### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Cr0WD** [steam3d/MagicPods-Windows#10]
1. Please add standard windows media keys for play/pause when airpods out of ear
![2020-05-15_14-47-30](https://user-images.githubusercontent.com/10212701/82047213-14c92a00-96bb-11ea-97be-5a8685d92110.png)

2. Please add feature to set "play/pause music" on double tap to AirPod
3. Please add support for Google Play Music Desktop Player. It supports standard media keys.(https://www.googleplaymusicdesktopplayer.com/)

**Comment by steam3d** [comment]
1. Windows does not allow manual control or getting information from **Global Media Control**
2. I'm trying to find a solution.
3. I will try to add support for this application

**Comment by steam3d** [comment]
Update to 1.0.42.0 and enable media keys in settings of Google Play Music Desktop Player.
