### ISSUE TITLE
"Searching Airpods" infinitely 

### ISSUE THREAD

**Issue by RavinduRanganath** [steam3d/MagicPods-Windows#103]
When I connect the Airpods Pro to the Computer via Bluetooth, the Application starts "Searching Airpods" but never finishes. The functions would not work as well. 
When I disconnect the Airpods via Bluetooth the Searching Stops and the App says that the "Airpods DIsconnected" message.

This is how the Log looks like.

15.06.2021 06:56:46 ----------------- ---- [Info]  |                | Run AirpodsState
15.06.2021 06:56:46 2D:58:9D:7B:B8:2D ---- [Info]  |GetPairedDevices| Find Ravindu’s AirPods Pro Model airpodspro Disconnected
15.06.2021 06:56:47 ----------------- ---- [Info]  |GetPairedDevices| programState Disconnected
15.06.2021 06:56:47 ----------------- ---- [Info]  |                | AirPods found
15.06.2021 06:56:47 ----------------- ---- [Info]  |                | Advertisement watcher started!
15.06.2021 06:57:10 ----------------- ---- [Error] |WaitActiveAudioS| Did not wait for the audio service activation {0.0.0.00000000}.{ae9db67c-509b-40c0-81c9-5e138c8b0f53}
15.06.2021 06:57:10 2D:58:9D:7B:B8:2D ---- [Info]  |ConnectionStatus| Ravindu’s AirPods Pro Connected (programState Searching)
15.06.2021 06:58:10 2D:58:9D:7B:B8:2D ---- [Info]  |ConnectionStatus| Ravindu’s AirPods Pro Disconnected (programState Disconnected)
15.06.2021 06:59:53 ----------------- ---- [Info]  |                | Advertisement watcher stopped: Success

**Comment by steam3d** [comment]
Hi. You can try to update your Bluetooth driver to the newest one. Some users said that it helps or uninstall the MagicPods, then reboot PC and again install the app.

If those steps does not helps then you Bluetooth dongle not supports. The windows controls all Bluetooth operations and i can't do anything with it.

**Comment by steam3d** [comment]
No feedback
