### ISSUE TITLE
Airpods wont connect at all

### ISSUE THREAD

**Issue by NotToxvic** [steam3d/MagicPods-Windows#105]
I have airpods pro and they wont connect at all. The app finds the airpods but it doesn't give me the pop up or anything and it just infinitely says "searching airpods" I tried multiple solutions and none of them work.

**Comment by steam3d** [comment]
Hi. What did you try to fix this problem? Can you upload a log file?

**Comment by NotToxvic** [comment]
I tried the support you did from your website https://help.magicpods.app/.  I tried infinite search, didn't work. I tried another but I forgot. Still didn't work. [
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6794320/MagicPodsServiceLog.txt)
](url)

**Comment by steam3d** [comment]
I see that at least once the application was able to receive information from the headphones.

> 09.07.2021 16:39:25 76:B9:F5:B4:13:D9  -78 [Info]  |  Print Action  | Case close(L ) : L out R in 

Value -78 means that AirPods far away from your PC. When value is -65 and below pop up animation will play

But information from AirPods was received when AirPods was using on other device (not your pc).

I can’t confirm infinity search error. 

Open the MagicPods on ‘support page’, clicks to the logo until it refresh. After it go to ‘general setting’ and scroll down, switch ‘log level’ to trace. Restart the app.

Then  bring AirPods to your Bluetooth antenna and try to open the case (don’t connect it to windows), wait some time. Uploaded the updated log file here.


Did you update the Bluetooth driver to latest version?

**Comment by NotToxvic** [comment]
I dont get how I got Value -78, when I open my Airods to connect to MagicPods its always near the computer with the case open and the Airpods inside. And I dont think my Airpods was connected to another device.
I have set the log level to trace and restarted the Magic pods app I have done what you said and it still didn't connect. And I am pretty sure I updated my Bluetooth driver to the latest version. I have Bluetooth version 5.0

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6795443/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
The MagicPods can’t find your AirPods because the Windows doesn’t receive any data from BLE devices like AirPods.

Since the work of bluetooth is completely controlled by windows, the problem is either in the drivers, or in the bluetooth module itself or in updating windows.

**Comment by NotToxvic** [comment]
Oh, I'll see if i can update  my drivers somehow or something
