### ISSUE TITLE
The style is wrong

### ISSUE THREAD

**Issue by no36bigyee** [steam3d/MagicPods-Windows#107]
![IMG_5438](https://user-images.githubusercontent.com/83548553/125682322-64a71d4f-d961-4d0e-8933-a22a67c1792e.jpg)

**Comment by steam3d** [comment]
Hi. I do not have the beats. It will be helpful if you collect a log data using [this tool](https://github.com/steam3d/MagicPods-Windows/issues/21).  And screencast the animation video from you iPad (about 20-30 second length).
Then I'll try to add color support

**Comment by no36bigyee** [comment]
Of course, I did as you asked, hope I can help you.

**Comment by no36bigyee** [comment]
https://user-images.githubusercontent.com/83548553/125689590-bc804fa7-a422-44a9-906c-250713fd81d8.mp4

**Comment by no36bigyee** [comment]
> Hi. I do not have the beats. It will be helpful if you collect a log data using [this tool](https://github.com/steam3d/MagicPods-Windows/issues/21). And screencast the animation video from you iPad (about 20-30 second length).
> Then I'll try to add color support



https://user-images.githubusercontent.com/83548553/125690391-4c589120-b588-44e9-a438-d39e33e77eab.mp4

[log.txt](https://github.com/steam3d/MagicPods-Windows/files/6818840/log.txt)

**Comment by steam3d** [comment]
Thanks. I got the data. I can't add yet, I need more data from other power beats pro colors. I will let you know as new details appear.

**Comment by steam3d** [comment]
Fixed.
