### ISSUE TITLE
Pop-up window's position is wrong after screen resolution changes

### ISSUE THREAD

**Issue by JasonWei512** [steam3d/MagicPods-Windows#108]
My laptop's screen resolution is 2736×1824 (DPI 200%). I set MagicPods's pop-up window position to "bottom right corner".
![Screenshot (7)](https://user-images.githubusercontent.com/16899918/126601658-fefb61f4-7038-4fac-81c7-34a7ca95acae.png)

However when I connect my laptop to an external screen (resolution 1920×1080, DPI 100%), the pop-up windows no longer show up in the bottom right corner.
![Screenshot (8)](https://user-images.githubusercontent.com/16899918/126601676-1d0416d1-8dfe-42d0-b41e-721f8af70e56.png)

After restarting MagicPods the pop-up window show up at the correct position.
![屏幕截图(9)](https://user-images.githubusercontent.com/16899918/126601702-fcbd9eca-a753-48d5-8d62-4a0374dafda3.png)

**Comment by steam3d** [comment]
I don't have Windows 11 yet. I. tested on windows 10, works as expected.
Do you turn off your notebook screen?
Can you show your monitor position?
![IMG_1857](https://user-images.githubusercontent.com/30986874/126945419-e2cfb0de-1ae1-41ac-8019-eeb03e23a25d.PNG)

**Comment by JasonWei512** [comment]
![image](https://user-images.githubusercontent.com/16899918/126946547-8c050c0a-775d-49fc-82ba-b3d42c1591ce.png)
1 is my laptop's screen. 2 is the external monitor.
This bug happens regardless of whether my laptop's screen is on or off.

**Comment by steam3d** [comment]
I will try to repeat the bug on my hardware. Looks like the app get the screen resolution from the "previous main monitor (laptop)" instead external monitor.

**Comment by steam3d** [comment]
Fixed. Update to 1.0.80.0.
