### ISSUE TITLE
Does not work on my Windows 11 computer

### ISSUE THREAD

**Issue by sameehsuhail** [steam3d/MagicPods-Windows#109]

**Comment by steam3d** [comment]
Hi. Can you upload the log file? I tested on windows 11 on my virtual machine and the MagicPods works well

**Comment by sameehsuhail** [comment]
is that the UI log or the service log

**Comment by sameehsuhail** [comment]
![image](https://user-images.githubusercontent.com/46632282/128537568-7a9ccd9f-26da-4ad3-8fa9-9775c03f21d9.png)
![image](https://user-images.githubusercontent.com/46632282/128537667-92a8648f-6c6e-45d3-97fd-2e544caad2bd.png)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/6946606/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6946607/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Do you have the two Bluetooth adapter on your pc? The MagicPods stuck on Bluetooth check

**Comment by sameehsuhail** [comment]
![image](https://user-images.githubusercontent.com/46632282/128539088-91f70c29-e19e-44ba-a542-56cbdf6eaa83.png)

**Comment by steam3d** [comment]
Try to run this [DeviceFinder](https://github.com/steam3d/MagicPods-Windows/issues/21). You should see a lot of creeping lines. You could try to restart or reinstall the MagicPods or reboot PC. Also check privacy settings, maybe Microsoft added some Bluetooth settings.

**Comment by sameehsuhail** [comment]
Restarting it did something, but now its stuck on searching.
![image](https://user-images.githubusercontent.com/46632282/128548729-6bdd6f2e-9bfd-45e3-b24e-7e1d16b519db.png)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/6947059/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6947060/MagicPodsServiceLog.txt)
And the log shows the same, but now it has connected

**Comment by steam3d** [comment]
Did you try to update Bluetooth drivers?

**Comment by sameehsuhail** [comment]
Yes I did

**Comment by steam3d** [comment]
Unfortunately, this is known issue when Windows does not send any Bluetooth data to the MagicPods. Since The Windows controls directly Bluetooth, there is no way to fix this issue.

There are 2 steps that help some users:
1. Remove the MagicPods -> Reboot PC -> Install it again
2. Update drivers to the latest on manufacture site (not through windows update)

I'm sorry, but from my side, I can't fix it

**Comment by steam3d** [comment]
No feedback
