### ISSUE TITLE
Endless notifications

### ISSUE THREAD

**Issue by debiskar** [steam3d/MagicPods-Windows#11]
After the last update, if you turn off the bluetooth, the application starts sending notifications and loading the processor. Reinstallation does not help. Please solve the problem as it is very annoying.
(Привет из России)

![1](https://user-images.githubusercontent.com/65491987/82143511-ed5e9280-985d-11ea-919d-d36f3e25bf71.png)
![2](https://user-images.githubusercontent.com/65491987/82143514-ef285600-985d-11ea-9cdf-ca2b2b29f07b.png)

**Comment by steam3d** [comment]
Привет, спасибо.  Я уже в курсе об этой проблеме. Решаю в ускоренном темпе.

**Comment by steam3d** [comment]
Обновите приложение до последний версии. Должно быть все впорядке.
