### ISSUE TITLE
Is it possible to add support for Beats Flex？

### ISSUE THREAD

**Issue by bigtiger-qian** [steam3d/MagicPods-Windows#110]
It has the same chip as airpods

**Comment by bigtiger-qian** [comment]
It has the same chip as airpods

**Comment by steam3d** [comment]
Hi. I don't have it and don't know how Beats Flex works. What are functions supporting the Beats Flex? (Looks like the beats flex supports only battery information)

**Comment by steam3d** [comment]
Hi. You can try to collect log using this https://github.com/steam3d/MagicPods-Windows/issues/21

Is magneticly play and stop works on Windows? (or available only for apple devices)

**Comment by joyhooian** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/7315615/log.txt)

### I changed the operation procedure to record the log a little bit:
1. Push the power button to turn on the Beats Flex.
2. Detached the two earphones.
3. Connected the two earphones.

Hope it useful😋

**Comment by steam3d** [comment]
I checked the log file.  I found battery. 
Can you repeat collecting logs?
1. Turn on the Beats Flex.
2. Put your Beats Flex on charge.
3. Remove your Beats Flex from charging
4. Upload the log file here
Also write the level of charge of the Beats Flex that was during the test and Beats Flex color.

**Comment by joyhooian** [comment]
I'm charging it right now.

Have you got some signals while detaching the earphones or powering up in the logs?

**Comment by steam3d** [comment]
No. Only battery information and perhaps when you "attach" two headphones together. (or maybe something different)

**Comment by steam3d** [comment]
Hi. Sorry for such a delay. I added support on 1.0.81.0 version. Please update the MagicPods and leave feedback.

**Comment by joyhooian** [comment]
Thanks!
