### ISSUE TITLE
Backwards auto audio switch is very slow

### ISSUE THREAD

**Issue by MulverineX** [steam3d/MagicPods-Windows#113]
It takes several seconds for the input device to be switched back to the airpods once they are put back in. Getting it down to a few seconds at most would be nice.

**Comment by steam3d** [comment]
The windows does not support direct access to the bluetooth.  Thus i can't direct access to the data that pass AirPods to pc.  In addition, getting data depends from Bluetooth that use the pc. I  don't have experience to writing custom drivers or etc.  Of course I'm looking for a solution, but so far unsuccessfully.

Anyway i can't improve this until i get direct access to the Bluetooth.
