### ISSUE TITLE
Connected to airpods but still not detected by the app

### ISSUE THREAD

**Issue by notcreatedyet** [steam3d/MagicPods-Windows#118]
I'm connected to the AirPods with my laptop and it still doesn't detect it. This worked before I purchased the app. Make it work now. 
![image](https://user-images.githubusercontent.com/71460655/131293423-83eeef5a-0751-404e-9505-426ffcccd6dc.png)

**Comment by steam3d** [comment]
Hi. Can you upload the log file? If the MagicPods worked before then it is not the MagicPods problem. Maybe windows update or bluetooth driver update broke something.

Did you buy the app recently? if so you can try uninstall the MagicPods, reboot PC and install it again. After trial some users had trouble with app. I can do nothing with this.

**Comment by steam3d** [comment]
No feedback
