### ISSUE TITLE
searching airpods 

### ISSUE THREAD

**Issue by min5624** [steam3d/MagicPods-Windows#119]
i have already connected to the laptop, restart and dowload the magicpods for several times but it still not work. It keeps say searching 
![Screenshot 2021-08-30 185854](https://user-images.githubusercontent.com/89782517/131335712-b302e1ac-432e-4804-a675-f208836870a1.png)

**Comment by steam3d** [comment]
Hi. Can you upload the log file?

**Comment by min5624** [comment]
> Hi. Can you upload the log file?

i don't know

**Comment by min5624** [comment]
how to do that


> Hi. Can you upload the log file?

**Comment by min5624** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7080865/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7080866/MagicPodsUILog.txt)

**Comment by min5624** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7080888/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7080889/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
This is known Windows issue. There is no solution from my side. Usually reinstall the app will resolve the issue. In some case you get this problem after bluetooth driver update. You need to install the latest driver from bluetooth manufactory site or older version if the newest does not help.

**Comment by min5624** [comment]
> This is known Windows issue. There is no solution from my side. Usually reinstall the app will resolve the issue. In some case you get this problem after bluetooth driver update. You need to install the latest driver from bluetooth manufactory site or older version if the newest does not help.



> This is known Windows issue. There is no solution from my side. Usually reinstall the app will resolve the issue. In some case you get this problem after bluetooth driver update. You need to install the latest driver from bluetooth manufactory site or older version if the newest does not help.

i don't know whether there is bluetooth drivers for me to update as i latop meet the requirement of bluetooth 4.0 and i have already reinstall it several times, even reset it for about 10 times

**Comment by steam3d** [comment]
Check bluetooth driver on manufactory site. I tested the MagicPods on Intel and Broadcom bluetooth modules on 3 different PC.

I also have feedback from little group users that have bluetooth module that can't work in two mode (listening to music and receive data) at the same time.

**Comment by min5624** [comment]
> Check bluetooth driver on manufactory site. I tested the MagicPods on Intel and Broadcom bluetooth modules on 3 different PC.
> 
> I also have feedback from little group users that have bluetooth module that can't work in two mode (listening to music and receive data) at the same time.

it is now accidently that it show the only percentage of the left ear while others don't but when i closed and reopen the case of the airpod it's gone forever

**Comment by min5624** [comment]
> Check bluetooth driver on manufactory site. I tested the MagicPods on Intel and Broadcom bluetooth modules on 3 different PC.
> 
> I also have feedback from little group users that have bluetooth module that can't work in two mode (listening to music and receive data) at the same time.
After an hour or more, it shows unexpectedly :)
![Screenshot 2021-08-31 193759](https://user-images.githubusercontent.com/89782517/131503914-66464a51-19c6-4f4c-b929-2a3513d97990.png)

**Comment by steam3d** [comment]
This means that the problem is definitely with bluetooth drivers.  it will be great if you tell the model of your bluetooth module to make a list of poorly compatible bluetooth modules.

**Comment by min5624** [comment]
![Screenshot 2021-08-31 203755](https://user-images.githubusercontent.com/89782517/131512508-d4fe3c81-d873-4f72-9065-42bcf5e98ea6.png)
i don't know which so i captured the screenshoot

**Comment by steam3d** [comment]
I am sorry i don't have the screenshot on English language.
Right click on Inter(R) Wireless Bluetooth(R) -> info or something like that -> device id

![image](https://user-images.githubusercontent.com/30986874/131729381-8772b4e4-ba6c-4e5e-92b3-408bd3ba474d.png)

**Comment by min5624** [comment]
i think the best would be from bluetooth 4.2 and up not 4.0 only

**Comment by steam3d** [comment]
Since release Bluetooth 4.0 was introduce Bluetooth Low Energy technology as [wikipedia](https://en.wikipedia.org/wiki/Bluetooth#Bluetooth_4.0) said. 
The MagicPods required 4.0 and above,  it will throw error message if bluetooth does not meet the requirements

**Comment by olzhaset** [comment]
Hi, I have the same problem. Infinite searching. I reinstalled the app and even bluetooth driver several times, it didn't help.
![image](https://user-images.githubusercontent.com/61376518/133888911-5e06d766-6465-4910-9ef0-4cc016b74849.png)

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7189872/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7189873/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
https://github.com/steam3d/MagicPods-Windows/issues/124
Hi. Did you try [this](https://github.com/steam3d/MagicPods-Windows/issues/124#issuecomment-921732032)?

**Comment by olzhaset** [comment]
Yep, they were already turned on.

**Comment by steam3d** [comment]
Try to turn off all switcher and turn in on again.  Maybe the windows rewrite some settings
It is difficult for me to advise something else, for 1.5 years I have never had such a problem on 4-5 computers. I cannot reproduce this problem

**Comment by olzhaset** [comment]
Does the app work on Windows 11? This is probably due to the fact that I have a preview build.

**Comment by steam3d** [comment]
@olzhaset Yes. on my virtual machine it works fine
![image](https://user-images.githubusercontent.com/30986874/133890180-ae67de09-ba03-4b35-88ff-f16d802c4126.png)

**Comment by olzhaset** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/7189955/log.txt)

**Comment by steam3d** [comment]
@olzhaset Looks like the Bluetooth works fine.I don't really understand what the problem might be, since both programs work according to the same algorithm. If one works, then the other program should work.

Did you turn off the MagicPods before reinstall it? The process names `MagicPodsService.exe` and `MagicPodsUI.exe` must be terminated before install the application again.

**Comment by olzhaset** [comment]
@steam3d It didn't help.

**Comment by steam3d** [comment]
@olzhaset Maybe you've tweaked your power settings or have a third-party antivirus? I double checked all windows builds, disable and enable all privacy setting. Multiple times reinstall the app. And it still works fine.

**Comment by olzhaset** [comment]
@steam3d None of this. I think the problem is in the airpods, it is not from the official store. It seems to be one of the Chinese copies...

**Comment by steam3d** [comment]
@olzhaset Can you check it out?

**Comment by olzhaset** [comment]
@steam3d It says here that "Repairs and Service Coverage: Expired" and this can't be, it's definitely fake one
![Screenshot 2021-09-18 203904](https://user-images.githubusercontent.com/61376518/133892544-f02261f8-4f12-4e19-971b-980b79eb6829.png)

**Comment by steam3d** [comment]
Can I ask your connect AirPods to your PC and run DeviceFinder app? (And upload the log.txt here)
I want to get the data from fake AirPods and compare it with original one.

**Comment by olzhaset** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/7190199/log.txt)

**Comment by steam3d** [comment]
@olzhaset the data is different from original AirPods, but still valid. There are two assumptions:
1. The AirPods fake
2. The AirPods was never paired with IOS device.
But I still do not know what the exact problem is, if I manage to repeat the error or find a solution, I will write
