### ISSUE TITLE
Feature Request : Taskbar icon color change when connected.

### ISSUE THREAD

**Issue by alierdogan70** [steam3d/MagicPods-Windows#12]
Hi,

Is it possible to change the taskbar icon when the airpods connected or disconnected like in this application? : https://apps.apple.com/us/app/battery-stats-for-airpods/id1405763798?mt=12

It could be nice to have partially colored when only one airpod is connected.

**Comment by steam3d** [comment]
Hi. Yes it is possible. I will think about your suggestion. Thx for feedback.

**Comment by steam3d** [comment]
Added. Update to ver. 1.0.28.0
