### ISSUE TITLE
Animation spins really fast

### ISSUE THREAD

**Issue by FM-050** [steam3d/MagicPods-Windows#120]
When i open the case, the airpods spin slowly at first then speed up and spin really fast for some reason.

**Comment by steam3d** [comment]
Hi. Can you show example? I think you have a 144hz monitor. This is known issue i am looking for a solution.

**Comment by FM-050** [comment]
Hey. Yeah i have a 300hz laptop screen. Do you still need me to send a video of it?

**Comment by steam3d** [comment]
Yes. It will help understand what going on

**Comment by FM-050** [comment]
Hi, here's the link to the video.
https://photos.app.goo.gl/gLt6X6Q8wfM5ciwc8

**Comment by steam3d** [comment]
Thx. I will try to fix it

**Comment by FM-050** [comment]
Thanks!

**Comment by steam3d** [comment]
Fixed. Update The MagicPods to 1.0.75.0.
Will be great to get feedback from you

**Comment by FM-050** [comment]
Works perfectly! Thankyou.

**Comment by steam3d** [comment]
Perfectly. Please rate the app if it doesn't bother you
