### ISSUE TITLE
Application closes when trying to open

### ISSUE THREAD

**Issue by Khomuttsan** [steam3d/MagicPods-Windows#123]
Привет, скачал триал
При попытке открыть, на 1 секунду появляется приложение (лого) и сразу же закрывается
Пробывал пререзагрузку, установить заново, средства восстановления ... не помогает

**Comment by steam3d** [comment]
Привет, до Вас был еще один такой случай, мне прислали решение, но я сам не проверял так как не могу повторить эту ошибку. Сначала проверьте установлены ли все обновления.

1. `На диске C нажать `Свойства` -> `Безопасность`, Gотом `Изменить` и нажать `Добавить`. 
2. В появившемся окне выбрать `Дополнительно` -> `Поиск`,затем найти и выбрать имя `ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ` и нажать `Ок` и еще раз `Ок`.
3. Выбрать `ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ` и дать полный доступ, нажать `Применить`
4. Теперь приложение должно запускаться, если нет нужно его переустановить. 

После того как все заработало можно удалить доступ для `ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ`

https://user-images.githubusercontent.com/30986874/132322865-8cb7791b-e82b-4ecb-a0d9-88e51ed52f1d.mp4

Приложение тестировалось только на официальных сборках от Windows 11 (самой новой) до Windows 10 (10.0.17763.1637 самой старой).

**Comment by steam3d** [comment]
Нет обратной связи

**Comment by Khomuttsan** [comment]
оказались китайские подсы

ср, 3 нояб. 2021 г. в 10:49, Alexander Maslov ***@***.***>:
