### ISSUE TITLE
App doesnt detect Airpods Pro anymore!

### ISSUE THREAD

**Issue by taimooralibukhari** [steam3d/MagicPods-Windows#124]
Suddenly it disconnects Airpods Pro and unable to connect since then when after restart Airpods Pro are working fine with my pc and I can hear everything but app isnt detecting device anymore.

**Comment by steam3d** [comment]
Hi. Can you upload a log file? This is 100% Bluetooth driver issue not the MagicPods, usually restart the pc helps.

**Comment by taimooralibukhari** [comment]
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7180901/MagicPodsUILog.txt)


my drivers are up to date and there is no issue with airpods pro itself just magicpods stopped detecting my airpods. I've tried restarting and reinstalling

**Comment by steam3d** [comment]
Please upload both log files. More info here https://help.magicpods.app/report-issue/

**Comment by taimooralibukhari** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7184959/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Based on your log file the MagicPods works fine. The Windows does not allow to use the Bluetooth. No one knows why the Windows has such behaviour.

The only solution is this, but you have already tried it:
https://help.magicpods.app/issue-infinite-search/

have you changed the power saving settings?

**Comment by steam3d** [comment]
Also make sure that you have turn on those options
![image](https://user-images.githubusercontent.com/30986874/133777250-438b5d5f-9ab5-491e-8b40-6926e8247c9b.png)

**Comment by taimooralibukhari** [comment]
These settings were on but turned them off and switched them back on. MagicPods started working properly. Thanks!!!!!

**Comment by steam3d** [comment]
Nice to hear. I would be glad if you rate MagicPods in the Microsoft Store.
