### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jim-agapov** [steam3d/MagicPods-Windows#125]
Привет. Не пойму как работает программа: висит "поиск AirPods", хотя наушники подключены. Прошу помочь
![2021-09-18_19-32-49](https://user-images.githubusercontent.com/51953754/133892385-906a7b87-4e48-4dc0-b94f-dca502a89fc0.png)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7190087/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7190088/MagicPodsServiceLog.txt)
ь

**Comment by steam3d** [comment]
Добрый день, вы обновили программу или установили впервые?

**Comment by jim-agapov** [comment]
Установил впервые. До этого просто пользовался наушниками с помощью стандартных средств Windows

**Comment by steam3d** [comment]
Программа работает без каких либо проблем, с большой вероятностью проблема не в ней.
В чем может быть проблема:
1. Блютус модель который используется в системе не умеет работать в двух режимах одновременно.
2. Проблема в драйверах

Рекомендуют попробовать скачать драйвера для вашего блютус прямо с сайта производителя, обычно они там новее чем те, что предлагает обновление Windows.

Так же используется Windows 10.0.18363.0 (сборка 2019 года), если вы используете LTSC c 90% вероятностью на ней будут проблемы с приложением.

Если после обновления проблема сохраняется, как вариант попробовать удалить приложение. Проверить, что в диспетчере задач нет запущенных процессов "MagicPodsService.exe" и "MagicPodsUI.exe", перезагрузить ПК и снова установить приложение. (В очень редких случаях это помогает).

Так как управление блютус полностью берет на себя Windows, у меня нет никакой информации, в чем конкретно дело.

**Comment by jim-agapov** [comment]
Заметил, что в службах у меня нет MagicPodsService.exe" и "MagicPodsUI.exe. Можете мне прислать ссылку на дистрибутив, чтобы я смогу установить ваше приложение не из магазина, а по старинке?

**Comment by steam3d** [comment]
@jim-agapov обычного установщика нет, приложения завязано на работе через Microsoft Store.  Если у Вас пробный период, то можно спокойно переустанавливать через Microsoft Store. 
Вы попробовали шаги которые я описал выше? (Я могу дать промокод, но если приложение не совместимо с устройством имеет ли это смысл)

**Comment by jim-agapov** [comment]
Программу я купил, так что промокод не нужен. Предложенные операции делал. Не помогло. Вы не ответили касательно отсутствия запущенных служб

**Comment by steam3d** [comment]
Это не службы, а процессы. Они запускаются автоматически, когда приложение открыто (они у вас были запущены, видно по скриншоты первому). Но в некоторых случая они остаются активными даже после закрытия приложения (некоторое время). По этому их надо закрыть перед переустановкой. 
![image](https://user-images.githubusercontent.com/30986874/133921945-274bb325-1f0e-4d93-8d8a-52f53eb3216a.png)

Так же можно попробовать запустить [DeviceFinder](https://github.com/steam3d/MagicPods-Windows/issues/21), что бы проверить работу Bluetooth модуля. При подключенных AirPods должны бесконечно бегать строчки:
![image](https://user-images.githubusercontent.com/30986874/133922203-0e0297cb-fa5b-4f64-9fce-8cd24e0c9754.png)

**Comment by jim-agapov** [comment]
![2021-09-19_14-23-12](https://user-images.githubusercontent.com/51953754/133922283-5e5f8908-2e97-45ef-a89f-514930170b54.png)
Музыка через наушники играет, но никакие строчки не бегают

**Comment by steam3d** [comment]
Значит оборудование не совместимо. 
Так как вы приобрели приложение, то Вы можете сделать [возврат товаров](https://support.microsoft.com/ru-ru/account-billing/%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2-%D0%BF%D1%80%D0%B8%D0%BE%D0%B1%D1%80%D0%B5%D1%82%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-microsoft-store-%D0%B4%D0%BB%D1%8F-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0-%D0%B8%D0%BB%D0%B8-%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82%D0%B0-%D0%B4%D0%B5%D0%BD%D0%B5%D0%B6%D0%BD%D1%8B%D1%85-%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2-81629012-aa4f-f48b-2394-8596f415072b)

Не могли бы скинуть название вашего Bluetooth модуля, его можно посмотреть в диспетчере устройств выбрал в выпадающем меню `ИД оборудования`. Я добавлю его в список несовместимых. Выглядит примерно так:
![image](https://user-images.githubusercontent.com/30986874/133923104-23c1ae01-ce8e-42b1-9a13-5d09c38208d6.png)

**Comment by jim-agapov** [comment]
![2021-09-19_14-56-20](https://user-images.githubusercontent.com/51953754/133923259-a02ddf7b-94cc-4595-9b01-1ddced15491a.png)
Почти тоже самое, что вы прислали. А никак не сделать, чтобы заработало?

**Comment by steam3d** [comment]
я бы с удовольствием сделал, но работой блютус полностью управляет Windows. Я даже не знаю, какая тип ошибки у вас происходит. Например приложение DeviceWatcher ответило, что операция выполнена, но по факту ничего не работает.

Был еще у одного человека такой случай, он перепробовал кучу версий блютус драйверов и у него заработало.

**Comment by jim-agapov** [comment]
Обновил драйвер и все заработало. Спасибо!
![2021-09-19_15-40-22](https://user-images.githubusercontent.com/51953754/133924673-d6858ad4-52a4-4199-90e6-97dc61bdf427.png)
о!

**Comment by steam3d** [comment]
Отлично, закрываю вопрос
