### ISSUE TITLE
Shows charging percent incorrectly

### ISSUE THREAD

**Issue by Comeodore** [steam3d/MagicPods-Windows#126]
My AirPods with your application show incorrect charging percentages for both headphones and the case (stable 100, 100 and 75), although everything shows correctly on Iphone & Ipad, how to fix it?

**Comment by steam3d** [comment]
Hi. The MagicPods supports only original AirPods.

You can upload screenshot with battery info (from iPhone or iPad) and write full AirPods fake model.

also you can collect some information about headphones using this program
https://github.com/steam3d/MagicPods-Windows/issues/21

This does not add support, but at least let's see how they work

**Comment by Comeodore** [comment]
> Hi. The MagicPods supports only original AirPods.
> 
> You can upload screenshot with battery info (from iPhone or iPad) and write full AirPods fake model.
> 
> also you can collect some information about headphones using this program #21
> 
> This does not add support, but at least let's see how they work

1) 
![SDvx5ra](https://user-images.githubusercontent.com/55732318/136454738-cac23bcd-2050-487c-89b0-709231868ccc.png)
![0Aiv8vv](https://user-images.githubusercontent.com/55732318/136454748-e7653993-04c7-40e9-bef9-0c1418fc6335.png)
2) Apple AirPods Pro Mirror
3
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/7306503/log.txt)
)
