### ISSUE TITLE
Multiple airpods show up as same name

### ISSUE THREAD

**Issue by barrymmartinLODS** [steam3d/MagicPods-Windows#129]
How can I delete a pair of airpods from what MagicPods has seen before.

I connected a pair of airpods that had the same name as my existing airpods and how when either set is opened, even though 1 set is not paired in windows, they both make a popup show up in magicpods.

**Comment by steam3d** [comment]
There is no solution for it now.  One thing that i can do it add option to do not show popup animation while AIrPods is connected.

**Comment by steam3d** [comment]
No feedback.
