### ISSUE TITLE
Default/disabled devices

### ISSUE THREAD

**Issue by paksisoma** [steam3d/MagicPods-Windows#130]
Disabling or setting other devices as default in Windows Sound then reconnecting the AirPods it forgets what was disabled/default.

Before reconnection:
![before](https://user-images.githubusercontent.com/78373326/138297514-11abd8b4-9271-49f6-8e41-bf547dd37ed7.png)

After reconneciton:
![after](https://user-images.githubusercontent.com/78373326/138297534-134fe66b-b957-475f-b523-34f9d3dda342.png)

**Comment by steam3d** [comment]
"Hands-free" is used to initialise the connection. Therefore, it automatically turns on. I can disable service when connection established or AirPods disconnected, but this can lead to freezing of audio devices, because windows does not work very well with bluetooth devices.

**Comment by paksisoma** [comment]
Without MagicPods, Windows can initialize the disabled devices.

**Comment by steam3d** [comment]
https://github.com/steam3d/MagicPods-Windows/issues/172

**Comment by steam3d** [comment]
Update to 1.0.83.0. Now Bluetooth services will not turn on after connection.
