### ISSUE TITLE
PLEASE UPDATE TO SUPPORT AIRPODS 3 , WASTED MONEY ON APP I CANT USE

### ISSUE THREAD

**Issue by junglelee3113** [steam3d/MagicPods-Windows#131]

**Comment by steam3d** [comment]
The MagicPods supports the AirPods 3 now. Update to 1.0.79.0.  Let me know if everything works.

**Comment by junglelee3113** [comment]
Awesome, thanks! really cool to be able to communicate with development
team on this , will try as soon as I get home and let you know how it works
