### ISSUE TITLE
AirPods 3 Support

### ISSUE THREAD

**Issue by vap0r1x** [steam3d/MagicPods-Windows#132]
[logs.txt](https://github.com/steam3d/MagicPods-Windows/files/7426663/logs.txt)

**Comment by steam3d** [comment]
The MagicPods supports the AirPods 3 now. Update to 1.0.79.0.  I still do not have the AirPods 3, let me know if everything works.

**Comment by Niki2k1** [comment]
Works perfectly, thank you very much for your work. Amazing App :)

**Comment by vap0r1x** [comment]
Yep works perfectly!
