### ISSUE TITLE
Airpods Name Showed as Random Symbols

### ISSUE THREAD

**Issue by m4l0n** [steam3d/MagicPods-Windows#134]
![image](https://user-images.githubusercontent.com/67460463/139529610-fec07043-fbd2-4a77-9e1d-e6e2aece9ab5.png)

OS: Windows 11 21H2
Airpods Model: Airpods Pro
Airpods Firmware: 4A400 (Latest)

As you can see from the image above, the name appears as random symbols. It's the same on the popup too. I've tried reinstalling the app from Microsoft Store to no avail.

**Comment by steam3d** [comment]
How is your AirPods name displayed in Windows Bluetooth settings?

**Comment by m4l0n** [comment]
It's displayed as the same too. Hmm, seems like it isn't the app problems then. My bad. You have any idea why this might have happened?

**Comment by m4l0n** [comment]
Sorry, reconnected to the airpods and no issues now.
