### ISSUE TITLE
Add support for Mica effect

### ISSUE THREAD

**Issue by Void48** [steam3d/MagicPods-Windows#135]
https://docs.microsoft.com/en-us/windows/apps/design/style/mica

**Comment by steam3d** [comment]
I see no reason to switch from Acrylic blur to Mica. The application does not often run in the foreground and there will not be much performance gain.

If you mean apply  the Mica to popup windows - it is impossible, classic windows apps does not support winui yet

**Comment by Void48** [comment]
Now that there's no Acrylic can the mica effect please be implemented for the application? Appreciate all the work you put into this btw.

**Comment by steam3d** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/30986874/145643201-7a7d6e1b-73b8-45f4-9bb5-e0a77cd3dd51.png">
 I can apply Mica only on this panel, because the AirPods videos has static background. There are many ways to create video with transparent background, but it takes lot's GPU, CPU and Ram usage.

**Comment by Void48** [comment]
> <img alt="image" width="768" src="https://user-images.githubusercontent.com/30986874/145643201-7a7d6e1b-73b8-45f4-9bb5-e0a77cd3dd51.png">
> 
> I can apply Mica only on this panel, because the AirPods videos has static background. There are many ways to create video with transparent background, but it takes lot's GPU, CPU and Ram usage to playback

Can't the mica effect go away after the AirPods videos show? So the mica effect would only be visible when the AirPods are disconnected..

**Comment by steam3d** [comment]
Yes, it is possible. I will think about how best to implement this effect. I am also waiting for Microsoft to finish working on its WinUI 3.0, to completely switch to it.

**Comment by steam3d** [comment]
Added. Update to 1.0.80.0.
I disabled the mica on page background for now. I think the better way it makes transparent videos than to change background color. I have some thoughts on how to do it.
