### ISSUE TITLE
How do you smoothly switch connection between PC and iPhone?

### ISSUE THREAD

**Issue by WestXu** [steam3d/MagicPods-Windows#139]
Just say I'm listening music with airpods connected to my iphone, and browsing internet on my PC at the same time. A video pops up on my PC and I want to watch it. How do I smoothly switch my airpods connection to my PC, and switch back later after I finish watch that video? How MagicPods helps with this situation? 

Thanks. Cool project.

**Comment by steam3d** [comment]
Hi. The MagicPods can't help, but you can connect your AirPods and iPhone to PC and stream music from iPhone to PC and from PC to AirPods..

This way gives you iPhone audio and pc audio on your AirPods on the same time.

**Comment by WestXu** [comment]
OK. I have to buy another Airpods then. 😂

**Comment by louisefindlay23** [comment]
Similar to this, how does auto-connect work if you're using this and iOS devices?

**Comment by WestXu** [comment]
Let me walk through my switching process:

1. Listening to music from iPhone while browsing stuff on PC
2. Find a video on my PC, want to watch it
3. take off my Airpods, put them back to the case, and keep the case top open
4. Long push the button on the Airpods case until the case LED starts glimmering, which is when it's disconnected from my iPhone
5. Open Bluetooth setting on my PC, choose the Airpods, select connect, and wait for it to be connected
6. Put the Airpods on and watch the video. You can close the case now
7. After watching the video, take the Airpods off again, put them in the box, and close it. It should be disconnected from my PC now
8. Open the case again, and unlock my iPhone, wait for Airpods popping up and tap connect
9. Put on the Airpods and keep on to my music

This process is crazy.

**Comment by steam3d** [comment]
You are doing it wrong. There are two stage:

First stage (Pair AirPods to Windows PC):
1. Open the case with AirPods inside
2. Long push the button on the Airpods case until the case LED starts glimmering white color
3. Open Bluetooth setting, click add device and wait until AirPods was found and press connect

AirPods is ready to work on Windows


Second stage (Connect AirPods)
1. You are listening to music on your iPhone and want to watch video on your PC. Both AirPods in your ears or on the table, never mind.
2. Open settings on Windows. Go to Bluetooth section, choose your AirPods and press connect.
2.1. Connect using the MagicPods. Right-click on the MagicPods tray icon and choose your AirPods or click connect button in the popup animation. Wait for the headphones to connect.
3. Done

To back on iPhone:
Open settings on iPhone. Choose Bluetooth section and tap on your AirPods.

**Comment by WestXu** [comment]
Wow. I never knew that one device could actively rob the connection from another already-paired device. I just tried it and it should works!

Thank you so much for saving my life.

**Comment by steam3d** [comment]
Glad that it helped you
