### ISSUE TITLE
Battery drain, high cpu usage of magic pods

### ISSUE THREAD

**Issue by RadianMay** [steam3d/MagicPods-Windows#140]
Keeping magicpods idle in the background appears to have high cpu usage and therefore high battery drain on a laptop. Magic pods and the bluetooth support agent appears to use a combined 4% of cpu, which drains the battery quickly. Cpu usage is much lower with magicpods closed. Is there a way to optimize cpu usage?

**Comment by steam3d** [comment]
This screenshot shows the battery usage for the last 7 days.  I have intel core i5 11 generation. The MagicPods uses about 0-1% CPU when it IDLE and 2% battery for 7 days.
![image](https://user-images.githubusercontent.com/30986874/141344158-72d7f20e-65c7-4383-b22c-593e3ab702e1.png)

More battery drain can be attributed to more apple devices around. The MagicPods check each device. But I've done quite a bit of work to minimize the drain on the battery.

What hardware do you have on your laptop?
