### ISSUE TITLE
Pop-Up Connection Window

### ISSUE THREAD

**Issue by Linderkamp** [steam3d/MagicPods-Windows#141]
This is not really a bug but a feature issue.
The Pop-Up Connection Window is shown not long enough, I am never able to click connect before the window disappears again. Would be nice if I could set a time how long the window is shown or at least make it 1 or 2 seconds longer visible.

**Comment by steam3d** [comment]
Hi. The AirPods itself sends the close popup command. If you use AirPods or AirPods Pro you can open the case, then click connect and then take out AirPods or enable auto connect in this case AirPods will connect when you put out one AirPods from case.
