### ISSUE TITLE
Airpods Pro Infinite Searching

### ISSUE THREAD

**Issue by razoo-choudhary** [steam3d/MagicPods-Windows#142]
After i open the case it shows searching and doesnot shows Airpods. My Pc Supports Bluetooth 5.
[DebugLog.zip](https://github.com/steam3d/MagicPods-Windows/files/7571969/DebugLog.zip)
0

**Comment by razoo-choudhary** [comment]
[DebugLog.zip](https://github.com/steam3d/MagicPods-Windows/files/7571966/DebugLog.zip)

**Comment by steam3d** [comment]
Hi. Did you try those steeps? https://help.magicpods.app/issue-infinite-search/
Update driver to the newest one usually helps.

**Comment by razoo-choudhary** [comment]
i tired everything mentioned in that link none worked, even updated to latest drivers and even the OS to windows 11.

**Comment by steam3d** [comment]
It means that your Bluetooth module is not compatible with the additional functions of AirPods.  This is not a software problem, for my part I cannot do anything.

**Comment by razoo-choudhary** [comment]
Can you please confirm that, my laptop is Asus ROG G531GT, Bluetooth Version 5.0

**Comment by steam3d** [comment]
I can only say that the MagicPods try to get data using your bluetooth module and in response, it does not receive any data. Considering that there are a huge number of computer configurations as well as windows settings, it is almost impossible to determine the exact reason.

In 90% of cases, users who faced such a problem were helped by installing a Bluetooth driver, but I was not told which drivers were installed (new or old one).

**Comment by juanfcopina** [comment]
Hello, none of the options that you propose to solve this Windows 11 problem does not work. Please try to fix it or refund the money paid for the purchase of the application.
