### ISSUE TITLE
YouTube videos pauses itself

### ISSUE THREAD

**Issue by NSTrains** [steam3d/MagicPods-Windows#143]
When the app is running, YouTube videos keep pausing itself.

Windows 10 21H1
Google Chrome latest version

**Comment by steam3d** [comment]
Hi. Attach the log files https://help.magicpods.app/report-issue/

**Comment by NSTrains** [comment]
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7575434/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7575435/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
There are two pair of airpods around your pc. The MagicPods can't detect which is your AirPods.  In this case, nothing can be done, the Apple is not allowed to accurately identify the AirPods.
