### ISSUE TITLE
It might be possible to add Play/Pause support for PotPlayer

### ISSUE THREAD

**Issue by RainEggplant** [steam3d/MagicPods-Windows#144]
As mentioned in #32, PotPlayer *by default* does not react on system play/pause command when it's in background. But there is a "Turn on global media control keys" option under "General > Keyboard > Support Multimedia Keyboard". After I turned this on, I was able to pause PotPlayer using my airpods' button or the media key on my keyboard when it's in background. So it might be possible to add Play/Pause support for PotPlayer.

**Comment by steam3d** [comment]
The PotPlayer will take all control on media keys. This will give unpredictable results for other programs. For example, you may accidentally play content from another player, or nothing happens at all.

I can try to add it as an experimental feature, but it will be hidden from everyone.

**Comment by RainEggplant** [comment]
Thanks for replying. Looking forward to seeing it added.

**Comment by steam3d** [comment]
Added. Update to 2.0.50.0
