### ISSUE TITLE
Auto pause problem

### ISSUE THREAD

**Issue by formintnine** [steam3d/MagicPods-Windows#145]
When wearing only one headset, take off the headset and the music cannot stop automatically; When you don't take off your headphones, open the headphone box and the concert will stop automatically.

At present, ear detection is not particularly sensitive. Can you improve it, thank you

**Comment by steam3d** [comment]
I checked everything works as expected.  I can't reproduce this issue. 
About case: When you open the case with one AirPod inside it automatically connects to the active AirPod.  As a result, we get one earphone in the ear, the other outside the ear, therefore the MagicPods will pause music.

**Comment by f-liva** [comment]
Doesn't work with AirPods Max.

Windows 11

**Comment by steam3d** [comment]
Fixed. Several people have confirmed that it works.
