### ISSUE TITLE
MagicPods shows connect window when my AirPods is not opened

### ISSUE THREAD

**Issue by agoudbg** [steam3d/MagicPods-Windows#148]
MagicPods often shows a window that seems I have start using my AirPods. The window's title is my AirPods' name, but the battery seems to be always wrong and same. e.g. 85%, 95% for several times.
However I haven't use my AirPods at that time... I wonder if there's others using their AirPods, but the name is really mine, and the battery was always a few percent.

**Comment by steam3d** [comment]
Hi. Can you [upload the log files](https://help.magicpods.app/report-issue/) here? Looks like someone around you also use AirPods

**Comment by agoudbg** [comment]
Yes, here's the logs 
[magicpods_log.zip](https://github.com/steam3d/MagicPods-Windows/files/7639650/magicpods_log.zip)

**Comment by steam3d** [comment]
I see that you tried to change *search radius. *Does the popup window still
appear when the search radius is less than 50?

чт, 2 дек. 2021 г. в 09:52, agoudbg ***@***.***>:

**Comment by agoudbg** [comment]
OK, I have changed this to 30.
The problem may appear a few days later. I'll report it if it happens again. 
What's more today MagicPods warned me that my AirPods' battery is only 5%, but my iPhone showed their battery is 80+%. I feel that MagicPods' battery is always not exact :-(
You can see now MagicPods shows 85% (9 times in 10 times), but iPhone shows 88%. 
![image](https://user-images.githubusercontent.com/55237525/144375206-8c86f15d-fac7-4c22-87a4-8b0c49a64f33.png)

**Comment by steam3d** [comment]
Apple highly hides information about AirPods. Many functions cannot be
implemented as I would like. The battery accuracy is +-5%.

чт, 2 дек. 2021 г. в 10:15, agoudbg ***@***.***>:

**Comment by agoudbg** [comment]
Haven't see the problem these days and I think it's time to close this issue. If it happens again I'll report it. 
MagicPods really works like a magic, thank you for building such a fantastic application :-)
