### ISSUE TITLE
Taskbar on Top

### ISSUE THREAD

**Issue by IyadhGm** [steam3d/MagicPods-Windows#15]
I have the taskbar set on the top. When the Case is being detected, it leaves out the wrong part of the screen not greyed out, as you can see [here](https://imgur.com/a/qTNPQjn). Is it possible to grey out the whole and not the taskbar wherever it is?

**Comment by steam3d** [comment]
Hi. I will disable "grey out" in next update. Because i planned to add option size of animation and maybe different types of animation appearance. It will look like this.  
![image](https://user-images.githubusercontent.com/30986874/83975520-0a3a3300-a8fd-11ea-9c3e-07796e32af4c.png)

**Comment by IyadhGm** [comment]
Thank you! <3

**Comment by steam3d** [comment]
Added. Update to ver. 1.0.28.0
