### ISSUE TITLE
Magicpods doesnot compatible with NVIDIA Advanced Optimus

### ISSUE THREAD

**Issue by kenny273** [steam3d/MagicPods-Windows#150]
It is hoped that Magicpods will be compatible with the features widely used in gaming laptops
![屏幕截图 2021-12-05 160655](https://user-images.githubusercontent.com/93571028/144738909-674eadd9-41b9-4149-8a92-11502ae8dd32.png)
![屏幕截图 2021-12-05 160805](https://user-images.githubusercontent.com/93571028/144738845-bd5e35cf-b429-409d-a467-de50ab3296f3.png)
)

**Comment by steam3d** [comment]
Hi. What’s the problem?

**Comment by kenny273** [comment]
> Hi. What’s the problem?

Nvidia advanced optimus auto-graphics switching is not available when Magicpods are running in the background

**Comment by steam3d** [comment]
Possible Windows issue, because some of the apps like Terminal, Notepad etc. have the same issue.
