### ISSUE TITLE
Unlimited search, but Bluetooth connection

### ISSUE THREAD

**Issue by pink-bananas** [steam3d/MagicPods-Windows#153]
Successful connection but no popover animation, tried various solutions, but to no ava
![微信图片_20211208173814](https://user-images.githubusercontent.com/95742300/145185138-0ae4ba4f-33b4-4a42-a328-68009abde096.jpg)
il

**Comment by steam3d** [comment]
Hi. [Upload a log files here](https://help.magicpods.app/report-issue/)

**Comment by pink-bananas** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "steam3d/MagicPods-Windows"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [steam3d/MagicPods-Windows] Unlimited search, but Bluetooth connection (Issue #153)





 
Hi. Upload a log files here
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by steam3d** [comment]
I did not receive any log files

**Comment by pink-bananas** [comment]
我尝试了各种方法，但是没有解决，感觉应该不是我耳机的问题，因为我用别人的耳机可以识别，我也重置耳机，但是显示一直在搜索（蓝牙已经连接成功了，只是没有弹窗），最后失败，我的电脑是神州战神Z7M-KP7GC,用的是windows11系统,耳机是airpods一代




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "steam3d/MagicPods-Windows"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 凌晨5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [steam3d/MagicPods-Windows] Unlimited search, but Bluetooth connection (Issue #153)





 
I did not receive any log files
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
