### ISSUE TITLE
Auto pause/play not working with AirPods Max

### ISSUE THREAD

**Issue by cleanlock** [steam3d/MagicPods-Windows#155]
Hi,

auto pause/play when stop/start wearing is not working with my AirPods Max. I'm using Spotify, and it should work (as your website states).

**Comment by steam3d** [comment]
Hi. Did you try other players?

**Comment by cleanlock** [comment]
Yes, doesn't work in general.

**Comment by steam3d** [comment]
Open the MagicPods on Support page. Click 5 or more times to the logo image until the page refreshes. After it go to General settings page, scroll down to bottom of the page and switch log level to trace. Restart the MagicPods. (Right click on tray icon exit).

Connect your AirPods Max and try to pause / play music as you did before. After it send the log files again.

I checked the MagicPods with my AirPods Max - everything works as expected

**Comment by cleanlock** [comment]
I've sent the logs via mail again.

Music still doesn't pause when I lay my AirPods Max on the table.

**Comment by steam3d** [comment]
Did you change the log level? I see that you enable developer menu, but did not change the log level to trace

**Comment by cleanlock** [comment]
Oh my bad, didn't do that. sent you new logs.

**Comment by steam3d** [comment]
Your AirPods Max is sending different data compared to mine. Can you send your AirPods Max firmware version? 
I wrote down your problem. Unfortunately i can't do anything now. I need at least 2 more people to confirm the problem.
Any change in how the MagicPods works with AirPods Max will affect other users, so I can't just change the algorithm right now.

**Comment by cleanlock** [comment]
I'm on the latest firmware 4A400.

**Comment by zzznz27** [comment]
Hey i have the same issue for Airpod Max. 
No ear detection when taking off the headphones

I've got the trace logs if you would like to see them.

**Comment by HTS126** [comment]
I also have the same ear detection issues with AirPods Max :) 
I can send the trace logs if you like!

**Comment by steam3d** [comment]
@zzznz27 @HTS126 Using this [answer](https://github.com/steam3d/MagicPods-Windows/issues/155#issuecomment-989722444) provide the logs. 

Also provide information:
- firmware version
- Have headphones been used with apple devices?
- What settings do you have for AirPods Max? (Digital crown, spatial Audio etc)
- Your region

I will try to figure out why your AirPods Max is sending data different from mine.

**Comment by HTS126** [comment]
I've emailed that info to you, hope it helps!

**Comment by f-liva** [comment]
Same here with AirPods Max. Logs attached.

How can I find the firmware version on Windows?
The headphones was connected first time to an iPhone but not disconnetted and used only on Windows
Where can i find the settings enabled like digital crown or spatial audio?
My region is italy

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7903783/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7903784/MagicPodsUILog.txt)

**Comment by Myradose** [comment]
I have the same issue with my Airpods Max. Ironically enough, my fake Airpods Pro in ear detection works flawlessly, but my authenic Airpods Max never pause when I take out my headphones. I've attatched the logs below after restarting and only using the Airpods Max. I put them on my ears and took them off a few times.

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7938037/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7938038/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
I released 1.0.81.0 update. Try to update and leave feedback works ear detection or not

**Comment by f-liva** [comment]
My side now works perfectly! What was the problem?

**Comment by steam3d** [comment]
I not sure but looks like some AirPods Max has minor changes from others. This may have something to do with how the AirPods Max was set up originally.

**Comment by HTS126** [comment]
Hi, I've just tried the latest version, and it's working now!

AirPods Max are pausing audio correctly if I take them completely off, or if I lift off the left ear cup. Interestingly, if I lift off the right ear cup, nothing happens. Not sure if this is meant to be how it works, or a bug? :)

**Comment by steam3d** [comment]
@HTS126 
I am not sure that it is the bug, because i tried on my iPhone, it pauses music about 1/10 times. The MagicPods also pauses the music sometimes.

**Comment by steam3d** [comment]
Hi. I need help to check AirPods Max.I need to collect extra data to be sure that everything works as expected.
Could you do those steps?

1. Downalod and unzip [Device finder](https://github.com/steam3d/MagicPods-Windows/files/4911413/DeviceFinder_1.zip)
2. Connect AirPods Max to PC. Airpods Max must be unwear (or placed on the table)
3. Run the Device Finder and wait 5 seconds
4. Wear your AirPods Max and wait 5 seconds
5. Close the Device Finder
6. You can unwear or disconnect AirPods Max now
7. Upload the log files that appeared near the exe file.
