### ISSUE TITLE
Flickering when switching between settings categories

### ISSUE THREAD

**Issue by Void48** [steam3d/MagicPods-Windows#156]
![SwcaJaPyPP](https://user-images.githubusercontent.com/85196642/145627007-1d374e99-0c24-44a6-a712-599402fd3b99.gif)

**Comment by Void48** [comment]
My windows scaling is set to 125% and the resolution of my monitor is 1440p@165Hz if this helps

**Comment by steam3d** [comment]
Hi. This is built-in the Microsoft animation. I can't control it. Maybe the Microsoft will fix this issue later. I try to use the latest available UI framework.
