### ISSUE TITLE
Can this app support beats solo pro wireless?

### ISSUE THREAD

**Issue by ppfrog427** [steam3d/MagicPods-Windows#158]

**Comment by steam3d** [comment]
You should collect data about your headphones and describe what they can do like ear detection, show battery etc.
https://github.com/steam3d/MagicPods-Windows/issues/21

**Comment by ppfrog427** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/7768368/log.txt)
Thsi file is the log file of my Beats solo pro headphones, thanks for your efforts in this program developing.

**Comment by steam3d** [comment]
It should works. Check [capability](https://help.magicpods.app/fun-capability/).
