### ISSUE TITLE
MagicPods doesn't recognize my AirPods Max anymore...

### ISSUE THREAD

**Issue by cleanlock** [steam3d/MagicPods-Windows#159]
Hello,

now the MagicPods application doesn't recognize my AirPods Max anymore at all... it just looks like this now, even tho my AirPods Max are connected. Everything was working fine yesterday...

![image](https://user-images.githubusercontent.com/32986026/147226605-e76be6c6-c7dc-494b-a75f-2c6a48d57292.png)

**Comment by steam3d** [comment]
Hi. Have you tried restarting your computer?
Most likely the problem is not related to MagicPods, most likely your Bluetooth drivers were updated yesterday and therefore the application stopped working.
I have not released any updates.

**Comment by cleanlock** [comment]
I'll try that. My PC didn't install any driver updates yesterday, but "Apple, Inc. - USBDevice - 486.0.0.0" got installed.

**Comment by cleanlock** [comment]
Restart fixed it..
