### ISSUE TITLE
Tray Icon color that adjusts to theme

### ISSUE THREAD

**Issue by IyadhGm** [steam3d/MagicPods-Windows#16]
Is it possible to make the tray icon switches colors when the theme swiches from light to dark? I have Auto Dark Mode installed and when the theme turns dark, the tray icon does not switch to white like the others tray icons. So I was wondering if that could maybe be implemented? Thanks in advance! <3

**Comment by steam3d** [comment]
Hi. Yes it is possible. I will add it.

**Comment by steam3d** [comment]
Hi. Update app to 1.0.33.0.  Now icon will automatically switch color!
