### ISSUE TITLE
This app isn't connecting to my airpods pro

### ISSUE THREAD

**Issue by Sanaan01** [steam3d/MagicPods-Windows#160]
Hi, I have connected my Airpods pro to my pc via Bluetooth, everything works fine but when I use this app, its stuck on the infinite searching for Airpods, I have done the 3 methods but that didn't fix it. Can someone please help

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/7769482/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/7769483/MagicPodsUILog.txt)
.

**Comment by Sanaan01** [comment]
Heres i checked over the log files and it seems my pc doesnt support BLE but device manager shows i have the driver for ble.

![image](https://user-images.githubusercontent.com/81903566/147246998-23dbdde8-b15b-4b7b-b8cd-5c1482f13574.png)

**Comment by steam3d** [comment]
Hi. Bluetooth low energy does not works on your PC.  Did you try install the latest driver from manufactory site? If this does not help, try installing an older version of the driver
