### ISSUE TITLE
Update the magicpods.app website media and use the new MS Store preview badges

### ISSUE THREAD

**Issue by Void48** [steam3d/MagicPods-Windows#162]
https://developer.microsoft.com/en-us/microsoft-store/badges/

**Comment by steam3d** [comment]
Hi. The magicpods.app will be updated when i finish work with refresh the MagicPods UI. Thx for feedback.

**Comment by Void48** [comment]
> Hi. The magicpods.app will be updated when i finish work with refresh the MagicPods UI. Thx for feedback.

Thank you for all the work! <3
