### ISSUE TITLE
Cant find any device

### ISSUE THREAD

**Issue by mrtiger9x** [steam3d/MagicPods-Windows#163]
I have airpods 2, airpod 3 but cant connect anything

Log here:
29.12.2021 17:05:55 ----------------- ---- [Info]  |                | Start program
29.12.2021 17:05:55 ----------------- ---- [Info]  | WindowsVersion | Microsoft Windows NT 10.0.19042.0
29.12.2021 17:05:55 ----------------- ---- [Info]  | PackageVersion | 1.0.79.0 X64
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | search_by_rssi: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | log_lvl: Info
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | auto_connect: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | auto_switch_output: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | voice_over_allow_all_apps: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | volume_down_percent: 75
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | ear_detection: Pause
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | is_ble: True
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | voice_over: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | animation_style: FadeInCenter
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | search_min_rssi: -60
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | debug_mode: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | hide_tips: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | auto_switch_output_guid: 
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | recommended_packet_count: 0
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | battery_tray_icon: True
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | recommended_rssi: -180
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | hide_tray_icon: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | hide_welcome_screen: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | recommended_rssi_count: 0
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | animation_rssi: -65
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | battery_tray_icon_type: Digital
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | show_connect_btn: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | send_play: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | low_latency: False
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | voice_over_voice: 
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | search_max_rssi: 0
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | animation: True
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | animation_size: Small
29.12.2021 17:05:55 ----------------- ---- [Info]  |    Settings    | additional_media_players: True
29.12.2021 17:05:55 ----------------- ---- [Info]  |                | Run AirpodsState
29.12.2021 17:05:55 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:05:55 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Baseus Encok WM01 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-28:4b:b4:0d:f9:a4
29.12.2021 17:05:55 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:05:55 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Vịt's Airpod 2 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-48:46:c1:09:8b:b9
29.12.2021 17:05:55 20:06:09:20:85:1A ---- [Info]  |GetPairedDevices| Find Vịt’s AirPods Model airpods1 Disconnected
29.12.2021 17:05:55 A5:DC:18:33:B2:CD ---- [Info]  |GetPairedDevices| Find AirPods của Vịt #2 Model airpods3 Disconnected
29.12.2021 17:05:55 ----------------- ---- [Info]  |GetPairedDevices| programState Disconnected
29.12.2021 17:05:55 ----------------- ---- [Info]  |                | AirPods found
29.12.2021 17:05:55 ----------------- ---- [Info]  |                | Advertisement watcher started!
29.12.2021 17:06:04 ----------------- ---- [Error] |WaitActiveAudioS| Did not wait for the audio service activation {0.0.0.00000000}.{9b8edc7e-28bc-4bcc-9681-5325cdb756d2}
29.12.2021 17:06:04 A5:DC:18:33:B2:CD ---- [Info]  |ConnectionStatus| AirPods của Vịt #2 Connected (programState Searching)
29.12.2021 17:06:05 ----------------- ---- [Info]  |                | Connection to UWP lost
29.12.2021 17:06:43 A5:DC:18:33:B2:CD ---- [Info]  |ConnectionStatus| AirPods của Vịt #2 Disconnected (programState Disconnected)
29.12.2021 17:07:02 A5:DC:18:33:B2:CD ---- [Info]  |ConnectionStatus| AirPods Connected (programState Searching)
29.12.2021 17:08:22 A5:DC:18:33:B2:CD ---- [Info]  |ConnectionStatus| AirPods Disconnected (programState Disconnected)
29.12.2021 17:09:08 ----------------- ---- [Info]  |                | Dispose UWP Connection
29.12.2021 17:09:08 ----------------- ---- [Info]  |                | App closed. Code -1
29.12.2021 17:09:11 ----------------- ---- [Info]  |                | Start program
29.12.2021 17:09:11 ----------------- ---- [Info]  | WindowsVersion | Microsoft Windows NT 10.0.19042.0
29.12.2021 17:09:11 ----------------- ---- [Info]  | PackageVersion | 1.0.79.0 X64
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | search_by_rssi: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | log_lvl: Info
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | auto_connect: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | auto_switch_output: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | voice_over_allow_all_apps: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | volume_down_percent: 75
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | ear_detection: Pause
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | is_ble: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | voice_over: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | animation_style: FadeInCenter
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | search_min_rssi: -55
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | debug_mode: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | hide_tips: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | auto_switch_output_guid: {0.0.0.00000000}.{a5e9d260-3439-42ef-aad0-a0d7d466b062}
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | recommended_packet_count: 0
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | battery_tray_icon: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | recommended_rssi: -180
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | hide_tray_icon: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | hide_welcome_screen: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | recommended_rssi_count: 0
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | animation_rssi: -65
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | battery_tray_icon_type: Digital
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | show_connect_btn: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | send_play: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | low_latency: False
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | voice_over_voice: 
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | search_max_rssi: 0
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | animation: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | animation_size: Small
29.12.2021 17:09:11 ----------------- ---- [Info]  |    Settings    | additional_media_players: True
29.12.2021 17:09:11 ----------------- ---- [Info]  |                | Run AirpodsState
29.12.2021 17:09:11 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:09:11 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Baseus Encok WM01 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-28:4b:b4:0d:f9:a4
29.12.2021 17:09:11 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:09:11 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Vịt's Airpod 2 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-48:46:c1:09:8b:b9
29.12.2021 17:09:12 20:06:09:20:85:1A ---- [Info]  |GetPairedDevices| Find Vịt’s AirPods Model airpods1 Disconnected
29.12.2021 17:09:12 A5:DC:18:33:B2:CD ---- [Info]  |GetPairedDevices| Find AirPods Model airpods3 Disconnected
29.12.2021 17:09:12 ----------------- ---- [Info]  |GetPairedDevices| programState Disconnected
29.12.2021 17:09:12 ----------------- ---- [Info]  |                | AirPods found
29.12.2021 17:09:12 ----------------- ---- [Info]  |                | Advertisement watcher started!
29.12.2021 17:10:32 ----------------- ---- [Info]  |                | Connection to UWP lost
29.12.2021 17:13:07 ----------------- ---- [Info]  |                | Dispose UWP Connection
29.12.2021 17:13:07 ----------------- ---- [Info]  |                | App closed. Code -1
29.12.2021 17:15:11 ----------------- ---- [Info]  |                | Start program
29.12.2021 17:15:11 ----------------- ---- [Info]  | WindowsVersion | Microsoft Windows NT 10.0.19042.0
29.12.2021 17:15:11 ----------------- ---- [Info]  | PackageVersion | 1.0.79.0 X64
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | search_by_rssi: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | log_lvl: Info
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | auto_connect: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | auto_switch_output: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | voice_over_allow_all_apps: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | volume_down_percent: 75
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | ear_detection: Pause
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | is_ble: True
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | voice_over: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | animation_style: FadeInCenter
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | search_min_rssi: -60
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | debug_mode: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | hide_tips: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | auto_switch_output_guid: 
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | recommended_packet_count: 0
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | battery_tray_icon: True
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | recommended_rssi: -180
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | hide_tray_icon: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | hide_welcome_screen: True
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | recommended_rssi_count: 0
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | animation_rssi: -65
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | battery_tray_icon_type: Digital
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | show_connect_btn: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | send_play: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | low_latency: False
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | voice_over_voice: 
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | search_max_rssi: 0
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | animation: True
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | animation_size: Small
29.12.2021 17:15:11 ----------------- ---- [Info]  |    Settings    | additional_media_players: True
29.12.2021 17:15:15 ----------------- ---- [Info]  |                | Run AirpodsState
29.12.2021 17:15:16 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:15:16 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Baseus Encok WM01 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-28:4b:b4:0d:f9:a4
29.12.2021 17:15:16 ----------------- ---- [Error] |GetPairedDevices| The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
29.12.2021 17:15:16 ----------------- ---- [Error] |GetPairedDevices| Can't get BluetoothDevice from Vịt's Airpod 2 ID Bluetooth#Bluetooth00:1a:7d:da:71:11-48:46:c1:09:8b:b9
29.12.2021 17:15:16 20:06:09:20:85:1A ---- [Info]  |GetPairedDevices| Find Vịt’s AirPods Model airpods1 Disconnected
29.12.2021 17:15:16 ----------------- ---- [Info]  |GetPairedDevices| programState Disconnected
29.12.2021 17:15:16 ----------------- ---- [Info]  |                | AirPods found
29.12.2021 17:15:16 ----------------- ---- [Info]  |                | Advertisement watcher started!

**Comment by steam3d** [comment]
Hi. This is Bluetooth dongle issue.  The MagicPods cannot receive the necessary data, as an error occurs in the bluetooth dongle.
You can try to update the bluetooth driver.

**Comment by mrtiger9x** [comment]
how can i update the bluetooth driver,?8

**Comment by steam3d** [comment]
Go to manufacturer's website. Download the latest drivers from support page of your bluetooth module and install it. Do not forget to reboot your PC.
