### ISSUE TITLE
No 'airpods 3' in supported devices list

### ISSUE THREAD

**Issue by AnwarBou** [steam3d/MagicPods-Windows#167]
When you first open the app it tells you Airpods 1 - 2 are supported. Airpods 3 are nowhere to be found even tho they work perfectly fine. Add it to the list? :^)

**Comment by steam3d** [comment]
Hi. Thanks for pointing out the typo. I will fix it next update.

**Comment by steam3d** [comment]
I improved text. Over time, users will translate the new text.
