### ISSUE TITLE
Can support for Beats Fit Pro be added?

### ISSUE THREAD

**Issue by mkaltner** [steam3d/MagicPods-Windows#168]
They're essentially AirPods Pro's and android apps like AssistantTrigger kinda pick them up without official support.

**Comment by steam3d** [comment]
Hi. Collect Beats Fit Pro log data using [this](https://github.com/steam3d/MagicPods-Windows/issues/21) tool. 

In your case if Beats Fit Pro works as AirPods Pro:
1. Run the DeviceFinder
2. Open the case
3. Take out both headphones from case
4. Put in ear right
5. Put in ear left
6. Take out both headphones from ears 
7, Put headphones to the case and close it

It is best to make a short delay of 2 seconds, for example, after each action, to be sure that the program has time to write all the data

**Comment by mkaltner** [comment]
Heres's a couple log runs, let me know if you need me to run it again.
Mine are the black ones.

[log1.txt](https://github.com/steam3d/MagicPods-Windows/files/7829252/log1.txt)
[log2.txt](https://github.com/steam3d/MagicPods-Windows/files/7829253/log2.txt)

Thanks!

**Comment by steam3d** [comment]
Thx, Seems Beats fit Pro works like AirPods Pro or AirPods. I will add a task to add it.

**Comment by mkaltner** [comment]
Perfect, thank you.  Since you've added a task to implement, I'll chose this ticket.
