### ISSUE TITLE
MagicPods app not updating power supply levels

### ISSUE THREAD

**Issue by ScarletFoxy** [steam3d/MagicPods-Windows#169]
i have Airpod Pro - brand new they link with the app but my earbuds ( according to the windows bluetooth page ) have 30% charge but app says there at 100% even when they flatten out and shut off app says 100% charged and same with the charge case fully charged or dead empty it stuck showing 75% i paid the money for the app for this precise reason so id know my power levels - but its not working

**Comment by steam3d** [comment]
Hi. If Windows settings Bluetooth page shows battery info it means that you have fake AirPods Pro. The MagicPods supports only original AirPods from Apple.
