### ISSUE TITLE
Size/Font

### ISSUE THREAD

**Issue by IyadhGm** [steam3d/MagicPods-Windows#17]
Hi, I wish that the pop up would be like 1,5 bigger or something so that it is more noticeable and so that the font doesnt get too pixelated. [In my case](https://imgur.com/a/YU3AL9G), it looks pretty rough! I think if it was bigger the font wouldn't look like that! Thanks!

**Comment by steam3d** [comment]
Hi. Thx for feedback. I already done this.  It will available in next update.
