### ISSUE TITLE
Option to disable the Hands-Free device.

### ISSUE THREAD

**Issue by sckohen** [steam3d/MagicPods-Windows#172]
Hello,

I was wondering if anyone would be interested in an optional feature to disable the hands-free mode on AirPods?

I personally use my AirPods Pro's to listen to my computer's sounds, however, I have dedicated microphones that are better than those on the AirPods themselves. However, whenever I connect my AirPods, they are automatically set as the default communication devices.

Since Windows setting menus are very annoying to work with, it would be great if there was an option for the AirPods Hands-Free device to not connect at all, or at least to be disabled automatically.

**Comment by steam3d** [comment]
Hi. This is a known issue because the Windows do not have a native way to connect Bluetooth devices.  I found another way, but it was not stable. Sometime iPhone takes connection to itself. 
I tried to disable Hands-Free after connecting AirPods and the windows just disconnect AirPods i have no idea why.

**Comment by OdinBoat** [comment]
I have this same issue. when connecting to my AirPods I have two playback devices
, "hands-free AG Audio" and "AirPods stereo" 

when using my PC, "hands-free AG Audio" causes lower quality audio to play, however, this isn't the issue itself. simply disabling the playback device fixes these issues.

however, when connecting my AirPods (with the app running) this playback device is re-enabled. 

image added to show playback devices.

![airpods](https://user-images.githubusercontent.com/54726753/149859189-f034565c-ec89-47d3-a9a2-c7b4015f925d.PNG)

**Comment by ajayvarghese2000** [comment]
>however, when connecting my AirPods (with the app running) this playback device is re-enabled.

Yeah for some reason when connecting using the app the HFP is re-enabled. Would be nice to be able to permanently disable it via the app or stop the app from re-enabling it after disabling it using the windows settings.

**Comment by steam3d** [comment]
Update to 1.0.83.0. Now Bluetooth services will not turn on after connection.

**Comment by joemussa** [comment]
> Update to 1.0.83.0. Now Bluetooth services will not turn on after connection.

I wrote this on my issue page but I thought it would be best to put this on an open issue page.

The new feature works on my home desktop running Windows 10 version 21H1 but I'm also using the app on my work laptop running Windows 10 Enterprise version 1909 and it's not working.

![image](https://user-images.githubusercontent.com/19414262/159337193-45f9a93c-0012-4814-8cc1-555821dd2ce9.png)

**Comment by steam3d** [comment]
@joemussa 
It is impossible. Legacy connection is turned off by default. 

Make sure that you disable **Handsfree**:
https://help.magicpods.app/issue-connectivity/

When Handsfree is disabled, you will not see the headset device on your screenshot.

**Comment by OdinBoat** [comment]
> @joemussa It is impossible. Legacy connection is turned off by default.
> 
> Make sure that you disable **Handsfree**: https://help.magicpods.app/issue-connectivity/
> 
> When Handsfree is disabled, you will not see the headset device on your screenshot.

can confirm this works as of a few tests, no more "hands free" device showing up and so far the app does not enable said device

**Comment by steam3d** [comment]
Works as expected

**Comment by OdinBoat** [comment]
turned on computer, and when the airpods connected the "hands-free telephony" was re-enabled in the services tab in the airpods properties settings

is this the app re enabling or possibly another cause?

**Comment by steam3d** [comment]
I think another. The MagicPods search all enabled services for Bluetooth headphone and connects to enabled services.

I can’t reproduce this issue.
Can you tell more details?
