### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ProjektSHIN** [steam3d/MagicPods-Windows#173]
This app just doesn't seem to work. I have my Airpod Pro connected to my PC currently with Bluetooth via the settings on my computer.  Even then, the app still doesn't even register my Airpods. sucks because I instantly purchased the app thinking that the description would be very useful, and it would've if it worked.

**Comment by steam3d** [comment]
Hi. Do you have infinity search?
Open the MagicPods app -> Go to Support page -> open log files -> Upload files here

**Comment by juanfcopina** [comment]
Hello, none of the options that you propose to solve this Windows 11 problem does not work. Please try to fix it or refund the money paid for the purchase of the application.

**Comment by steam3d** [comment]
No feedback.
