### ISSUE TITLE
Can you please add support for Beats Studio 3 headphones ? 

### ISSUE THREAD

**Issue by TIasMat16** [steam3d/MagicPods-Windows#174]
Hello, since Beats headphones are in the apple's ecosystem, it would be great that you add it to the supported list !

**Comment by steam3d** [comment]
Hi. Can you provid [ log data](https://github.com/steam3d/MagicPods-Windows/issues/21) from Beats Studio 3?

**Comment by steam3d** [comment]
I added support on 1.0.81.0 version. Please update the MagicPods and leave feedback.

**Comment by TIasMat16** [comment]
Thank you so much!!! I really appreciate it, I will
definitely recommend this application to my friends and give it 5 stars!!!
