### ISSUE TITLE
[Feature Request] Disabling/Customizing low battery notifications 

### ISSUE THREAD

**Issue by DashCruft** [steam3d/MagicPods-Windows#176]
Hey thanks for your awesome work!

I was wondering if its possible to add a feature where you could disable it giving you a notification on a low battery. It would be great to also customize it maybe?

Thank you!

**Comment by steam3d** [comment]
Hi. You can disable notification from MagicPods for now. I will think about your request. Thx for feedback.

**Comment by DashCruft** [comment]
Of course. I will disable it through the windows settings for now until it gets included in the new update.

Thanks for your answer.
