### ISSUE TITLE
The taskbar icon is very low quality

### ISSUE THREAD

**Issue by aayushyap89** [steam3d/MagicPods-Windows#179]
The digital icon is very low quality but the battery is a bit better. Also please make a discord server, would be nice.

**Comment by steam3d** [comment]
Can you provide a screenshot? 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/30986874/151502732-39e10839-ab31-42e0-b0b3-49d53b145b47.png">

**Comment by steam3d** [comment]
No feedback
