### ISSUE TITLE
My questions and some functions to be improved

### ISSUE THREAD

**Issue by git102347501** [steam3d/MagicPods-Windows#18]
Wow, this software is exactly what I always want to do. Someone really started to do it. I'm so happy!

I have the following questions

1. When you develop this software, is there any copyright obstacle for apple?

2. I see that you are developing based on uwp. Are you interested in open source to let more people improve this software?

Functions urgently needed to be improved

1. Double click control is invalid. I think at least it can control iTunes music playing.

2. It doesn't seem to connect to the headset automatically. I need to connect my headset manually in Windows Bluetooth.

Other unimportant functions.

1. I think the animation is a little small. Can you customize the size? Is there an optional mask layer to display the animation?

I'm sorry, my English level is average. This is the question and answer of machine translation.

**Comment by steam3d** [comment]
2. I thought about it but for now there will be closed code

1. I can't control double click now. Still looking for solution.
2. Windows Bluetooth less documented compared to linux. I spend lots time to find some information how to use classic bluetooth on windows.  I also want this function to auto-connect to AirPods

1. Update to 1.0.28.0. I added different size to animation window.

**Comment by git102347501** [comment]
I have received it. Thank you for your reply
