### ISSUE TITLE
The info color is wrong.

### ISSUE THREAD

**Issue by aayushyap89** [steam3d/MagicPods-Windows#180]
All the other colors are light blue accent colors that use the windows 11 default color (the default not the one I set) is not the same as the info color set by the app.
![image](https://user-images.githubusercontent.com/77907390/151455864-6654e467-c92e-49af-afc0-0f852f4f50b4.png)

**Comment by steam3d** [comment]
Hi. What windows build do you use?

**Comment by steam3d** [comment]
No feedback
