### ISSUE TITLE
airpods wont connect

### ISSUE THREAD

**Issue by LennyDaBoss** [steam3d/MagicPods-Windows#181]
[New folder (3).zip](https://github.com/steam3d/MagicPods-Windows/files/7962767/New.folder.3.zip)

**Comment by LennyDaBoss** [comment]
i dont know if it means anything but every time I run an error report for Bluetooth it comes back with this 
![image](https://user-images.githubusercontent.com/86168593/151642931-6b94db21-ad9f-4dbb-9a22-ae586ea6c446.png)

**Comment by steam3d** [comment]
Hi. This is Bluetooth driver issue. The MagicPods try to use the Bluetooth and it goes down.
Try install another version Bluetooth drivers
