### ISSUE TITLE
[Feature Request] Auto disable the Hands-Free AG Audio Device

### ISSUE THREAD

**Issue by joemussa** [steam3d/MagicPods-Windows#182]
Love the program, but there's something that constantly irks me about Bluetooth headphones/headsets. I'm constantly having to manually disable the "Hands-Free AG Audio" in the Windows sound panel because applications like Discord, Teams, Zoom, etc. seem to default to the Default Communication Device, i.e. the Headset which has terrible audio and blows out my ears.

I would love it if the application had a setting where it would automatically disable the Hands-Free playback device and set the Default Communication Device to the headphones or just set the Default Communication Device to the headphones and leave the Hands-Free playback device alone.

I've tried other solutions like manually disabling the device or removing the driver within the device manager but every time my AirPods are reconnected, it will override any changes I make.

**Comment by joemussa** [comment]
Oh I'm an idiot and glanced over #172. You can close this.

**Comment by steam3d** [comment]
Update to 1.0.83.0. Now Bluetooth services will not turn on after connection.

**Comment by joemussa** [comment]
Works great on Windows 10 21H1
