### ISSUE TITLE
High CPU utilisation

### ISSUE THREAD

**Issue by bedrin** [steam3d/MagicPods-Windows#183]
I'm measuring amount of time my CPU spends in C0 state (using Throttlestop).

With idle system it's around 0.5% 
When I launch MagicPods it goes up to 2% which negatively affects battery.

**Comment by steam3d** [comment]
The main load is the processing of data from different Bluetooth devices. The more devices, the more CPU it consumes. I filter by maximum the list the amount of Bluetooth data being processed.

**Comment by bedrin** [comment]
Thanks for response. As a workaround maybe introduce (an advanced) switch which would disable BLE scanning if laptop is running on battery? For me personally it would work.

**Comment by bedrin** [comment]
Just realized there're already two issues on this topic. Linking for history:
https://github.com/steam3d/MagicPods-Windows/issues/152
https://github.com/steam3d/MagicPods-Windows/issues/140

**Comment by steam3d** [comment]
When BLE scanning is off the popup feature will not be available.  I can add an option to manually turn off BLE scanning but i use a notebook every day and the MagicPods takes about 1% percent of battery usage. Is it worth it?

**Comment by bedrin** [comment]
I would say ultra-low priority)

**Comment by steam3d** [comment]
Reduced CPU usage in new versions MagicPods
