### ISSUE TITLE
[Feature Request] Allow connecting via the full app window, not just the tray icon menu

### ISSUE THREAD

**Issue by stamminator** [steam3d/MagicPods-Windows#186]
Right-clicking the tray icon menu shows eligible bluetooth devices to connect.

![image](https://user-images.githubusercontent.com/10633170/154288851-197a5fdf-b44b-4107-9f72-6e9587ca72d4.png)

It would be nice if the same options were present in the full app window via a Connect button of some kind.

Side note: the tray icon Connect option is working great for me, but I've noticed it's present even when I set the<<Connect>> button experimental feature to off. Not a problem really, just thought I'd mention it.

**Comment by steam3d** [comment]
Hi. I plan to add, but it won't be soon. Now I am reworking the function of connecting headphones and changing the pop-up menu like in your screenshot

**Comment by steam3d** [comment]
Implemented. Update the MagicPods to 2.0.0.0
