### ISSUE TITLE
CONNECTION DROP

### ISSUE THREAD

**Issue by GHOST-ARYAN** [steam3d/MagicPods-Windows#19]
FREQUENT CONNECTION DROPS AFTER TURNING ON LOW AUDIO LATENCY ON DELL XPS. TRIED REINSATALLING WINDOWS ALSO AND ALL DRIVERS ARE ALSO UPTO DATE

**Comment by steam3d** [comment]
Hi. Can you explain what is happen? Which connection is drop?

**Comment by steam3d** [comment]
No feedback.
