### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by alikorkmazz** [steam3d/MagicPods-Windows#192]
Hello, I can't connect my AirPods 2 in any way. I am using Windows 11 operating system. I made all the settings. Could you help 
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/8315674/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/8315675/MagicPodsUILog.txt)
?

**Comment by alikorkmazz** [comment]
I also updated the Bluetooth version.

**Comment by steam3d** [comment]
Hi. Looks like there is the Bluetooth driver issue. The MagicPods does not receive any data from Bluetooth module. 

You can try to install the older driver and try again.

Also try to rapier the MagicPods (Right click on MagicPods tile in start menu -> App settings -> Rapier)

**Comment by alikorkmazz** [comment]
Unfortunately. I tried all of them but it didn't work. Do you have any other suggestion?

**Comment by alikorkmazz** [comment]
![image](https://user-images.githubusercontent.com/11902753/159429967-ec6d2cd1-da13-414d-a6ff-f0b4ad3af113.png)

Normally, the battery percentage is also displayed in the bluetooth settings of windows. But it does not connect to the MagicPods application in any way. I paid for the app for nothing, unfortunately.

**Comment by steam3d** [comment]
Hi. Which windows version do you use? I do not see battery level on windows settings Bluetooth  tab.

**Comment by steam3d** [comment]
From my side I can’t access to Bluetooth directly, but as I can see Microsoft can. 

I can’t resolve this issue, because the MagicPods just ask Bluetooth data from Windows.  Most likely some settings are blocking the application.

Do you allow background process?

**Comment by alikorkmazz** [comment]
How do I allow background processing? Do I need to make any extra settings?

**Comment by steam3d** [comment]
Go to settings and search "Background"
![image](https://user-images.githubusercontent.com/30986874/159440067-b72a41cc-55bf-4971-b29c-b67900eaa4ba.png)

I tested on 4 different machine with different Windows and settings right now, there are no any issues. 
I also did not find the way to enable display battery percentage as you showed on screenshoot.

**Comment by steam3d** [comment]
One more question, do you have original AirPods? Because the MagicPods can works only with original Apple.

**Comment by steam3d** [comment]
No feedback
