### ISSUE TITLE
Airpods Max not detected while connected via wire

### ISSUE THREAD

**Issue by TheRacc2** [steam3d/MagicPods-Windows#194]
I use the APM as my daily headphones, but always use the lightning->3.5mm connector from apple. This does NOT charge the headphones so I’d like to monitor my battery. MagicPods does not seem to detect my APM when connected via wire, but works flawlessly with wireless.

**Comment by steam3d** [comment]
Hi. The MagicPods does not support AirPods Max by wire. Unfortunately, i can't buy the wire. It is not sold in my country.
