### ISSUE TITLE
[Feature Request] Setting to disable auto-pause upon disconnect

### ISSUE THREAD

**Issue by amdziuk** [steam3d/MagicPods-Windows#195]
It would be great if the Settings menu allowed you to disable the auto-pause feature.

Use case: I often want the media to continue playing on my PC when I switch my AirPods to my iPhone.

**Comment by steam3d** [comment]
Hi. Okay, it will be added.

**Comment by steam3d** [comment]
Implemented. Update the MagicPods to 2.0.0.0
