### ISSUE TITLE
Random Connectivity

### ISSUE THREAD

**Issue by MonstrumHD** [steam3d/MagicPods-Windows#196]
While using magicpods I encountered a very annoying bug, this bug forces the airpods to connect randomly every 15 minutes thus pausing my music/video and disconnecting my headset.

**Comment by steam3d** [comment]
Hi. There is only one option that can only connect (not disconnect) - "Auto-connect". I this function is turned off then some other application is causing this problem.  You can also attach the log files to check how the MagicPods works.
