### ISSUE TITLE
App no longer detects airpods

### ISSUE THREAD

**Issue by kurtchief** [steam3d/MagicPods-Windows#197]
This may be due to a recent intel bluetooth driver update but not sure.  The app no longer detect my airpods when I open the case.  After I manually connect to them in my computer's bluetooth settings and open MagicPods the app flips back and forth continuously between "Searching Airpods" and "Airpods disconnected" screen.  I have tried removing/ reinstalling your application as well without success.

**Comment by kurtchief** [comment]
Windows 11 as well in case that matters

**Comment by kurtchief** [comment]
I also completely unpaired and repaired my airpods to my machine but the software still has the same issue

**Comment by steam3d** [comment]
Hi. Looks like it is Bluetooth driver issue. You can try to manually install the latest one.

**Comment by steam3d** [comment]
No feedback
