### ISSUE TITLE
The Icon Tray don't display the battery level

### ISSUE THREAD

**Issue by juniorfontana** [steam3d/MagicPods-Windows#20]
I just bought the app and I'm having problems with the icon tray battery level. For me it only show one blank icon.

![erro](https://user-images.githubusercontent.com/67166205/85169924-ff5b9880-b242-11ea-8d56-2d3966b79f3c.png)

**Comment by steam3d** [comment]
Everything is working. You have half of full battery.
![image](https://user-images.githubusercontent.com/30986874/85229308-96fee980-b3f1-11ea-8148-c59d00ed2b5b.png)
