### ISSUE TITLE
[Issue] MagicPods no longer working with brand new intel driver

### ISSUE THREAD

**Issue by l0lGhostlxl** [steam3d/MagicPods-Windows#204]
I just updated my Bluetooth drivers and magic pods no longer works. When opening up the AirPods, the app tray icon and the actual app will start looping between searching and disconnected until the AirPods are closed. Furthermore, if you connect the AirPods manually whilst the app is running it will start pausing any video constantly, and it will not register on the app, and the app will crash after 20 seconds. Another discrepancy is that upon right-clicking the app tray icon there is no button to connect to my AirPods, moreover, I also have tried resetting the AirPods and restarting my computer with no improvement.

My current bluetooth driver is 22.130.0.2 and I am using the Intel® Wi-Fi 6E AX210 160MHz wireless adapter

Thank you for your time.

**Comment by steam3d** [comment]
Hi. Did you try to rollback driver?
In this case i can do nothing, because it is Bluetooth Driver issue. The tray icon will work when the driver issue is resolved.

**Comment by l0lGhostlxl** [comment]
The airpods and bluetooth are working just fine but it's only the app i'm having trouble with but I'll see if I rolling back will fix my issue.

**Comment by l0lGhostlxl** [comment]
I just rolled back and it works just fine, so I think it might be a compatibility issue with the driver if it doesn't work when I update.

**Comment by l0lGhostlxl** [comment]
Alright just updated back from the old driver and the behaviour is the same.

**Comment by l0lGhostlxl** [comment]
Nevermind, seems to be working now. Thank you for the support.
