### ISSUE TITLE
Auto-Connect when the Computer Starts

### ISSUE THREAD

**Issue by AllForLandlord** [steam3d/MagicPods-Windows#205]
When I put my airpods 2nd generation in my ears first and they are connected to my iPad. Then I open the computer which has configured to make magicpods auto start when the computer starts. And then the computer will take the airpods connection from my iPad.
I have kept the "autopair" feature in magicpods closed and I even toggle it to open and then reclosed it. But that didn't fix it.
I have also found out that when my airpods slept in the charge case before the computer started, and I waited until magicpods run successfully on my computer. Then I took the airpods out of the charging case and the computer did not autopair it like it did when the airpods were in my ears.
I turned off the auto start of magicpods but when the computer restarts, it still take the connection from iPad.
So I think this problem might have something to do with windows 10, whcih is the compyter's system I'm using. But do  you have any fix to that? Thanks!

**Comment by steam3d** [comment]
Hi. This is default behavior of Windows. When the Windows turn on the Bluetooth (when pc starts the Bluetooth also turn on) it tries to connect to each paired Bluetooth device that you have. I tried to figure out how to fix this, but i think there is no way to change it.
