### ISSUE TITLE
Incorrect text apperance in context menu

### ISSUE THREAD

**Issue by kenny273** [steam3d/MagicPods-Windows#207]
According to weblate's translation, "Connect" should appear as “连接” under Simplified Chinese, but it doesn't appear correctly.
![QQ图片20220514115314](https://user-images.githubusercontent.com/93571028/168409851-fa1aa43e-4b66-4c9f-ba05-aa9b4e28149f.png)

**Comment by steam3d** [comment]
Hi. I don’t update the translation yet. I will think. Maybe I will release the update without new features just update translations.

**Comment by steam3d** [comment]
Update to 1.0.84.0. I updated translations.
