### ISSUE TITLE
Cant terminate the app by the button provide in app

### ISSUE THREAD

**Issue by MatrixLau** [steam3d/MagicPods-Windows#209]
When the choice 'hidden icon' is on, I cant terminate the app by the button provide in app

**Comment by steam3d** [comment]
Hi. There is known issue when the MagicPods hangs on closing. I can't find the reason. 
You must terminate the app
https://help.magicpods.app/issue-airpods-status-not-updating/

**Comment by MatrixLau** [comment]
Maybe there is an another way to terminate the app via a button ?

**Comment by steam3d** [comment]
You can make .bat file and pin it to start menu.
I am sorry for this issue, i still try to find solution.
