### ISSUE TITLE
Low audio latency not working 

### ISSUE THREAD

**Issue by pablorodriguezzurro** [steam3d/MagicPods-Windows#211]
As the title says, The low audio latency doesn't work. I tried to reset the AirPods and reinstall MagicPods and Bluetooth Drivers with no changes.
[TempState.zip](https://github.com/steam3d/MagicPods-Windows/files/8727445/TempState.zip)

**Comment by steam3d** [comment]
Hi. Low audio latency prevents an AirPods goes to sleep mode. Many Bluetooth modules have a big delay when they switch the sleep mode to normal one on AirPods.

I did not find any issue depended from Low Audio Latency. 

But you have a lot of other issues. The MagicPods can’t find audio devices and detect your primary monitor resolution. 

Did you sure the your windows system doesn’t damage?

**Comment by pablorodriguezzurro** [comment]
Hi! Thanks for the fast response. 

It only happens on my work PC (the debug data is from this PC). I have tried it also on my home desktop PC, and it works fine. 

I'm not sure if Windows on this PC is damaged. I use the Airpods as the only audio device and have the latest Bluetooth drivers installed. 

I will try to reconnect the screens and reinstall MagicPods again and see if that solves the error.

**Comment by pablorodriguezzurro** [comment]
I have solved it by installing the latest Bluetooth drivers of my bios and unchecking Allow the computer to turn off this device to save power option in Power Management tab.

**Comment by steam3d** [comment]
Can you describe what you exact from MagicPods? The log says that the last 2-3 times running the app is good. Everything works as expected.
Did you want to close the MagicPods after disconnecting or what?

**Comment by pablorodriguezzurro** [comment]
The error appears when Airpods are disconnected and the app is left open. 

The next time the Airpods are connected, the low latency mode doesn't work. 

To solve it, each time I connect them again, I have to restart the app through the terminal command. If I close it through the exit app button, the latency mode is not applied when the app is open. 

I was using the app as intended. When I would have wanted to use the Airpods on the PC, I pressed the connect button. The app was always open.

I hope this info helps you.

**Comment by steam3d** [comment]
Some modern Bluetooth drivers already fixed it, so if there is no difference between on and off Low Audio Latency then keep this feature off
