### ISSUE TITLE
Beats Studio Buds Support

### ISSUE THREAD

**Issue by Palm1ye** [steam3d/MagicPods-Windows#214]
Can you add "Beats Studio Buds" support?

**Comment by Ayemnatokey** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/8737075/log.txt)
And there is the log file.

**Comment by steam3d** [comment]
Hi. Can you please run the [DeviceFinder](https://github.com/steam3d/MagicPods-Windows/files/4911413/DeviceFinder_1.zip) before connecting Beats Studio Buds. 
1. Run the DeviceFinder
2. Connect Beats Studio Buds
3. Try listen to music 
4. Put both headphone to case and close it
5. Send the log file here

I will check if it possible

**Comment by Ayemnatokey** [comment]
Sure, here it is
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/8737616/log.txt)
.

**Comment by Ayemnatokey** [comment]
Sorry, i don't want to bother. Is there any updates about this?

**Comment by steam3d** [comment]
Hi. I added a task.  I will write when i will start the task.  I work on large update right now.

**Comment by kasik96** [comment]
Hey. Just added my log for Beats Studio Buds: 

[log.txt](https://github.com/steam3d/MagicPods-Windows/files/8946262/log.txt)

**Comment by steam3d** [comment]
@Ayemnatokey Which headphone color do you have?

**Comment by Ayemnatokey** [comment]
@steam3d I have the black one

**Comment by steam3d** [comment]
Can someone repeat the following steps?

1. Put two headphone to case
2. Run the DeviceFinder
3. Open the headphone's case and wait 10 sec
4. Take out the left headphone from the case and wait 5 sec
5. Take out the right headphone from the case and wait 5 sec
6. Put two headphone to the opened case and wait 10 sec
7. Close the case

Upload the log file here.

Does Beats Studio Buds show animation when case open near iPhone?
If yes, can you screen record of animation about 15 sec?

I added headphones. Now i will wait additional info from your. After it i will prepare the update to the Microsoft Store
![image](https://user-images.githubusercontent.com/30986874/177294377-273dec20-9951-491e-a2b1-62c46249f00c.png)

**Comment by Ayemnatokey** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/9046848/log.txt)
here the log file and

https://user-images.githubusercontent.com/64729369/177343346-ce7ee490-f227-4fad-90a5-1d6221a27070.MOV

here is the video

**Comment by steam3d** [comment]
@kasik96 can you record video too?

@Ayemnatokey  Thanks. I think the popup animation should works.  I return if i will have a questions.

**Comment by kasik96** [comment]
> @kasik96 can you record video too?
> 
> @Ayemnatokey Thanks. I think the popup animation should works. I return if i will have a questions.

Yeah, here it is :)

[log.txt](https://github.com/steam3d/MagicPods-Windows/files/9054516/log.txt)


https://user-images.githubusercontent.com/7235992/177546091-f187a819-19ed-412f-b0a8-fe5f8f93f3f7.mp4

**Comment by steam3d** [comment]
I released the update 2.0.3.0 with support Beats Studio Pro. I enabled the Popup animation (i am not sure that it will work right). The animation must appear only when you open the case with headphones inside or when you open the empty case and put 
inside two headphones.

About color. The MagicPods update information about the color after first connection. If you connected your Beats and the MagicPods shows it in black instead gray just refresh the page. (Go to any page for example support and go back to headphones it will update the UI)

Anyway leave feedback about popup window.  I think it maximum that i can make for this headphones for now.

**Comment by Ayemnatokey** [comment]
I checked the update and everything works well i guess, I can't find any difference between "low latency mode" on and off but i guess it's because the missing H1 Chip. 

Also the pop up animation working perfectly well.
![image](https://user-images.githubusercontent.com/64729369/178022275-ef5df73c-0eca-4b72-998e-fcae9f3e6e82.png)

**Comment by steam3d** [comment]
"low latency mode" helps only on certain PC. Windows updated Bluetooth audio and many PC no more need this option. 

Yep, you are right. I will update the wiki page soon.

**Comment by Ayemnatokey** [comment]
I think you forget to add "AirPods Supported" on there: https://github.com/steam3d/MagicPods-Windows/blob/master/README.md
