### ISSUE TITLE
Charge status on ibuds case battery

### ISSUE THREAD

**Issue by b10tds** [steam3d/MagicPods-Windows#216]
The iPods Pro case charge status indicator only displays the lightning bolt while the case displays the charge led. With the iPods Pro case connected to charge lead and charging, opening the case and connecting to MagicPods the charge status does not update correctly either.

**Comment by steam3d** [comment]
Hi. The MagicPods does not support iPods Pro. Only original Apple or Beats headphones supported.

**Comment by steam3d** [comment]
No feedback
