### ISSUE TITLE
Internal Server While Adding New Language Support in MagicPodsUI

### ISSUE THREAD

**Issue by faysalmehmood** [steam3d/MagicPods-Windows#218]
Getting below while choosing to add translations for the Urdu language. Not sure if logs can be found somewhere for investigation.

![image](https://user-images.githubusercontent.com/14193531/174104738-2975a72e-6fae-478e-aeb5-1e7add6fb310.png)

**Comment by steam3d** [comment]
I checked everything looks fine. I any way rebooted and updated the server.
