### ISSUE TITLE
Airpods 3 work fine but all magicpods says is couldn't find airpods

### ISSUE THREAD

**Issue by AznCheese** [steam3d/MagicPods-Windows#219]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/107897256/174694771-11549527-30ba-4d0b-9fc5-f07bf122a92e.png">

**Comment by steam3d** [comment]
Hi. Did you try to update a Bluetooth driver?

**Comment by AznCheese** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/107897256/174905430-f1ea2095-8b72-4ec0-a5de-fddf46645658.png">
im pretty sure i have

**Comment by AznCheese** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/107897256/174906466-49d76263-ece8-4e51-979f-30a299dc3196.png">

**Comment by steam3d** [comment]
Upload the log files. You can found them on Support page

**Comment by AznCheese** [comment]
what do you mean by upload the log files?

**Comment by steam3d** [comment]
Open MagicPods and go to "Support" page then click to "Debug log". Upload files here

**Comment by AznCheese** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9154940/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9154941/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
The log files is empty. You launched the application 1 time and that's it. Did you use the app?

**Comment by AznCheese** [comment]
ive opened the app multiple times.
its in my taskbar
<img width="265" alt="image" src="https://user-images.githubusercontent.com/107897256/181598249-13d104ea-d845-4c89-aa43-84127622abe7.png">

**Comment by steam3d** [comment]
When you run the MagicPods you must see the icon in system tray.
![image](https://user-images.githubusercontent.com/30986874/181598959-b1a9ccb3-2220-4b63-9f84-fd2775dba5b5.png)

You need also upload the fresh log files.  Because as i can said above the log files is empty.

**Comment by AznCheese** [comment]
how do i lupload fresh log files?

**Comment by steam3d** [comment]
Just drag and drop here 
https://help.magicpods.app/report-issue/
