### ISSUE TITLE
AirPods Pro noise cancelling switch

### ISSUE THREAD

**Issue by leckhsu** [steam3d/MagicPods-Windows#22]
Hi,
When will MagicPods support Noise Cancelling switch for AirPods Pro? Thank you!

**Comment by steam3d** [comment]
Hi. For now it is impossible. i will continue looking for solution. Thx for feedback.

**Comment by masterged** [comment]
> Hi,
> When will MagicPods support Noise Cancelling switch for AirPods Pro? Thank you!

Hi, just switch by tap on headphone.

**Comment by steam3d** [comment]
https://github.com/steam3d/MagicPods-Windows/issues/97

**Comment by steam3d** [comment]
Implemented on MagicPods 2.0.72.0. [MagicAAP driver required](https://help.magicpods.app/fun-magicaap/)
To discuss, join [MagicPods Discord](https://discord.com/invite/UyY4PY768V)
