### ISSUE TITLE
How to set the double tap to switch to the next song

### ISSUE THREAD

**Issue by 3026187875** [steam3d/MagicPods-Windows#220]
I need this feature！
please.
thank you

**Comment by steam3d** [comment]
Hi. It is not possible on Windows

**Comment by EwanGreen4** [comment]
Would it not be a similar implementation to ear detection?

**Comment by steam3d** [comment]
@EwanGreen4 Hi. No it is not the same. Windows does not provide access to low-layers of Bluetooth stack. So I can’t get pressing keys data from headphones.
