### ISSUE TITLE
AirPods bug out when using one single AirPod for a while and trying to connect the other one again

### ISSUE THREAD

**Issue by H4lfShark** [steam3d/MagicPods-Windows#221]
I can't listen with my left AirPod because of this and it's getting extremely annoying,

**Comment by steam3d** [comment]
What is problem? Your second AirPod can't connect?

**Comment by H4lfShark** [comment]
> What is problem? Your second AirPod can't connect?

Yes, it just simply won't connect and I cannot hear anything. I uninstalled the app and I won't use it anymore so I'll just close this. Thanks!
