### ISSUE TITLE
Turning off "Automatic Pause" doesn't affect anything

### ISSUE THREAD

**Issue by v0s** [steam3d/MagicPods-Windows#223]
When turning off "Automatic Pause", the app still behaves as if it's turned on. 

![image](https://user-images.githubusercontent.com/3237013/176795013-98c7a69c-2e6f-4533-8f48-94274dc3a20e.png)

I.e., stops playback when disconnecting airpods or when locking desktop. 

MagicPods v2.0.0.0

**Comment by steam3d** [comment]
I uploaded the hot fix to Microsoft Store. It will be available after Microsoft team accept it (About 1-5 days).
