### ISSUE TITLE
High CPU usage in background (when no airpods connected)

### ISSUE THREAD

**Issue by Mattims** [steam3d/MagicPods-Windows#226]
<img width="301" alt="Screenshot 2022-07-07 112728" src="https://user-images.githubusercontent.com/31645594/177684446-048d5c2b-b628-40be-90b4-e301faea8f84.png">

Magicpods is using around 10% CPU Constantly when its running with no airpods connected.

**Comment by steam3d** [comment]
I optimized the MagicPods it should take less CPU now.
