### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by LUJUNZE** [steam3d/MagicPods-Windows#228]
Inaccurate display of left and right battery power

**Comment by steam3d** [comment]
Hi. Does anyone around you use the AirPods?

**Comment by homieHolmes** [comment]
Hi, I also have this problem. Yes, there's another AirPods in my house.

**Comment by homieHolmes** [comment]
Lowering the search radius can't help with the problem?

**Comment by steam3d** [comment]
@homieHolmes No, but the Fast search must turned off.  I will let you know if I can figure out, but Apple does everything for keep your privacy and it also makes trouble for developers
