### ISSUE TITLE
Can't Buy Outside MS Store - Corp. Policy Restriction

### ISSUE THREAD

**Issue by chaos-codifier** [steam3d/MagicPods-Windows#229]
REQUEST: 
Is there a way around this? 

BACKGROUND:
Hello, I have this App on my Home PC (purchase via Store), but my Work PC doesn't allow multiple MS profiles and their corp. MS profile forbids any direct Store purchases.
I suspect I am not the only one with this *payment* challenge.

**Comment by steam3d** [comment]
Hi. There is no other way to get the MagicPods. The app available only on Microsoft Store

**Comment by master9559** [comment]
Could I buy this on a personal account and try to transfer it over to a work computer?

**Comment by steam3d** [comment]
Available by request on [MagicPods Discord](https://discord.com/invite/UyY4PY768V)
