### ISSUE TITLE
Infinite search

### ISSUE THREAD

**Issue by vasconcego21** [steam3d/MagicPods-Windows#234]
Hello, I'm having a problem using MagicPods on my AirPods Pro. On iOS it recognizes it normally, but in the app, it connects but is in infinite search. Below is the debuglog along with the print
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9331503/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9331504/MagicPodsServiceLog.txt)
![image](https://user-images.githubusercontent.com/68581590/184495933-f1dfeea0-a7b2-4dbf-9442-bedc334a5e12.png)
![image](https://user-images.githubusercontent.com/68581590/184495945-297a5197-a99b-42b1-b2b7-27ca20db9304.png)

**Comment by steam3d** [comment]
Hi. This is windows or bluetooth issue. You can try to update the bluetooth driver or downgrage. The MagicPods does not receive any data from Windows. So from my side i cannot do anything.

**Comment by vasconcego21** [comment]
There's no chance it's due to W11 right?

**Comment by steam3d** [comment]
I do not know the real reason. I have a lot of users who had the same problem and there is not any clue to understand what's wrong.  It does not depend on windows version. Usually, users just update their Bluetooth drivers and after it everything fine.

One user also did not resolve this issue and after couple months he wrote to me that he reinstalled windows and everything works now.

I have ten machine to test the MagicPods and i never got this issue.
