### ISSUE TITLE
Request for setting for magicpod to be minimized during startup

### ISSUE THREAD

**Issue by nelsontyc** [steam3d/MagicPods-Windows#235]
Hi! Hoping that you can make a setting for magicpods to be minimized during startup. Currently when i open the app, the window is always opened by default.

**Comment by steam3d** [comment]
Hi. You can enable "startup" option and MagicPods will run at windows start.

**Comment by nelsontyc** [comment]
Hi! Thanks for the reply. I meant that when I open the Magicpods application, it will automatically minimize into the system tray. Great job on the app!!

**Comment by steam3d** [comment]
For many users it is unexpected behavior.  The MagicPods was designed to use it as background service that automatically start at windows runs, so there is no need to manual open the app.  I tried to optimize the app and it uses about 1% battery of my laptop.

**Comment by nelsontyc** [comment]
Will it be possible for me to propose a feature request to add this setting into the "preferences" of the app? So that those who manually open the app can have it minimized during opening of the app, if the "Magicpod will open minimized by default" toggle is turned on. Thanks so much once again!
