### ISSUE TITLE
Can you support Huaqiangbei earphones?

### ISSUE THREAD

**Issue by kot4ri** [steam3d/MagicPods-Windows#236]
I have many airplads pro, some of which are imitations of China Huaqiangbei. It can be correctly recognized by magicpods, but it cannot pop up windows and get battery level. These earphones can be normally recognized and used on Apple phones, but as far as I know, the pop-up protocol of these products is different from that of apple. I hope magicpods can correctly recognize these earphones. Thank you!

The following are two Android apps of Huaqiangbei products. I hope they are helpful to you.

Flycc http://www.198509.xyz/
Caishen's Earphone https://a.app.qq.com/o/simple.jsp?pkgname=com.luozong.caishen

**Comment by steam3d** [comment]
Hi. What the name of this headphones? Can i buy it on Aliexpress?

I will check but i want to say that it may took lot of time. Because Windows has a lot of Bluetooth limitation and it is complicate to figure out how it works.

Some of users said about very good replica of AirPods pro. It works on Airoha chip. Does your AirPods too?

**Comment by kot4ri** [comment]
I have almost all chip versions of imitation earphones. After my test, I recommend Airoha 1562AE and BES2500YP.
I tried to find it in aliexpress, but I couldn't find it.
I can give you the shopping link of China Taobao, and maybe it can be shipped overseas.

悦虎三代洛达1562AE
https://detail.tmall.com/item.htm?spm=a230r.1.14.11.19ea4cb1q2u9vV&id=677860380863&ns=1&abbucket=3&skuId=4865756996158

红蜂pro恒玄2500YP
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.40f32e8ddEfWkF&id=668639868344&_u=e3r5h8fce91c

You can understand their subtle differences in my blog posts.
Thank you for your reply.

**Comment by kot4ri** [comment]
Thank you for your efforts.

 I have updated to the latest version today, and the headphones equipped with the 1562AE chip are now working properly.

But it seems that there is no complete Simplified Chinese translation. I tried to view the string on Weblate, but the progress of Simplified Chinese translation is 100%. Will the latest translation be included in the next version?

**Comment by steam3d** [comment]
@kot4ri All languages will be updated when next update will be ready. All new features come with English only language then after a while users translate the MagicPods and I include new transation in MagicPods.
