### ISSUE TITLE
The ear detection feature for play/pause is unresponsive

### ISSUE THREAD

**Issue by BumpySnail23** [steam3d/MagicPods-Windows#237]
I have an AirPods Pro and the ear detection feature is a bit buggy. It works sometimes and then suddenly decides to stop for some time. There is also a bit of latency when it seems to work which is also not very consistent. Sometimes it works like a charm while other times it takes a whole 5 seconds before it registers it. Even though this might not be a huge issue, I believe that it is a very useful feature which if refined and made a bit more consistent, would tremendously improve the user experience.

Thanks a lot

**Comment by steam3d** [comment]
Hi. You can enable fast search it can help, but people who use AirPods around you will make trouble to you. I have idea how to improve this feature.

**Comment by steam3d** [comment]
Implemented on MagicPods 2.0.72.0. [MagicAAP driver required](https://help.magicpods.app/fun-magicaap/)
To discuss, join [MagicPods Discord](https://discord.com/invite/UyY4PY768V)
