### ISSUE TITLE
Can I manually add other brands of bluetooth headphones?

### ISSUE THREAD

**Issue by yorklai** [steam3d/MagicPods-Windows#238]
I hope to add a function to manually add the paired bluetooth headset to the list, so that the connection can be quickly started, thank you

**Comment by steam3d** [comment]
Hi. I started to work on it. But it is very complicate feature. It took a lot of time.

**Comment by crawfishie** [comment]
Would love for my Bose QC EarBuds II to show up in MagicPods. Merely showing the battery level in the system tray would be very welcome.

**Comment by steam3d** [comment]
MagicPods can take battery level from Windows Bluetooth Settings page. Update to 2.0.72.0
