### ISSUE TITLE
airpods pro connected but its saying couldn't find airpods.the battery status is also not visible

### ISSUE THREAD

**Issue by crushercoder** [steam3d/MagicPods-Windows#245]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9528581/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9528582/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
https://github.com/steam3d/MagicPods-Windows/issues/243

The Windows does not provide Bluetooth information. Update Bluetooth driver manually. (Go to Bluetooth manufacture site, download the newest Bluetooth driver and install it).

Note. The fake AirPods is not supported.

**Comment by crushercoder** [comment]
tried updating to the latest Bluetooth driver still the same issue.

**Comment by steam3d** [comment]
Everything works as expected from my side. If you have the original AirPods Pro than the only one thing left -  the Bluetooth adapter does not support BLE. I'd love to help, but I don't have direct Bluetooth access.

**Comment by crushercoder** [comment]
there is a driver named Microsoft Bluetooth LE Enumerator on my device.so I think it support BLE and i got my airpods pro as gift not 100% sure if they are original.
