### ISSUE TITLE
Ear detection doesn't work for both Airpods Max and Airpods Pro

### ISSUE THREAD

**Issue by muxuuu** [steam3d/MagicPods-Windows#249]
![image](https://user-images.githubusercontent.com/51448688/193206257-f4ce5597-96ba-40d6-9516-c9f595113c1e.png)
![image](https://user-images.githubusercontent.com/51448688/193206330-024ec4f8-bd41-4dba-a6a6-488c9f6e05a6.png)

**Comment by steam3d** [comment]
Hi. Do you try to use other player?

**Comment by muxuuu** [comment]
I tried different players, like edge,
![image](https://user-images.githubusercontent.com/51448688/193262004-42cc50e0-f164-4249-90b9-14555ca70e52.png)
but it didn't work. the pause button's play/pause works fine and the ear detection just  do nothing

**Comment by steam3d** [comment]
What Windows Build do you use?
What firmware version  do AirPods has?
Can you upload the log files from support page?

I tested the whole day and can't reproduce issue.

**Comment by muxuuu** [comment]
22623.730 beta channel
I don't know my AirPods firmware version because i don't have an Iphone.
I think it's not a firmware problem because it used to work fine on my airpods pro but now it doesn't work on both airpods.

**Comment by muxuuu** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9684100/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Ear detection is set to none the log file said.  You can try to reset settings to default. 
![image](https://user-images.githubusercontent.com/30986874/193270148-c37dd4fc-223a-47e9-b8cf-4fdd374799ac.png)

**Comment by muxuuu** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9684212/MagicPodsServiceLog.txt)
tried reset, still didn't work. QAQ

**Comment by steam3d** [comment]
I do not see that you tried to reset settings of MagicPods.  2 headphones were connected last time, so when 2 headphones connected at the same time all the Features will turn off.

Do you use two models headphones at the same time?

**Comment by muxuuu** [comment]
I did reset the settings but don't know why there's no log.
I tried connect Airpods pro only, Airpods Max only ,and connect both the same time ,and all of these just the same result.

**Comment by steam3d** [comment]
I can't detect anything because most of the time you had both model headphones connected. Try reinstall the MagicPods maybe Windows clear something.  AirPods Max is disconnected only when it inside their case.

**Comment by muxuuu** [comment]
Tried reinstall, :( still the same ):
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9684448/MagicPodsServiceLog.txt)
forget this, maybe it's the OS version problem, It's nothing serious without the feature. Thanks again.

**Comment by muxuuu** [comment]
I don't have an Iphone, If you can try turn off ear detection on Iphone and connect to windows again, see what will happen :)

**Comment by steam3d** [comment]
No feedback
