### ISSUE TITLE
Incorrect Battery Percentage

### ISSUE THREAD

**Issue by adepew** [steam3d/MagicPods-Windows#25]
When viewing the battery percentage on Windows my case is showing 90% charged. When viewing on my iPhone the case is showing 99% charged.

**Comment by steam3d** [comment]
It is right. I can only get battery level in 10% increments. It is mean that when battery is 99% you see 90%. I can't found better way know to get battery level now.

**Comment by adepew** [comment]
Thanks! Appreciate the quick response!
