### ISSUE TITLE
Recently started- delay in resuming playback, audio stutters and so on

### ISSUE THREAD

**Issue by okumam** [steam3d/MagicPods-Windows#251]
Has there been an update to the app?  Recently, I have started having issues with my Airpods Pro on Windows 11 where resuming playback on sites like youtube  or programs like potplayer has problems.  On the sites, it takes up to 5 seconds to resume the video.  On potplayer, video resumes but audio does not, and when audio kicks in, the video lags badly.  This happens when video has been paused for a bit, like 30 seconds.  If you pause then immediately resume, this does not happen.

I used to have similar problems in windows 11 before I started using magicpods and was connecting through windows' own interfaces.  But when I started using magicpods, everything started working flawlessly, until very recently.

If there was an update, is it possible to downgrade to the previous version?  If this were a regular windows program I would uninstall and reinstall the version that worked, but I don't know if that is possible with windows store apps.

**Comment by steam3d** [comment]
Hi. The latest update did not change any of base logic.  So maybe Bluetooth driver was updated or something else. I also noticed that Apple made a little bit changes.

I try to figure out how to improve ear detection latency

**Comment by steam3d** [comment]
@okumam No. You can't downgrade. Microsoft Store does not support this. But as i said before i did not change the logic.  I tested today and did not find any issues.
