### ISSUE TITLE
magicpods can't connect but airpods can connect. Only forecful restart will fix the issue.

### ISSUE THREAD

**Issue by ghost** [steam3d/MagicPods-Windows#254]
magicpods can't connect but airpods can connect. Only forecful restart will fix the issue.

**Comment by steam3d** [comment]
Hi. Can you upload the log file?

**Comment by direrFlood** [comment]
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9868195/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9868197/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Well, at least I found issue why AirPods disconnect failed. It fixed in 1.0.41.0
