### ISSUE TITLE
need support for two screens

### ISSUE THREAD

**Issue by vv12138vv** [steam3d/MagicPods-Windows#255]
when i use two screens ，sometimes the pop-up notification appeared in wrong location

**Comment by steam3d** [comment]
Hi. Can you describe more detailed? 
I use two screens each day and extremely rarely have wrong location and only when connect or discontent display or change DPI of it. In most case everything is fine.

**Comment by vv12138vv** [comment]
emm，my main screen is 1080P,and the other is 2K,when i focus on the 1080P screen ,the pop-up notification appears in right location,but when i focus on the 2K screen,it appears in wrong location.

**Comment by steam3d** [comment]
Can you record of example such behavior and send the log files? You can send information to [MagicPods@outlook.com](mailto:MagicPods@outlook.com) if you do no want to public share. 

The MagicPods uses only primary display.  It has only one bug when taskbar has different location:
https://github.com/steam3d/MagicPods-Windows/issues/208

**Comment by steam3d** [comment]
Fixed in new version of MagicPods
