### ISSUE TITLE
When I use two screens, the pop-up is not appeared.

### ISSUE THREAD

**Issue by listentide** [steam3d/MagicPods-Windows#256]
I can't see it on any of the screens.

**Comment by steam3d** [comment]
Hi. Does it happen when you restart the MagicPods? When you set animation position to the center of the screen,  popup window appears?

1. Send screenshot how did you position your displays?
![image](https://user-images.githubusercontent.com/30986874/199193203-432efd5c-21c7-45fa-8332-f1c87d1eda0c.png)
2. Which resolution and dpi on  Display 1?
3. Which resolution and dpi on  Display 2?
4. Which of two displays is primary? 

Enable advanced collect log and use the app while you do not get the same issue:
1. Open MagicPods on `Support Page`
2. Click on MagicPods logo 5-10 time, the page will refresh.
3. Go to `General Settings` and scroll down, switch `Log level` to `debug`
4. Restart MagicPods
When you get the issue upload the log files here

**Comment by listentide** [comment]
Hi, I try to restart the software but it was unuseful. I set the position of the screens as you present. But the bottom one is smaller than the upper one. The bottom one's resolution is 2560*1660, another is 1920*1080, and the bottom is the primary display.

**Comment by steam3d** [comment]
I am sorry but i did not understand what are you talking about.
You should provide information about your environment. I requested necessary information above. You do not need to change any system settings.

**Comment by listentide** [comment]
1. I set the position of the screens as you present, but I can't screenshot for you now.
2. the dpi on display 1 is 2560 1660
3. the dpi on display 2 is 1920 1080
4. display 1 is primary.
It that clear?

**Comment by steam3d** [comment]
@listentide You should to return displays setting to your own and take screenshot how your monitors positioned.
I added screenshot to show what screenshot I need to reconfigure my own environment to try to recreated your issue.

DPI is scale factor. For example my 4k display has 150% scale factor.

**Comment by steam3d** [comment]
Fixed, Update the MagicPods.
