### ISSUE TITLE
AirPods connected and working normally but MagicPods can't detect it unless ending task

### ISSUE THREAD

**Issue by Oblivious02** [steam3d/MagicPods-Windows#260]
This has been an issue since day 1 sadly.
When reconnecting AirPods after a disconnection in the same session it infinitely keeps searching unless I force end task and reopen.
Hope this log file is enough for you to pin down the issue, thanks!

[MagicPodsUILog.zip](https://github.com/steam3d/MagicPods-Windows/files/9989016/MagicPodsUILog.zip)

**Comment by steam3d** [comment]
Hi. I see that you use a hotkey to connect AirPods Pro, but I do not see any trouble with MagicPods.
Can describe step by step how to reproduce issue?

**Comment by steam3d** [comment]
No feedback
