### ISSUE TITLE
AirPod Pro is Already Connected with the window but Magic Pod show no paired headphone?

### ISSUE THREAD

**Issue by Itshayat** [steam3d/MagicPods-Windows#261]
Hi Magic Pod,
I m getting this issue that my AirPod Pro is Already Connected with the window but Magic Pod show no paired headphone.

**Comment by steam3d** [comment]
Hi. Could you upload the log files? https://help.magicpods.app/report-issue/

**Comment by Itshayat** [comment]
how to upload this?

**Comment by steam3d** [comment]
![image](https://user-images.githubusercontent.com/30986874/204082372-b6d92c74-5abb-4653-84d1-62c46f8ebc3a.png)

**Comment by Itshayat** [comment]
[New WinRAR archive.zip](https://github.com/steam3d/MagicPods-Windows/files/10095999/New.WinRAR.archive.zip)

**Comment by Itshayat** [comment]
I have downloaded trail base once if I checked it worked then ill buy it.

**Comment by steam3d** [comment]
If it worked before than it means that cause not in MagicPods.  
Did you try reinstall MagicPods?

**Comment by steam3d** [comment]
Possible fixed in 2.0.39.0
