### ISSUE TITLE
Airpods Pro Not being detected

### ISSUE THREAD

**Issue by AX200M** [steam3d/MagicPods-Windows#262]
My airpods pro are not being detected, they are connected but when it searches for airpods it doesnt find them. I have done all debug steps but same issue, I even tried with another pair
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10096834/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10096835/MagicPodsServiceLog.txt)
Please help

**Comment by steam3d** [comment]
Hi. I see that MagicPods correctly worked on 24 November. I did not release update of MagicPods. It is mean that problem not connected to MagicPods. 

Maybe your Bluetooth adapter driver was automatically updated or installed other software or changed some Windows settings. 

You can try to reinstall the MagicPods and update Bluetooth driver manually (not through Windows update).

**Comment by steam3d** [comment]
From my side I see that Windows does not provide Bluetooth data and MagicPods does nothing and just wait data.

**Comment by Hazy-Dayz** [comment]
let me try to reinstall drivers

**Comment by Hazy-Dayz** [comment]
I have reverted the drivers but the same thing occurs

**Comment by steam3d** [comment]
You can try delete the MagicPods and reboot PC after update driver. It will rewrite all settings in Windows. After it you can try to install MagicPods. 

About 80% users who had similar issue helped update or downgrade Bluetooth driver.

**Comment by Hazy-Dayz** [comment]
aight thank you let me give it a shot

**Comment by Hazy-Dayz** [comment]
still not working

**Comment by steam3d** [comment]
Did you also try the first solution?
https://help.magicpods.app/issue-infinite-search/#solution-1
