### ISSUE TITLE
Keep pause/play when auto play and auto pause options are activated 

### ISSUE THREAD

**Issue by kiddingchicken** [steam3d/MagicPods-Windows#263]
Keep pause/play when auto play and auto pause options are activated, even tough my AirPods Pro are still in my ear.

**Comment by steam3d** [comment]
Hi. Could you upload the log files?

I think it is not Auto Pause / Play, looks like someone around you also using AirPods Pro. The Apple does not allow to detect AirPods. So it complicated to detect which AirPods Pro is yours and which not.

**Comment by steam3d** [comment]
No feedback
