### ISSUE TITLE
Uploaded Headphones images

### ISSUE THREAD

**Issue by steam3d** [steam3d/MagicPods-Windows#264]
You can upload your high quality PNG image of headphones on transparent background with resolution 512x512. It will help other users to customize their MagicPods application.

Write the headphones vendor, name and model and upload the image.

Example:
Sony SBH20
![sbh20](https://user-images.githubusercontent.com/30986874/205012862-44578178-9e11-44c8-ab0e-e652ebd21d0a.png)

**Comment by xujiahong108** [comment]
[1220.zip](https://github.com/steam3d/MagicPods-Windows/files/10218233/1220.zip)
beats fit pro(white)
