### ISSUE TITLE
Battery indicator stuck on 95% with no change

### ISSUE THREAD

**Issue by kolosovpetro** [steam3d/MagicPods-Windows#269]
Battery status from MagicPods:

![image](https://user-images.githubusercontent.com/31904595/206145161-97a4360e-3f3b-45b7-9490-fbaa1295b88d.png)

Actual battery status:

![image](https://user-images.githubusercontent.com/31904595/206145264-3d2642ba-e432-43fa-a795-52cbec229e03.png)

**Comment by steam3d** [comment]
Hi. Everything right. The battery has step 10%. This limitation cannot be bypassed.
