### ISSUE TITLE
spatial audio feature on/off

### ISSUE THREAD

**Issue by clintcfavor** [steam3d/MagicPods-Windows#271]
I've been noticing that on the AirPods Pro 2's audio keeps cutting out when I turn my head around. Might be because of the Spatial Audio feature. 

Can you add this feature to be toggled on/off?

A workaround to bring the audio back to the AirPods is to select another audio source and select the AirPods Pro 2 back. Other features like noise cancellation/transparency mode works just the audio that's been cut out.

**Comment by steam3d** [comment]
Hi. Apple does not provide any way to do it for developers. So for now it is impossible.
