### ISSUE TITLE
Can't connect to app

### ISSUE THREAD

**Issue by MicroWazzle** [steam3d/MagicPods-Windows#273]
https://pastebin.com/e6eecAAN Service log
https://pastebin.com/A4Mtbxwa UI Log

I've tried all 3 suggest solutions but none of them work is it just broken?

**Comment by steam3d** [comment]
Hi. Windows does not provide data from Bluetooth to MagicPods.  Because of it MagicPods can't do anything. This issue can not be resolved from my side. 

Some users said that they reinstalled windows and decided to try MagicPods again. MagicPods worked well. So I can make an assumption that some Windows settings may be blocking applications.

**Note. I do not recommend or encourage you to reinstall Windows.**

**Comment by steam3d** [comment]
I also know that Microsoft has different policies for different countries. You can write what language and region you have selected in WIndows. I'll try to install the system like you.

**Comment by MicroWazzle** [comment]
I have installed windows united states and english as my language

**Comment by MicroWazzle** [comment]
> Hi. Windows does not provide data from Bluetooth to MagicPods. Because of it MagicPods can't do anything. This issue can not be resolved from my side.
> 
> Some users said that they reinstalled windows and decided to try MagicPods again. MagicPods worked well. So I can make an assumption that some Windows settings may be blocking applications.
> 
> **Note. I do not recommend or encourage you to reinstall Windows.**

I will try reinstalling and let you know if it works

**Comment by MicroWazzle** [comment]
> Hi. Windows does not provide data from Bluetooth to MagicPods. Because of it MagicPods can't do anything. This issue can not be resolved from my side.
> 
> Some users said that they reinstalled windows and decided to try MagicPods again. MagicPods worked well. So I can make an assumption that some Windows settings may be blocking applications.
> 
> **Note. I do not recommend or encourage you to reinstall Windows.**

Didn't work.

**Comment by steam3d** [comment]
Check system files can help: https://help.magicpods.app/report-issue/#check-system-files
