### ISSUE TITLE
AirPods disconnect when case is open - Windows 11 

### ISSUE THREAD

**Issue by X512B11** [steam3d/MagicPods-Windows#274]
For some reason, my AirPods disconnect when I open the case. The AirPods are still in my ear. To reconnect to the AirPods, I need to turn to turn off Bluetooth then back on. Any help or information would be appreciated.

-Windows 11 (latest update)

Thanks.

**Comment by steam3d** [comment]
Hi. Do you use AirPods Pro Gen 2? Do you wear both AirPods and case is empty?

**Comment by X512B11** [comment]
Hi,

I have just the regular AirPods 2 (not pro). I usually just use one of the ear piece (the other one is left in the case). But it seems if I open the case, I lose audio but the AirPods still say they are connected to bluetooth.

 I recently upgraded to a new Windows 11 laptop and it seems to have lots of issues with AirPods, what was not the case with Windows 10, so I don't know what is missing from Windows 11.

**Comment by steam3d** [comment]
Related to Windows itself, not to MagicPods
