### ISSUE TITLE
Text Change: Middle to Medium

### ISSUE THREAD

**Issue by pairofcrocs** [steam3d/MagicPods-Windows#275]
I think technically, in `Windows size` it should say Medium instead of Middle.

Small
Middle
Large

VS 

Small
Medium
Large

Just my 2 cents :) Great product, keep up the good work <3

**Comment by steam3d** [comment]
Hi. You could fix English translation on this page:
https://weblate.magicpods.app/projects/magicpods-windows/magicpodsui/en_devel/

Thanks. I will update translation with next update.
