### ISSUE TITLE
Non-Apple headphones now appear in MagicPods

### ISSUE THREAD

**Issue by crawfishie** [steam3d/MagicPods-Windows#277]
I've just noticed my Bose QC II earbuds and other non-Apple BT headphones now show in MagicPods, which is a nice addition! However, there are two things that would make it even better:

1. Enable the "Low Audio Latency" feature for them. I currently need to run another program to do this.
2. Show their battery status in the system tray.

**Comment by steam3d** [comment]
I can get battery info only when headset is turn off, so you can not be able to use headphone as microphone only like headphones.

**Comment by crawfishie** [comment]
That's no problem, because I disable Headset for all my headphones. Thus, for my purposes, it would be great if you could add battery display even with this limitation.

**Comment by steam3d** [comment]
Experimental showing battery for unsupported headphones added in 2.0.41.0.  You could try, maybe it will work for you. I highly recommend to read information on help page.

https://help.magicpods.app/headphones-show-battery-percentage/

**Comment by crawfishie** [comment]
Thanks for this! It works for my 1More ColorBuds 2, but it doesn't work for my Bose QuietComfort EarBuds II. The Bose are the ones I actually use with my PC, so if there's anything I can do to help, let me know.
