### ISSUE TITLE
Не подключаются Pro

### ISSUE THREAD

**Issue by izotope1** [steam3d/MagicPods-Windows#28]
![image](https://user-images.githubusercontent.com/66484533/93712383-3e5cfb00-fb5e-11ea-8ced-f375ca57f483.png)

Сначала не показывали заряд кейса, теперь вообще не подключают

**Comment by steam3d** [comment]
Подождите 10-20 сек, приложение обновит информацию о батареи. Можно так же сюда прикрепить лог файл, что бы удостоверится, что приложение видит наушники.
