### ISSUE TITLE
Magicpod stopped working after windows 11 update

### ISSUE THREAD

**Issue by nelsontyc** [steam3d/MagicPods-Windows#280]
![image](https://user-images.githubusercontent.com/51257403/209239471-3ab26515-cb1e-482b-9e14-3a5d491a0256.png)

**Comment by steam3d** [comment]
Hi. You could upload log files here, but your issue is not related to MagicPods. Looks like it is windows update issue.

**Comment by mihanich** [comment]
Hey. same for me. attaching logs.
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10299823/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10299824/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
@mihanich 
Hi. Open the MagicPods on support page. Click 5-10 time on MagicPods logo while page do not refresh. Then go to General Settings scroll down and change Log level to Debug or Trace. Restart the app.

Open the MagicPods again and go to support page, click on debug log and upload log files here.

**Comment by steam3d** [comment]
Could you also show screenshot of Narrator’s voice and  Region & language settings page?
![image](https://user-images.githubusercontent.com/30986874/209469518-77f1af5e-ff17-4f69-9588-693c37a0e123.png)
![image](https://user-images.githubusercontent.com/30986874/209469548-bad03e64-3891-4b74-9b1b-a4e79ec4917d.png)

**Comment by mihanich** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicP
![Screenshot 2022-12-25 152506](https://user-images.githubusercontent.com/29480208/209469778-482ed460-0a83-4972-a6a4-f0b8409dfce4.png)
ods-Windows/files/10300011/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10300012/MagicPodsUILog
![Screenshot 2022-12-25 152637](https://user-images.githubusercontent.com/29480208/209469789-626fb0a9-4fe7-435b-93e2-b34bfaa4f99c.png)
.txt)

here you are)

**Comment by steam3d** [comment]
@mihanich 
I think this issue because field "Choose a voice" is empty.  If you add any voice and restart MagicPods everything will work I think. (It is temporary solution, because I am trying to find way to reproduce it).

But anyway how could you installed the Windows without any voices? I have been trying to install Windows for the third day without votes. (they are always set by default). 

Do you have Windows 11 single language edition with Ukraine language as primary?

**Comment by mihanich** [comment]
nope, just installed fresh from official usb image. maybe by default there is no default voice package.

**Comment by steam3d** [comment]
@mihanich  Did adding any voice help?

**Comment by mihanich** [comment]
just downloaded)
Yes, now works. will watch what happen, but hope it would fix for a long time.
Thank you!

**Comment by steam3d** [comment]
@mihanich  I will fix this issue when I could to install Windows without voice package.  Thanks for your help.

**Comment by nelsontyc** [comment]
![image](https://user-images.githubusercontent.com/51257403/209488769-6197cd62-c038-469b-ac04-3e364cd10542.png)

Hi, Thanks for finding the solution. However, whenever i am trying to go to the voiceover configuration, the magicpod app will just crash. I can't add any voice package due to it.

**Comment by steam3d** [comment]
@nelsontyc That's right, you need to configure Windows not MagicPods. 

1. Close MagicPods
2. Follow this guide's steps to add any voice https://help.magicpods.app/fun-audio/#add-a-new-voice
3. Run MagicPods everything should works.

**Comment by nelsontyc** [comment]
Hi, thanks for the reply! The instruction is not relevant as the settings in Windows 11 is different. I tried to add the voice in the new menu, but the same error still persists. 
![image](https://user-images.githubusercontent.com/51257403/209547310-80607286-2a08-4c70-a3c9-e144b59a7ac1.png)

**Comment by steam3d** [comment]
Did you try to reboot PC? I tested couple minutes ago on my system. After reboot MagicPods started to work. 

If you still have issue after reboot so I could wait the update with fix. I am working on it right now.

**Comment by nelsontyc** [comment]
Ok i will wait for the fix then! Thanks for the support!

**Comment by steam3d** [comment]
I uploaded update 1.0.38.0 to Microsoft Store, based on my test everything should work.
