### ISSUE TITLE
Cannot Find my Airpods in Software

### ISSUE THREAD

**Issue by herm11t** [steam3d/MagicPods-Windows#281]
![image](https://user-images.githubusercontent.com/121337655/209429422-cb2c226c-2b47-4fa1-b986-57586b94a026.png)

![image](https://user-images.githubusercontent.com/121337655/209429469-1825b2d5-8565-4f91-9390-a80bc699953c.png)

![image](https://user-images.githubusercontent.com/121337655/209429513-c722b90f-eb3e-400f-9302-30be9e8baf06.png)

**Comment by steam3d** [comment]
Hi. Open the MagicPods on support page. Click 5-10 time on MagicPods logo while page do not refresh. Then go to General Settings scroll down and change Log level to Debug or Trace.  Restart the app. 

Open the MagicPods again and go to support page, click on debug log and upload log files here.

**Comment by herm11t** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10298314/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10298315/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Looks like it is external error related to Narrator Settings (Windows logo key + Ctrl + N).
1. Do you have original Windows without any tweaks? 
2. Do you have any installed Narrator voice? 
3. Does MagicPods crash If you choose any voice in VoiceOver settings and click speak?
![image](https://user-images.githubusercontent.com/30986874/209439760-5bab17f7-32fa-43fe-bcd3-f02595abe606.png)

**Comment by herm11t** [comment]
It has not been found in MagicPods since it was updated the day before yesterday.
1.no
2.no
3.I never enabled VoiceOver,but if I enable VoiceOver, clicking VoiceOver settings will crash.
![image](https://user-images.githubusercontent.com/121337655/209442223-361993e3-30af-43c5-a115-88b5c4caafd7.png)

**Comment by steam3d** [comment]
MagicPods will crash on previous version on your PC too. It's also use VoiceOver, I think It's just a coincidence that the app hasn't crashed before.

1. You could check system files on error:
https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e
2. Add any voice in Narrator Settings (Sorry, I do not have screenshot on EN language). [This article can help](https://help.magicpods.app/fun-audio/#add-a-new-voice)
![image](https://user-images.githubusercontent.com/30986874/209443123-2b2488be-c636-4718-936a-f5cf880ffe3b.png)
3. Try to "speak" with added voice. 

By default Windows always has an English voice installed, but you said you did not have any voice so maybe it is the cause.
