### ISSUE TITLE
always loading

### ISSUE THREAD

**Issue by Marspotatopop** [steam3d/MagicPods-Windows#283]
the software is always loading, but cannot show my airpods

**Comment by steam3d** [comment]
Hi.

1. Try to force exit the MagicPods. https://help.magicpods.app/issue-airpods-status-not-updating/
2. Reboot PC to refresh hardware environment.

if these steeps do not help you need to upload log files manually to this chat.
1. Press Win +R
2. Past this text:  `%LOCALAPPDATA%\Packages\715AleksandrMaslov.MagicPods_vk1h99z2mpttm\TempState` 
3. Upload 2 txt files here

**Comment by Marspotatopop** [comment]
Thanks! Problem seems no longer exist
