### ISSUE TITLE
Had an updated to Windows 11, now have issues 

### ISSUE THREAD

**Issue by blacknumberone** [steam3d/MagicPods-Windows#284]
I have Windows 11 and have been using MagicPods app with no problem, but recently I did a Windows 11 update and now I'm having issues. MP app message "Couldn't find AirPods" "Follow this guide to fix the problem". ... It connects to Bluetooth with no problem, but MagicPods doesn't work like it used to. Sometimes it connects, especially if I do a restart on my computer but most of the time it's a no-go. Is there an update coming out for MagicPods?

**Comment by steam3d** [comment]
Hi. Issue related to windows update. The MagicPods supports Windows 11 from release. 

Looks like something with Bluetooth driver. You could upload the log files, to check maybe some issue will be find.

**Comment by blacknumberone** [comment]
How do I upload the log files? thanks in advance... Still having issues even after I updated MagicPods... I was very happy with the app, I hope it can be fixed!

**Comment by steam3d** [comment]
Just drag & drop file here

**Comment by steam3d** [comment]
Here is the instruction: 
https://help.magicpods.app/report-issue/

**Comment by blacknumberone** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10452175/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10452176/MagicPodsUILog.txt)

Is this what you were looking for?

**Comment by steam3d** [comment]
What’s the problem? I see that everything works as expected

**Comment by steam3d** [comment]
Could you use GitHub instead of mail? I did get screenshots. What your described sounds like a driver issue.  Because based on log files I don’t see any trouble

**Comment by blacknumberone** [comment]
I updated the app (going to the store and saw an update for the app), still didn't work correctly after the update... so I installed your app and reinstalled it and now it seems to work!  Thanks
