### ISSUE TITLE
Can you add the feature to stream to the computer only if the AirPods are connected to the computer?

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#288]
Hey,
Can you add the feature to stream to the computer only if the AirPods are connected to the computer?
You can make it in two steps:
1) When AirPods are connected, → stream iPhone audio to the computer.
2) When AirPods are disconnected, → stop streaming iPhone audio to the computer.

**Comment by steam3d** [comment]
Hi. This is a new feature, I will wait 1 month for feedback. For iPhone looks like it can work like you described but there are lot of other devices. 

So if everything alright, I will add such behavior in future updates

**Comment by steam3d** [comment]
I tried to make this. This is very buggy feature. Sometimes everything works as expected, sometimes connections stuck, sometimes iPhone refuse accept connection. It also can trigger Windows to disconnect all Bluetooth devices connected and reconnect them.

Looks like Windows too busy when connect headphone and connection failed to other devices. I can add delay like 60 seconds before connect streaming device, but I am not sure that it make sense.

**Comment by steam3d** [comment]
Workaround is adding hotkeys to connect / disconnect specified streaming device. I will think how to implement this.

**Comment by steam3d** [comment]
Added htokeys to connect and disconnectingstreaming device. Update to 2.0.78.0.
