### ISSUE TITLE
Airpods Pro did not work

### ISSUE THREAD

**Issue by jackyname1** [steam3d/MagicPods-Windows#29]
I opened my airpods and nothing happened !
My log file:

9/21/2020 7:48:20 AM ----------------- --- [Info]  |                | Start program
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | search_by_rssi: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | log_lvl: Info
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | auto_connect: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | volume_down_percent: 75
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | ear_detection: Volume
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | is_ble: True
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | search_min_rssi: -60
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | debug_mode: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | hide_tips: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | recommended_packet_count: 0
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | battery_tray_icon: True
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | recommended_rssi: -180
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | hide_tray_icon: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | hide_welcome_screen: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | recommended_rssi_count: 0
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | animation_rssi: -65
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | battery_tray_icon_type: Analog
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | show_connect_btn: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | send_play: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | low_latency: False
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | search_max_rssi: 0
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | animation: True
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | animation_size: Small
9/21/2020 7:48:20 AM ----------------- --- [Info]  |    Settings    | additional_media_players: True
9/21/2020 7:48:25 AM ----------------- --- [Info]  |                | Run AirpodsState
9/21/2020 7:48:25 AM A3:D1:C7:24:75:CB --- [Info]  |GetPairedDevices| Find AirPods Pro Model airpods1 Disconnected
9/21/2020 7:48:25 AM ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
9/21/2020 7:48:25 AM ----------------- --- [Info]  |                | AirPods found
9/21/2020 7:48:25 AM ----------------- --- [Info]  |                | Advertisement watcher started!
9/21/2020 7:48:35 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:49:05 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 7:49:05 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 7:49:07 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:49:18 AM ----------------- --- [Info]  |                | Advertisement watcher stopped
9/21/2020 7:49:28 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 7:49:31 AM A3:D1:C7:24:75:CB --- [Info]  |GetPairedDevices| Find AirPods Pro Model airpods1 Disconnected
9/21/2020 7:49:31 AM ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
9/21/2020 7:49:31 AM ----------------- --- [Info]  |                | AirPods found
9/21/2020 7:49:31 AM ----------------- --- [Info]  |                | Advertisement watcher started!
9/21/2020 7:49:32 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 7:49:34 AM ----------------- --- [Info]  |                | Connection to UWP lost
9/21/2020 7:49:34 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:50:24 AM ----------------- --- [Info]  |                | Connection to UWP lost
9/21/2020 7:50:31 AM ----------------- --- [Info]  |                | Advertisement watcher stopped
9/21/2020 7:50:44 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 7:50:46 AM A3:D1:C7:24:75:CB --- [Info]  |GetPairedDevices| Find AirPods Pro Model airpods1 Disconnected
9/21/2020 7:50:46 AM ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
9/21/2020 7:50:46 AM ----------------- --- [Info]  |                | AirPods found
9/21/2020 7:50:46 AM ----------------- --- [Info]  |                | Advertisement watcher started!
9/21/2020 7:50:47 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 7:50:50 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:50:53 AM ----------------- --- [Info]  |                | Spotify vol: 0.1579666
9/21/2020 7:51:46 AM ----------------- --- [Info]  |                | Connection to UWP lost
9/21/2020 7:53:01 AM ----------------- --- [Info]  |                | Start program
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | search_by_rssi: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | log_lvl: Info
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | auto_connect: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | volume_down_percent: 75
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | ear_detection: Volume
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | is_ble: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | search_min_rssi: -55
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | debug_mode: False
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | hide_tips: False
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | recommended_packet_count: 0
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | battery_tray_icon: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | recommended_rssi: -180
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | hide_tray_icon: False
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | hide_welcome_screen: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | recommended_rssi_count: 0
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | animation_rssi: -65
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | battery_tray_icon_type: Digital
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | show_connect_btn: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | send_play: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | low_latency: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | search_max_rssi: 0
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | animation: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | animation_size: Small
9/21/2020 7:53:01 AM ----------------- --- [Info]  |    Settings    | additional_media_players: True
9/21/2020 7:53:01 AM ----------------- --- [Info]  |                | Run AirpodsState
9/21/2020 7:53:01 AM A3:D1:C7:24:75:CB --- [Info]  |GetPairedDevices| Find AirPods Pro Model airpods1 Disconnected
9/21/2020 7:53:01 AM ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
9/21/2020 7:53:01 AM ----------------- --- [Info]  |                | AirPods found
9/21/2020 7:53:01 AM ----------------- --- [Info]  |                | Advertisement watcher started!
9/21/2020 7:53:35 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:54:05 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 7:54:05 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 7:54:06 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:58:26 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 7:58:29 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 7:58:48 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 7:58:51 AM ----------------- --- [Info]  |                | ShellExperienceHost vol: 0.1730378
9/21/2020 7:58:51 AM ----------------- --- [Info]  |                | chrome vol: 0.2694328
9/21/2020 7:59:01 AM ----------------- --- [Info]  |                | Connection to UWP lost
9/21/2020 8:00:16 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:00:43 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:02:13 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:02:16 AM ----------------- --- [Info]  |                | Spotify vol: 0.130485
9/21/2020 8:02:23 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:02:24 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:02:24 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:02:26 AM ----------------- --- [Info]  |                | Spotify vol: 0.2639537
9/21/2020 8:02:26 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:02:29 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:02:54 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:02:56 AM ----------------- --- [Info]  |                | Spotify vol: 0.1410303
9/21/2020 8:03:02 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:03:08 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:03:14 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:03:16 AM ----------------- --- [Info]  |                | Spotify vol: 0.3203421
9/21/2020 8:03:17 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:03:17 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:03:20 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:03:23 AM ----------------- --- [Info]  |                | Spotify vol: 0.256515
9/21/2020 8:03:26 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:03:27 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:04:15 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:04:17 AM ----------------- --- [Info]  |                | Spotify vol: 0.04286528
9/21/2020 8:04:18 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:04:20 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:04:26 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:04:28 AM ----------------- --- [Info]  |                | Spotify vol: 0.17073
9/21/2020 8:04:30 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:04:30 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:04:35 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
9/21/2020 8:04:37 AM ----------------- --- [Info]  |                | Spotify vol: 0.2405918
9/21/2020 8:04:48 AM ----------------- --- [Info]  |                | Connection to UWP lost
9/21/2020 8:05:03 AM ----------------- --- [Info]  |                | force_hide clear
9/21/2020 8:05:03 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Disconnected (IsAirPodsConnected False)
9/21/2020 8:05:05 AM A3:D1:C7:24:75:CB --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)

**Comment by steam3d** [comment]
Hi. It is known issue and doesn't have solution. Sometimes helps update Bluetooth driver or delete all AirPods from Windows and add those again.

Looks like it is problem with specific Bluetooth dongle. I tried on some devices and couldn't repeat this issue.

**Comment by steam3d** [comment]
No feedback
