### ISSUE TITLE
Ear detection not available for Airpods pro 2

### ISSUE THREAD

**Issue by mrcoprea** [steam3d/MagicPods-Windows#290]
I just replaced my Airpods pro 1 with the 2nd gen and now the ear detection option is not there anymore.

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10401841/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10401842/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Hi. AirPods Pro 2 doesn’t support ear detection.

**Comment by steam3d** [comment]
I understood, I will rename AirPods name to do not confuse people. 

Headphones capability:
https://help.magicpods.app/fun-capability/

Discussion AirPods Pro 2:
https://github.com/steam3d/MagicPods-Windows/issues/246

AirPods Pro and AirPods Pro 2 it is different headphones like Google Pixel Buds and Galaxy Buds.
