### ISSUE TITLE
Update Icons for the Sound Output feature

### ISSUE THREAD

**Issue by l0lGhostlxl** [steam3d/MagicPods-Windows#291]
When the sound output feature is used, the icons for the speakers look old and dated, and look heavily aliased. Instead it would be better to use the stock Windows 11 speaker Icon, as it would look more integrated with the OS.

**Comment by steam3d** [comment]
Hi. It designed to be compatible with dark and light theme and has similar style like headphone images do that use in MagicPods. 

So if you don’t like it, you can replace image on your own if you like.

**Comment by l0lGhostlxl** [comment]
Ah that makes sense, thank you for the clarification.
