### ISSUE TITLE
Connection problem with Surface Pro X ARM Win 11

### ISSUE THREAD

**Issue by Krometti7** [steam3d/MagicPods-Windows#292]
Hello there,

MagicPods won't see my Airpods. I'm running it on a Surface Pro X with Win 11, they are paired and work perfectly with other apps, but Magic Pods doesn't recognize them. Just bought the app 2 days ago. Can you please help? 

Here's the log file

 18.01.2023 20:45:51   [Info]  |MigrateLocalSett| Just updated settings version from 0 to 2
18.01.2023 20:45:51   [Info]  |      app       | Start program
18.01.2023 20:45:52   [Info]  |    Welcome     | Try to process WelcomeAnimation1.json
18.01.2023 20:45:52   [Info]  |    Welcome     | File ready WelcomeAnimation1.json
18.01.2023 20:45:54   [Info]  |    Welcome     | Try to process WelcomeAnimation2.json
18.01.2023 20:45:54   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 20:45:54   [Info]  |    Welcome     | File ready WelcomeAnimation2.json
18.01.2023 20:45:55   [Info]  |    Welcome     | Try to process WelcomeAnimation3.json
18.01.2023 20:45:55   [Info]  |    Welcome     | File ready WelcomeAnimation3.json
18.01.2023 20:45:56   [Info]  |    Welcome     | Try to process WelcomeAnimation4.json
18.01.2023 20:45:56   [Info]  |    Welcome     | File ready WelcomeAnimation4.json
18.01.2023 20:46:07   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:46:07   [Info]  |Headphones page | Request headphones
18.01.2023 20:46:07   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:48:11   [Error] |      App       | Error has occured
18.01.2023 20:48:12   [Info]  |      app       | Start program
18.01.2023 20:48:12   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 20:48:17   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:48:17   [Info]  |Headphones page | Request headphones
18.01.2023 20:48:17   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:48:56   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:48:56   [Info]  |Headphones page | Request headphones
18.01.2023 20:48:56   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:50:34   [Info]  |      app       | Start program
18.01.2023 20:50:34   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 20:51:03   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:51:03   [Info]  |Headphones page | Request headphones
18.01.2023 20:51:03   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:51:53   [Error] |      App       | Error has occured
18.01.2023 20:51:54   [Info]  |      app       | Start program
18.01.2023 20:51:54   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 20:51:59   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:51:59   [Info]  |Headphones page | Request headphones
18.01.2023 20:51:59   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:53:11   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:53:11   [Info]  |Headphones page | Request headphones
18.01.2023 20:53:11   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:54:08   [Info]  |Headphones page | ListView_Loaded
18.01.2023 20:54:08   [Info]  |Headphones page | Request headphones
18.01.2023 20:54:08   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 20:55:21   [Error] |      App       | Error has occured
18.01.2023 20:55:22   [Info]  |      app       | Start program
18.01.2023 20:55:22   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 21:02:43   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:02:43   [Info]  |Headphones page | Request headphones
18.01.2023 21:02:43   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:03:59   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:03:59   [Info]  |Headphones page | Request headphones
18.01.2023 21:04:00   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:04:21   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:04:21   [Info]  |Headphones page | Request headphones
18.01.2023 21:04:21   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:08:46   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:08:46   [Info]  |Headphones page | Request headphones
18.01.2023 21:08:46   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:08:59   [Error] |      App       | Error has occured
18.01.2023 21:08:59   [Info]  |      app       | Start program
18.01.2023 21:08:59   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 21:09:04   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:09:04   [Info]  |Headphones page | Request headphones
18.01.2023 21:09:04   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:10:08   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:10:08   [Info]  |Headphones page | Request headphones
18.01.2023 21:10:08   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:10:09   [Error] |      App       | Error has occured
18.01.2023 21:10:09   [Info]  |      app       | Start program
18.01.2023 21:10:09   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 21:10:14   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:10:14   [Info]  |Headphones page | Request headphones
18.01.2023 21:10:14   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 21:10:43   [Info]  |Headphones page | ListView_Loaded
18.01.2023 21:10:43   [Info]  |Headphones page | Request headphones
18.01.2023 21:10:43   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 22:33:31   [Info]  |      app       | Start program
18.01.2023 22:33:32   [Info]  |Headphones page | ListView_Loaded
18.01.2023 22:33:32   [Info]  |Headphones page | App connection was null. Can't get headphones list.
18.01.2023 22:33:32   [Info]  |      app       | connection established from the fulltrust process
18.01.2023 22:33:32   [Info]  |Headphones page | App_AppServiceConnected
18.01.2023 22:33:32   [Info]  |Headphones page | Request headphones
18.01.2023 22:33:33   [Info]  |                | Program state changed to On
18.01.2023 22:33:33   [Info]  |Headphones page | Request headphones
18.01.2023 22:33:33   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 22:34:55   [Info]  |Headphones page | ListView_Loaded
18.01.2023 22:34:55   [Info]  |Headphones page | Request headphones
18.01.2023 22:34:55   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 22:52:24   [Info]  |Headphones page | ListView_Loaded
18.01.2023 22:52:24   [Info]  |Headphones page | Request headphones
18.01.2023 22:52:24   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
18.01.2023 23:03:01   [Error] |      App       | Error has occured
18.01.2023 23:03:02   [Info]  |      app       | Start program
18.01.2023 23:03:02   [Info]  |      app       | connection established from the fulltrust process
20.01.2023 11:33:05   [Info]  |Headphones page | ListView_Loaded
20.01.2023 11:33:05   [Info]  |Headphones page | Request headphones
20.01.2023 11:33:05   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
20.01.2023 11:33:11   [Info]  |Headphones page | ListView_Loaded
20.01.2023 11:33:11   [Info]  |Headphones page | Request headphones
20.01.2023 11:33:11   [Info]  |HeadphonesMessag| Pc does not have paired headphones.
20.01.2023 11:40:53   [Info]  |                | Program state changed to SessionLock
20.01.2023 11:40:54   [Info]  |HeadphonesMessag| Hide help message
20.01.2023 12:01:20   [Info]  |                | Program state changed to On
20.01.2023 12:01:20   [Info]  |Headphones page | Request headphones
20.01.2023 12:01:21   [Info]  |HeadphonesMessag| Pc does not have paired headphones.

**Comment by steam3d** [comment]
Hi. MagicPods doesn’t support arm architecture.

![D5D896A7-3B8E-43D7-9C51-90E038320A64](https://user-images.githubusercontent.com/30986874/213803514-db45d0f1-8597-49f8-b374-15c311695477.jpeg)

**Comment by Krometti7** [comment]
Hi Alexander, 

thank you for the reply!

On my Microsoft store is checked with a green tick saying "this App will work on your device. System requirements are satisfied etc..." lol  I blind trusted the green tick before reading the system requirements. 

I'll ty to get a refund, but i guess Microsoft should not write such misleading informations on their store. 

Thank you anyway and ahave a good day.

Max
