### ISSUE TITLE
Shortcut unavailable after deleting Airpods through windows bluetooth settings

### ISSUE THREAD

**Issue by JLIspace** [steam3d/MagicPods-Windows#294]
Shortcut unavailable after deleting Airpods through windows bluetooth settings

Add ALT+M shortcut
delete Airpods from windows bluetooth settings
Trying to add ALT+M to other pair of airpods -> won't work

**Comment by steam3d** [comment]
Hi. It because settings for old headphone saved. Just reset settings to default one on Preference page.
