### ISSUE TITLE
Some hotkeys are not regisetered.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#295]
Hey,
I try to register Windows + Shift + T to the magic pods.
I noticed this happens to magic select.
Here it is stuck not getting the T hotkey, so it is something like (Windows + Shift + T).
![Here it is stuck not getting the T hotkey, so it is something like (Windows + Shift + T).](https://user-images.githubusercontent.com/119108387/214593433-48a9d6cc-b67c-49ef-ae0a-04c8f701c128.png)
Also, I was wondering where can I find the magic select repo to discuss issues.

**Comment by steam3d** [comment]
Hi. Yes, it is Windows API limitation.  You need to choose other hotkey.  Unfortunately I did not find other way to bind hotkeys. I suppose Windows reserved some keys.

![image](https://user-images.githubusercontent.com/30986874/214626844-0e6766fd-2d28-4080-a0ef-e0db22eea688.png)

**Comment by bigplayer-ai** [comment]
> Hi. Yes, it is Windows API limitation.  You need to choose other hotkey.  Unfortunately I did not find other way to bind hotkeys. I suppose Windows reserved some keys.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/30986874/214626844-0e6766fd-2d28-4080-a0ef-e0db22eea688.png)
> 
> 

On power toys every hot key is possible.

**Comment by steam3d** [comment]
Yep. PowerToys is developed by team from Microsoft. Anyway the Microsoft docs says:
![image](https://user-images.githubusercontent.com/30986874/214639717-00add37a-ebdc-4913-9be0-b3e394d7f78e.png)

**Comment by bigplayer-ai** [comment]
Not planned
