### ISSUE TITLE
I can't change all speakers/audio sources icons, I wish if you can add us this option to change all audio sources icons.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#296]
Hey,
I use sound output windows, I wish if you can add us the option to change all audio sources icons (Non-bluetooth devices).

**Comment by steam3d** [comment]
Hi. Yes I already thought about it, I will add this option later.

**Comment by bigplayer-ai** [comment]
When are you implementing this?

**Comment by steam3d** [comment]
I am not sure, maybe next update.  I have higher priority tasks.

**Comment by steam3d** [comment]
It will be available in next update. More info and demo video you can find on Discord server.
