### ISSUE TITLE
Fake AirPods

### ISSUE THREAD

**Issue by steam3d** [steam3d/MagicPods-Windows#298]
If you have fake AirPods you could help to add it to MagicPods.

1. Download the **DeviceFinder** tool
[DeviceFinder_1.zip](https://github.com/steam3d/MagicPods-Windows/files/4911413/DeviceFinder_1.zip)
2. Unzip **DeviceFinder** to any folder
3. Be sure that headphones already paired with PC
4. Turn on BT on your PC
5. Run the **DeviceFinder.exe**
6. Open case of your headphones. 
7. Wait 5-10 second then close the **DeviceFinder.exe** 
8. Find the file **log.txt** near **DeviceFinder.exe**
9. Write the fake AirPods model and current battery of AirPods and case

**Comment by agateophobe** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/11131348/log.txt)
model Airpods Pro
chipset BN230105cc
Left pod 66% right pod 68% case 44%

**Comment by Edvincoderolan** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/11183281/log.txt)
model Airpods Pro 2 gn
chipset no info
![Screenshot_2](https://user-images.githubusercontent.com/72279134/230721531-2fb3bdaa-4c2b-4f29-b264-15d8140455a8.png)

**Comment by Daniel02706** [comment]
perdón, pero no entiendo, después de cargar el modelo en el archivo, que hago o mejor dicho, donde lo guardo o a donde lo paso?

**Comment by steam3d** [comment]
@Daniel02706 Drag'n'drop log.txt file and add description of your fake AirPods as did users above

**Comment by 2952004791my** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/11458759/log.txt)
型号 Airpods Pro
芯片组 悦虎1562AE
怎么才能连接上

**Comment by steam3d** [comment]
@2952004791my  let my know if it works for you.

**Comment by steam3d** [comment]
Added Fake AirPods Pro 2 Airoha 1562AE and AirPods 3 1562E to MagicPods 2.0.53.0

**Comment by MagicGazelle** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/12839895/log.txt)
Model Airpods Pro 2
Chipset Huilian H2s Pro 277
Battery left 100% right 100% case 81%
