### ISSUE TITLE
Add a hotkey to switch default output like soundswitch does.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#299]
Hey,
can you add a hotkey to switch default output sound like soundswitch does?
https://github.com/Belphemur/SoundSwitch/releases

**Comment by steam3d** [comment]
Hi. It's possible, if there is a request from more users

**Comment by d0tiKs** [comment]
Hi, is there some page where we could vote for feature request or just commenting here is sufficient ?

**Comment by steam3d** [comment]
Comment is enought. If you have other request you can open issue and I and other users will discuss.

**Comment by bigplayer-ai** [comment]
How about mute and input devicesOn 19 Apr 2023, at 1:22, Alexander Maslov ***@***.***> wrote:﻿
@svalencia014 It's ready. I am testing this feature. It will be released next update.

**Comment by steam3d** [comment]
Added. Update to 2.0.50.0
