### ISSUE TITLE
single airpods volume abnormal

### ISSUE THREAD

**Issue by aaaaahua** [steam3d/MagicPods-Windows#30]
During worktime, I often only take single airpods from power box to listen songs, but the volume is always reset to 94, which is very loud 
i use airpods1

**Comment by steam3d** [comment]
Hi. Have you tried without a MagicPods? Can you attach a log file?

**Comment by aaaaahua** [comment]
> Hi. Have you tried without the MagicPods? Can you attach a log file?

2020/9/21 16:49:42 ----------------- --- [Info]  |                | Start program
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | search_by_rssi: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | log_lvl: Info
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | auto_connect: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | volume_down_percent: 75
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | ear_detection: Volume
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | is_ble: True
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | search_min_rssi: -60
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | debug_mode: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | hide_tips: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | recommended_packet_count: 0
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | battery_tray_icon: True
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | recommended_rssi: -180
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | hide_tray_icon: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | hide_welcome_screen: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | recommended_rssi_count: 0
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | animation_rssi: -65
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | battery_tray_icon_type: Analog
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | show_connect_btn: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | send_play: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | low_latency: False
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | search_max_rssi: 0
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | animation: True
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | animation_size: Small
2020/9/21 16:49:42 ----------------- --- [Info]  |    Settings    | additional_media_players: True
2020/9/21 16:49:43 ----------------- --- [Info]  |                | Run AirpodsState
2020/9/21 16:49:43 74:9E:AF:E4:DA:9F --- [Info]  |GetPairedDevices| Find Jiahui AirPods Model airpods1 Disconnected
2020/9/21 16:49:43 ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
2020/9/21 16:49:43 ----------------- --- [Info]  |                | AirPods found
2020/9/21 16:49:43 ----------------- --- [Info]  |                | Advertisement watcher started!
2020/9/21 16:50:00 59:89:B3:5D:EB:3B -53 [Info]  |  Print Action  | Open close| All out
2020/9/21 16:50:08 6F:BA:DD:6D:E8:12 -87 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:50:19 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| Jiahui AirPods Connected (IsAirPodsConnected True)
2020/9/21 16:50:31 6F:BA:DD:6D:E8:12 -59 [Info]  |   MyAirPods    | Founded
2020/9/21 16:50:31 6F:BA:DD:6D:E8:12 -60 [Info]  | Media control  | RestoreVolume
2020/9/21 16:50:31 6F:BA:DD:6D:E8:12 -60 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:51:10 6F:BA:DD:6D:E8:12 -59 [Info]  | Media control  | VolumeDown
2020/9/21 16:51:10 6F:BA:DD:6D:E8:12 -59 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:51:28 6F:BA:DD:6D:E8:12 -60 [Info]  | Media control  | RestoreVolume
2020/9/21 16:51:28 6F:BA:DD:6D:E8:12 -60 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:51:32 6F:BA:DD:6D:E8:12 -63 [Info]  | Media control  | VolumeDown
2020/9/21 16:51:32 6F:BA:DD:6D:E8:12 -63 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:51:45 6F:BA:DD:6D:E8:12 -47 [Info]  | Media control  | RestoreVolume
2020/9/21 16:51:45 6F:BA:DD:6D:E8:12 -47 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:51:51 6F:BA:DD:6D:E8:12 -50 [Info]  | Media control  | VolumeDown
2020/9/21 16:51:51 6F:BA:DD:6D:E8:12 -50 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:52:03 6F:BA:DD:6D:E8:12 -55 [Info]  | Media control  | RestoreVolume
2020/9/21 16:52:03 6F:BA:DD:6D:E8:12 -55 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:52:07 6F:BA:DD:6D:E8:12 -58 [Info]  | Media control  | VolumeDown
2020/9/21 16:52:07 6F:BA:DD:6D:E8:12 -58 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:52:20 6F:BA:DD:6D:E8:12 -50 [Info]  | Media control  | RestoreVolume
2020/9/21 16:52:20 6F:BA:DD:6D:E8:12 -50 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:52:28 6F:BA:DD:6D:E8:12 -46 [Info]  | Media control  | VolumeDown
2020/9/21 16:52:28 6F:BA:DD:6D:E8:12 -46 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:52:29 6F:BA:DD:6D:E8:12 -49 [Info]  | Media control  | RestoreVolume
2020/9/21 16:52:29 6F:BA:DD:6D:E8:12 -49 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:53:19 6F:BA:DD:6D:E8:12 -52 [Info]  | Media control  | VolumeDown
2020/9/21 16:53:19 6F:BA:DD:6D:E8:12 -52 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:53:21 6F:BA:DD:6D:E8:12 -57 [Info]  | Media control  | RestoreVolume
2020/9/21 16:53:21 6F:BA:DD:6D:E8:12 -57 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:53:28 6F:BA:DD:6D:E8:12 -60 [Info]  | Media control  | VolumeDown
2020/9/21 16:53:28 6F:BA:DD:6D:E8:12 -60 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:54:12 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/21 16:55:07 6F:BA:DD:6D:E8:12 -54 [Info]  | Media control  | RestoreVolume
2020/9/21 16:55:07 6F:BA:DD:6D:E8:12 -54 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:55:49 6F:BA:DD:6D:E8:12 -71 [Info]  | Media control  | VolumeDown
2020/9/21 16:55:49 6F:BA:DD:6D:E8:12 -71 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:56:00 6F:BA:DD:6D:E8:12 -54 [Info]  | Media control  | RestoreVolume
2020/9/21 16:56:00 6F:BA:DD:6D:E8:12 -54 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:56:10 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/21 16:56:18 6F:BA:DD:6D:E8:12 -53 [Info]  | Media control  | VolumeDown
2020/9/21 16:56:18 6F:BA:DD:6D:E8:12 -53 [Info]  |  Print Action  | Unknown   | L:out
2020/9/21 16:56:21 6F:BA:DD:6D:E8:12 -61 [Info]  | Media control  | RestoreVolume
2020/9/21 16:56:21 6F:BA:DD:6D:E8:12 -61 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:57:44 6F:BA:DD:6D:E8:12 -51 [Info]  | Media control  | VolumeDown
2020/9/21 16:57:44 6F:BA:DD:6D:E8:12 -51 [Info]  |  Print Action  | Close     | R:out
2020/9/21 16:59:19 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/21 16:59:22 6F:BA:DD:6D:E8:12 -52 [Info]  | Media control  | RestoreVolume
2020/9/21 16:59:22 6F:BA:DD:6D:E8:12 -52 [Info]  |  Print Action  | Close     | LR:in
2020/9/21 16:59:33 6F:BA:DD:6D:E8:12 -39 [Info]  | Media control  | RestoreVolume and reset state
2020/9/21 16:59:33 6F:BA:DD:6D:E8:12 -39 [Info]  |  Print Action  | Close     | Case:All out
2020/9/21 16:59:37 6F:BA:DD:6D:E8:12 -40 [Info]  |  Print Action  | Open(L)   | Case:R out
2020/9/21 16:59:38 6F:BA:DD:6D:E8:12 -44 [Info]  |   Animation    | Show, case_open False
2020/9/21 16:59:38 6F:BA:DD:6D:E8:12 -44 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/21 16:59:42 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Disconnected (IsAirPodsConnected False)
2020/9/21 16:59:45 ----------------- --- [Info]  |                | force_hide clear
2020/9/21 17:02:35 40:7A:FF:4B:B1:0E -53 [Info]  |   Animation    | Show, case_open False
2020/9/21 17:02:35 40:7A:FF:4B:B1:0E -44 [Info]  |  Print Action  | Unknown   | Case:open
2020/9/21 17:02:35 40:7A:FF:4B:B1:0E -43 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/21 17:02:36 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Connected (IsAirPodsConnected True)
2020/9/21 17:02:40 ----------------- --- [Info]  |                | isAirpodsConnect: Hide 2020/9/21 17:02:36 < 2020/9/21 17:02:43
2020/9/21 17:02:40 6F:BA:DD:6D:E8:12 -49 [Info]  |   MyAirPods    | Founded
2020/9/21 17:02:40 40:7A:FF:4B:B1:0E -56 [Info]  |  Print Action  | Case:Closed [close_ctrl]
2020/9/21 17:02:42 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Disconnected (IsAirPodsConnected False)
2020/9/21 17:02:42 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Connected (IsAirPodsConnected True)
2020/9/21 17:02:44 ----------------- --- [Info]  |                | force_hide clear
2020/9/21 17:02:48 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Disconnected (IsAirPodsConnected False)
2020/9/21 17:02:48 ----------------- --- [Info]  |                | force_hide clear
2020/9/21 17:03:06 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/21 17:21:11 6C:C4:02:BA:B6:A3 -90 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/21 17:36:02 52:97:43:8F:38:75 -93 [Info]  |  Print Action  | Close     | LR:in
2020/9/22 11:03:22 51:19:85:BF:4C:85 -92 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 12:07:07 5A:1C:9B:4F:5D:15 -73 [Info]  |  Print Action  | Unknown   | R:out
2020/9/22 12:07:08 5A:1C:9B:4F:5D:15 -66 [Info]  |  Print Action  | Open close| All out
2020/9/22 12:07:11 5A:1C:9B:4F:5D:15 -60 [Info]  |  Print Action  | Close     | LR:in
2020/9/22 12:22:03 43:25:4F:25:C5:D1 -68 [Info]  |  Print Action  | Close     | LR:in
2020/9/22 12:37:01 55:12:68:27:A6:8C -63 [Info]  |  Print Action  | Close     | LR:in
2020/9/22 12:52:01 42:58:F6:67:7E:AC -59 [Info]  |  Print Action  | Close     | LR:in
2020/9/22 13:06:42 42:58:F6:67:7E:AC -60 [Info]  |  Print Action  | Close     | L:out
2020/9/22 13:06:44 52:6D:0A:2F:16:9A -56 [Info]  |  Print Action  | Open(L)   | Case:R out
2020/9/22 13:06:45 42:58:F6:67:7E:AC -59 [Info]  |  Print Action  | Unknown   | R:in case
2020/9/22 13:06:47 42:58:F6:67:7E:AC -50 [Info]  |  Print Action  | <unknown>04
2020/9/22 13:14:07 78:C5:FE:59:E0:99 -52 [Info]  |   Animation    | Show, case_open False
2020/9/22 13:14:08 78:C5:FE:59:E0:99 -41 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/22 13:14:11 62:46:B6:BE:89:99 -37 [Info]  |   Animation    | Hide, case_open True
2020/9/22 13:14:12 62:46:B6:BE:89:99 -33 [Info]  |  Print Action  | Case:Closed [close_ctrl]
2020/9/22 13:14:19 6E:5E:1A:B0:95:DD -55 [Info]  |  Print Action  | <unknown>04
2020/9/22 13:14:20 78:C5:FE:59:E0:99 -41 [Info]  |  Print Action  | Close(R)  | L:out
2020/9/22 13:14:26 78:C5:FE:59:E0:99 -44 [Info]  |   Animation    | Show, case_open False
2020/9/22 13:14:26 78:C5:FE:59:E0:99 -44 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/22 13:14:33 ----------------- --- [Info]  |                | isAirpodsConnect: Hide 2020/9/22 13:14:30 < 2020/9/22 13:14:36
2020/9/22 13:14:41 5F:70:72:F1:38:2F -46 [Info]  |  Print Action  | Unknown   | R:out
2020/9/22 13:14:43 5F:70:72:F1:38:2F -42 [Info]  |  Print Action  | Open(R)   | L:out
2020/9/22 13:14:46 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 13:14:49 5F:70:72:F1:38:2F -49 [Info]  |  Print Action  | Open(R)   | L:in
2020/9/22 13:14:50 68:3F:94:13:FE:47 -53 [Info]  |  Print Action  | <unknown>35
2020/9/22 13:14:51 5F:70:72:F1:38:2F -52 [Info]  |  Print Action  | Case:Closed [close_ctrl]
2020/9/22 13:14:55 5F:70:72:F1:38:2F -52 [Info]  |  Print Action  | Unknown   | Case:open
2020/9/22 13:14:57 5F:70:72:F1:38:2F -49 [Info]  |  Print Action  | <unknown>04
2020/9/22 13:14:58 68:3F:94:13:FE:47 -52 [Info]  |  Print Action  | Close(R)  | L:out
2020/9/22 13:15:01 5F:70:72:F1:38:2F -36 [Info]  |  Print Action  | Unknown   | Case:open
2020/9/22 13:15:01 5F:70:72:F1:38:2F -36 [Info]  |  Print Action  | Open(R)   | L:out
2020/9/22 13:15:02 68:3F:94:13:FE:47 -62 [Info]  |  Print Action  | Open(R)   | Case:L out
2020/9/22 13:15:07 68:3F:94:13:FE:47 -56 [Info]  |  Print Action  | Close     | Case:All out
2020/9/22 13:15:10 68:3F:94:13:FE:47 -43 [Info]  |  Print Action  | Open(R)   | Case:L out
2020/9/22 13:15:17 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 13:15:37 5F:70:72:F1:38:2F -44 [Info]  |  Print Action  | Open(R)   | L:in
2020/9/22 13:15:38 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 13:15:40 5F:70:72:F1:38:2F -57 [Info]  |  Print Action  | Open(R)   | L:out
2020/9/22 13:15:41 5F:70:72:F1:38:2F -44 [Info]  |  Print Action  | Open(R)   | L:in
2020/9/22 13:15:43 68:3F:94:13:FE:47 -50 [Info]  |  Print Action  | <unknown>35
2020/9/22 13:15:44 5F:70:72:F1:38:2F -41 [Info]  |   Animation    | Show, case_open False
2020/9/22 13:15:44 5F:70:72:F1:38:2F -41 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/22 13:15:48 ----------------- --- [Info]  |                | Connect to Jiahui AirPods model 0220
2020/9/22 13:15:51 5F:70:72:F1:38:2F -41 [Info]  |  Print Action  | Open(R)   | L:out
2020/9/22 13:15:54 68:3F:94:13:FE:47 -41 [Info]  |  Print Action  | Open(R)   | Case:L out
2020/9/22 13:15:55 5F:70:72:F1:38:2F -56 [Info]  |  Print Action  | Open(R)   | L:in
2020/9/22 13:15:58 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Connected (IsAirPodsConnected True)
2020/9/22 13:15:59 40:7A:FF:4B:B1:0E -45 [Info]  |   MyAirPods    | Founded
2020/9/22 13:16:01 ----------------- --- [Info]  |SendConnCommand| Connected
2020/9/22 13:16:06 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 13:16:06 ----------------- --- [Info]  |                | force_hide clear
2020/9/22 13:16:14 5F:70:72:F1:38:2F -46 [Info]  |   MyAirPods    | Founded
2020/9/22 13:16:14 68:3F:94:13:FE:47 -57 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 13:16:24 68:3F:94:13:FE:47 -51 [Info]  |   MyAirPods    | Founded
2020/9/22 13:16:24 68:3F:94:13:FE:47 -54 [Info]  | Media control  | Do Play
2020/9/22 13:16:27 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 13:29:21 55:53:C0:DC:F9:0B -58 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 13:29:35 55:53:C0:DC:F9:0B -57 [Info]  |   MyAirPods    | Founded
2020/9/22 13:44:06 45:D6:50:55:79:B2 -52 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 13:44:14 45:D6:50:55:79:B2 -55 [Info]  |   MyAirPods    | Updated
2020/9/22 13:58:51 65:95:98:F8:B8:2A -53 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 13:58:58 65:95:98:F8:B8:2A -52 [Info]  |   MyAirPods    | Updated
2020/9/22 14:10:32 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 14:13:35 71:CF:90:83:44:F3 -50 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 14:13:38 71:CF:90:83:44:F3 -52 [Info]  |   MyAirPods    | Updated
2020/9/22 14:15:39 ----------------- --- [Info]  |                | cloudmusic vol: 0.1718035
Found process cloudmusic -> 三十岁的女人 - 赵雷(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 14:15:39 71:CF:90:83:44:F3 -50 [Info]  | Media control  | Do Pause
2020/9/22 14:15:39 71:CF:90:83:44:F3 -50 [Info]  |  Print Action  | Close(R)  | L:out
Found process cloudmusic -> 三十岁的女人 - 赵雷(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 14:18:33 71:CF:90:83:44:F3 -52 [Info]  | Media control  | Do Play
2020/9/22 14:18:33 71:CF:90:83:44:F3 -52 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 14:28:23 7D:DB:F6:21:E4:F1 -50 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 14:28:33 7D:DB:F6:21:E4:F1 -56 [Info]  |   MyAirPods    | Founded
2020/9/22 14:42:10 ----------------- --- [Info]  |                | cloudmusic vol: 0.009324311
Found process cloudmusic -> 生日快乐 - 李雪莱(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 14:42:10 7D:DB:F6:21:E4:F1 -53 [Info]  | Media control  | Do Pause
2020/9/22 14:42:10 7D:DB:F6:21:E4:F1 -53 [Info]  |  Print Action  | Close(R)  | L:out
2020/9/22 14:42:13 6C:6A:10:D6:CB:65 -53 [Info]  |  Print Action  | <unknown>04
2020/9/22 14:42:18 7D:DB:F6:21:E4:F1 -59 [Info]  |  Print Action  | <unknown>24
2020/9/22 14:42:54 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Disconnected (IsAirPodsConnected False)
2020/9/22 14:42:54 ----------------- --- [Info]  |                | force_hide clear
2020/9/22 15:10:20 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 15:38:19 74:66:16:05:05:61 -89 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 15:55:06 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Connected (IsAirPodsConnected True)
2020/9/22 15:55:07 7D:DB:F6:21:E4:F1 -51 [Info]  |   MyAirPods    | Founded
2020/9/22 15:55:07 4D:7D:BF:60:CE:96 -59 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 15:55:15 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 15:55:23 4D:7D:BF:60:CE:96 -60 [Info]  |   MyAirPods    | Founded
2020/9/22 15:55:23 4D:7D:BF:60:CE:96 -68 [Info]  | Media control  | Do Play
2020/9/22 16:01:36 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 16:02:07 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 16:07:58 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 16:09:47 7A:B3:66:61:45:8D -65 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 16:10:06 7A:B3:66:61:45:8D -66 [Info]  |   MyAirPods    | Founded
2020/9/22 16:24:34 4A:4E:85:84:C0:46 -59 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 16:24:41 4A:4E:85:84:C0:46 -59 [Info]  |   MyAirPods    | Founded
2020/9/22 16:36:23 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 16:37:21 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 16:39:18 42:E6:33:99:C0:CE -66 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 16:39:29 42:E6:33:99:C0:CE -63 [Info]  |   MyAirPods    | Founded
2020/9/22 16:54:02 54:04:9C:2A:73:60 -74 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 16:54:16 54:04:9C:2A:73:60 -59 [Info]  |   MyAirPods    | Founded
2020/9/22 17:06:41 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 17:08:49 6D:86:F9:6A:4B:AA -63 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 17:08:55 6D:86:F9:6A:4B:AA -58 [Info]  |   MyAirPods    | Founded
2020/9/22 17:14:19 ----------------- --- [Info]  |                | cloudmusic vol: 0.1581528
Found process cloudmusic -> 三十岁的女人 - 赵雷(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 17:14:19 6D:86:F9:6A:4B:AA -53 [Info]  | Media control  | Do Pause
2020/9/22 17:14:19 6D:86:F9:6A:4B:AA -53 [Info]  |  Print Action  | Close(R)  | L:out
Found process cloudmusic -> 三十岁的女人 - 赵雷(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 17:20:18 6D:86:F9:6A:4B:AA -49 [Info]  | Media control  | Do Play
2020/9/22 17:20:18 6D:86:F9:6A:4B:AA -49 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 17:23:32 7A:12:3D:78:48:09 -54 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 17:23:35 7A:12:3D:78:48:09 -55 [Info]  |   MyAirPods    | Updated
2020/9/22 17:33:35 ----------------- --- [Info]  |                | cloudmusic vol: 0.1526825
Found process cloudmusic -> 三十岁的女人 - 赵雷(1844)
Send key ' ' to MiniPlayer -> 迷你播放器
2020/9/22 17:33:35 7A:12:3D:78:48:09 -40 [Info]  | Media control  | Do Pause
2020/9/22 17:33:35 7A:12:3D:78:48:09 -40 [Info]  |  Print Action  | Close(R)  | L:out
2020/9/22 17:33:38 7A:12:3D:78:48:09 -63 [Info]  |  Print Action  | <unknown>24
2020/9/22 17:33:38 7A:12:3D:78:48:09 -50 [Info]  |  Print Action  | Case:Closed [close_ctrl]
2020/9/22 17:33:42 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Disconnected (IsAirPodsConnected False)
2020/9/22 17:33:42 ----------------- --- [Info]  |                | force_hide clear
2020/9/22 17:49:39 68:E9:79:2B:75:A7 -52 [Info]  |   Animation    | Show, case_open False
2020/9/22 17:49:40 68:E9:79:2B:75:A7 -57 [Info]  |  Print Action  | Open(RL)  | Case:open
2020/9/22 17:49:41 74:9E:AF:E4:DA:9F --- [Info]  |ConnectionStatus| AirPods Connected (IsAirPodsConnected True)
2020/9/22 17:49:44 ----------------- --- [Info]  |                | isAirpodsConnect: Hide 2020/9/22 17:49:40 < 2020/9/22 17:49:47
2020/9/22 17:49:47 7A:12:3D:78:48:09 -49 [Info]  |   MyAirPods    | Founded
2020/9/22 17:49:47 68:E9:79:2B:75:A7 -65 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 17:50:32 68:E9:79:2B:75:A7 -64 [Info]  |   MyAirPods    | Founded
2020/9/22 17:50:32 68:E9:79:2B:75:A7 -60 [Info]  | Media control  | Do Play
2020/9/22 17:50:35 ----------------- --- [Info]  |                | Connection to UWP lost
2020/9/22 18:03:19 71:F5:91:90:BE:21 -53 [Info]  |  Print Action  | Close(R)  | L: in
2020/9/22 18:03:30 71:F5:91:90:BE:21 -54 [Info]  |   MyAirPods    | Founded

**Comment by aaaaahua** [comment]
> Hi. Have you tried without the MagicPods? Can you attach a log file?

it's normal without the MagicPods.

**Comment by steam3d** [comment]
You can set Ear Detection to None and try again. What is your value here?
![image](https://user-images.githubusercontent.com/30986874/93869649-c107c680-fcd4-11ea-8066-de2c9948a483.png)

**Comment by aaaaahua** [comment]
> You can set Ear Detection to None and try again. What is your value here?
> ![image](https://user-images.githubusercontent.com/30986874/93869649-c107c680-fcd4-11ea-8066-de2c9948a483.png)

ok,i'll try.  
only  play/pause .

**Comment by aaaaahua** [comment]
But I just tried it again and it  seems to be working.
Thanks for your answer~
