### ISSUE TITLE
Airpods Max won't fully connect.

### ISSUE THREAD

**Issue by jpakele** [steam3d/MagicPods-Windows#300]
I can see that MagicPods finds my Airpods Max and even reports back on the current battery. But on the Airpods side, it doesn't make the "connection found" sound like a connection was actually established. And after about 2 seconds, the MagicPods app loses the connection. I'm attaching the logs just in case their needed.
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10611693/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10611694/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Hi. The MagicPods works as expected. The Windows controls maintaining a connection with the headphones. That's means it is not problem related to MagicPods.

**Comment by steam3d** [comment]
You could try to repair AirPods Max or reboot them

**Comment by jpakele** [comment]
Thank you.
