### ISSUE TITLE
Headphones tab not loading

### ISSUE THREAD

**Issue by Teodorz97** [steam3d/MagicPods-Windows#303]
The headphones tab keeps loading forever. Tried to reinstall the app, but it didn't fix the issue.

**Comment by Teodorz97** [comment]
![image](https://user-images.githubusercontent.com/100035344/217801674-3a8f9d8f-5296-4667-9a1d-a8c295f81b5b.png)

**Comment by steam3d** [comment]
Hi. Do you have MagicPodsService.exe process in task manager?

Upload log files:
Win+r past this string and press enter
`%LOCALAPPDATA%\Packages\715AleksandrMaslov.MagicPods_vk1h99z2mpttm\TempState`

Do you try to reboot PC?

**Comment by Teodorz97** [comment]
Hi, there's MagicPodsService.exe running, however I can see some errors in the MagicPodsUILog.

[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10696988/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10696989/MagicPodsServiceLog.txt)
![image](https://user-images.githubusercontent.com/100035344/217811403-aae9eae1-ee8a-4a7d-a80f-227ebb0bd64a.png)

**Comment by Teodorz97** [comment]
The app was ran only once, because I tried reinstalling it, however the issue got fixed by itself after some time. Thanks for the responses.
