### ISSUE TITLE
Automatic stream audio from iPhone.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#304]
Hey,
Sometimes I forget to auto stream audio from iPhone.
I want to have an option to automatically stream audio from iPhone without the need to press the stream audio button.

**Comment by steam3d** [comment]
Hi. This is not possible. In 70% cases you will get connection error.  I do not know the reason why it happens like this. I also tested with large delay like 60 second after connect AirPods.
