### ISSUE TITLE
Random disconnection

### ISSUE THREAD

**Issue by geaty3** [steam3d/MagicPods-Windows#305]
Hi, thanks for the great app.
My Airpods Pro 2 keeps disconnecting randomly on Win11, every few hours on average.
It was already happening before using this app so this app is not the cause.
Do you have any idea what the problem is?

**Comment by steam3d** [comment]
Well, I don't know. I know that it is a very popular issue.
I could only suggest base solutions:
1. Try to disable the AirPods Pro 2 options on iPhone, like switch between devices and locator (or location, I am not sure what the right name)
2. Update AirPods Pro 2 to the latest firmware
3. Try to reset AirPods Pro 2

**Comment by steam3d** [comment]
No feeback
