### ISSUE TITLE
Не видит bluetooth adapter Comfast CF-B01

### ISSUE THREAD

**Issue by Bis-65** [steam3d/MagicPods-Windows#306]
Bluetooth adapter подключен , звук на Airpods 2 есть , а в программе сообщение "Bluetooth adapter не найден".

**Comment by steam3d** [comment]
Добрый день. Загрузите лог файлы. Их можно найти на вкладке поддержка

**Comment by Bis-65** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10746654/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10746655/MagicPodsUILog.txt)

**Comment by Bis-65** [comment]
Bluetooth почему-то находится в USB контроллерах.
![Bluetooth](https://user-images.githubusercontent.com/106326181/219133973-18889dcf-33f2-4281-9f66-cfcf866e0b9b.jpg)

**Comment by steam3d** [comment]
По этому собственно приложение и не находит, так как для Windows - это не Bluetooth адаптер.

**Comment by Bis-65** [comment]
Значит с этим адаптером работать не будет?

**Comment by steam3d** [comment]
Да, я при всем желании не смогу сделать. Потому что для меня это прсто USB устройство, я никак не могу определать что оно делает, а уж темболее как с ним взаимодействовать.

У меня есть внешний Bluetooth адаптер - `Asus usb bt-500`. Я его использую для тестов, он отображается в системе как Bluetooth устройство.

Возможно новый Bluetooth драйвер правильно ингерирует BRLINK в систему.
