### ISSUE TITLE
Startup disabled by group policy, or not supported by this device.

### ISSUE THREAD

**Issue by 1womp** [steam3d/MagicPods-Windows#308]
I click on the enable startup button but nothing happens, ive also tried to enable startup through task manager but it auto disables.

**Comment by steam3d** [comment]
Hi. Looks like Startup apps disabled. I never happened with this, but I googled this:
https://sourcedaddy.com/windows-7/how-to-disable-startup-applications-configured-using-group-policy-or-logon-scripts.html

I think for windows 10 or 11 it is the same setting
