### ISSUE TITLE
Connect problem with AirPodspro2（5B58）

### ISSUE THREAD

**Issue by Koinega** [steam3d/MagicPods-Windows#309]
When i use it after 5 minutes，the sound become like glich music until i reconnected it. I even have tried reinstall the operating system,but it not change:(

**Comment by steam3d** [comment]
HI. Does it happen when you close MagicPods?

**Comment by Koinega** [comment]
> 
No

**Comment by steam3d** [comment]
Well, it means that your Bluetooth adapter does not support BLE and Classic Bluetooth connection at the same time.

I could not affect on it.
