### ISSUE TITLE
I can't install, please help me, please

### ISSUE THREAD

**Issue by lyplft** [steam3d/MagicPods-Windows#31]
I have already purchased. But I have no way to download. I use the win10 LTSC version. Try to install the store, but the store can only buy it but not download it. Could you help me in any way，please 。

**Comment by steam3d** [comment]
Hi. You can install only from Microsoft Store another way not available.

You can try to enable Microsoft Store in Windows LTSC.

**Comment by lyplft** [comment]
> 
> 
> Hi. You can install only from Microsoft Store another way not available.
> 
> You can try to enable Microsoft Store in Windows LTSC.

I tried it. But it keeps downloading, I can’t download anything from the store

**Comment by lyplft** [comment]
> 
> 
> Hi. You can install only from Microsoft Store another way not available.
> 
> You can try to enable Microsoft Store in Windows LTSC.

I installed the program, but after opening it, there is no response. There is only one window with the airpods icon in the middle and a blue background.

**Comment by steam3d** [comment]
> I installed the program, but after opening it, there is no response. There is only one window with the airpods icon in the middle and a blue background.

I think it because you use LTSC. Maybe some modules or something else missing in the system.  The app was designed to regular windows.

**Comment by steam3d** [comment]
No feedback provided.

**Comment by wonsuc** [comment]
> Hi. You can install only from Microsoft Store another way not available.
> 
> You can try to enable Microsoft Store in Windows LTSC.

My workplace blocked Microsoft Store downloads. I hope there's `exe` way to install this app.

**Comment by steam3d** [comment]
> My workplace blocked Microsoft Store downloads. I hope there's exe way to install this app.
I am sorry, but there is only one way to install MagicPods. Moreover, Microsoft is actively promoting its store and provides all the tools for distributing the application.
