### ISSUE TITLE
Пропадает отображение заряда 

### ISSUE THREAD

**Issue by ArtSiB** [steam3d/MagicPods-Windows#310]
При подключении airpods pro 2 периодически пропадает отображение заряда одного из наушников и кейса.

**Comment by steam3d** [comment]
Добрый день. Со временем обо наушника появятся. AirPods обмениваются дополнительными данными, когда наушник вынимается и вставляется в ухо.

Заряд кейса отображается только когда один из наушников находится в кейсе и кейс открыт.
