### ISSUE TITLE
AirPods pro 2 some magicpods settings is missing.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#312]
Hey,
I have airpods pro 2 and airpods pro 1 
on magicpods some settings are missing check the [attached photo](https://imgur.com/c9dxvYp): https://imgur.com/c9dxvYp
![image](https://user-images.githubusercontent.com/119108387/220580027-4191b030-7d3a-4ed3-937c-29c97651a4ee.png)

**Comment by steam3d** [comment]
Hi. Nothing is missing. Check https://help.magicpods.app/fun-capability/

**Comment by bigplayer-ai** [comment]
> Hi. Nothing is missing. Check https://help.magicpods.app/fun-capability/

There is an option when I disconnect my Air Pods to change to other audio device.

**Comment by bigplayer-ai** [comment]
And may I ask why the other features are not supported on air pods pro-2?
Best Regards,

**Comment by steam3d** [comment]
Apple detects when you use AirPods on none Apple device and disable features
