### ISSUE TITLE
Why do you recommend enabling handsfree telephony service on AirPods?

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#314]
Hey, 
I read all of your wikis. Thank you for investing the time to write this clear guide -BTW, it does not sound like an indie developer guide:3-
I just wanted to know why you recommend turning on hands-free telephony for AirPods.
In both of these articles, you mentioned this:
1) https://help.magicpods.app/issue-connectivity/#:~:text=Enable%20all%20checkboxes%20on%20this%20tab
![Hands-free Recommendation.](https://user-images.githubusercontent.com/119108387/220585206-679a1266-3da1-4afd-a0af-d2bf9dc15247.png)

2) https://help.magicpods.app/headphones-show-battery-percentage/#:~:text=Select%20your%20headphones%20and%20check%20the%20Handsfree%20Telephony%20turned%20on.
![Hands-free Recommendation #2.](https://user-images.githubusercontent.com/119108387/220585132-302e2c41-cfb7-44ed-bc78-b6270a38e647.png)

Turning on hands-free telephony makes my AirPods sound chunky and low quality. So I was wondering why I should enable this and if you have another workaround to fix the bad audio quality when using the hands-free telephony (I don't use the AirPods mic at all).

**Comment by steam3d** [comment]
For most ordinary users (not advanced Windows users) these are the optimal settings, users will not have a question why the microphone does not work, etc.
