### ISSUE TITLE
a problem with the display of connection status in the status bar

### ISSUE THREAD

**Issue by Jarvis2333** [steam3d/MagicPods-Windows#315]
![image](https://user-images.githubusercontent.com/114388117/221363052-f5743bb0-5663-4587-b6b7-fdb117971ecc.png)

you can see the problem with the display of the connect state. my airpods are connected,but the state bar display a disconnected state. on the contrary, the state of the other disconneted earphone is "connected". i dont know whether it is a translation problem?

**Comment by steam3d** [comment]
1-2 headphones English text is "Connect"
3 headphone English text is "Disconnect"

The community works on translation. I do not know Chinese, so if you know it you can fix translation on weblate.magicpods.app

**Comment by Jarvis2333** [comment]
but actually the state of 1-2 headphones are disconnected. and the 3 headphone is connected. the display of the state is reversed.
do you notice the small blue point in front of the 3 headphone? i guess it shows its connected state.

**Comment by steam3d** [comment]
Yes. The small dot shows the current state of headphones or any functions (like  VoiceOver).
Text on each item of context menu describes not state. It describes action that will happen when the user clicks on this item. If you check Windows Bluetooth setting, you will see that it displays state as reversed also.

**Comment by Jarvis2333** [comment]
oh，maybe i know where the problem is. the button describe the action that will happen when i click it. but the  chinese words "已连接" means that it has been connected.  if you wanna decribe an action which will happen when user click,  "连接" is a better expression.  Similarly, "断开" instead of "已断开".  A friendly propotion~

**Comment by steam3d** [comment]
Could you make a suggestion or edit (if you registered) this spell?

[Edit text connect](https://weblate.magicpods.app/translate/magicpods-windows/magicpodsservice/zh_Hans/?sort_by=-priority%2Cposition&offset=9)

[Edit text disconnect](https://weblate.magicpods.app/translate/magicpods-windows/magicpodsservice/zh_Hans/?sort_by=-priority%2Cposition&offset=10)

**Comment by Jarvis2333** [comment]
Of course, i'm so glad to join the develoment of this software. It  has excellent design and graceful interface. If it keep improving, I will recommend it to more friends around me. By the way, i has submited the recommend, but im not sure if it has been submit successfully,cause it's my first time to try thing like this. Finally, thanks for your sincere attitude!
