### ISSUE TITLE
Please add this option to convert bookmarks into subtitles. 

### ISSUE THREAD

**Issue by motealle** [steam3d/MagicPods-Windows#316]
It may be implemented like this:

- adding an option in H menu to [Create srt, subtitle file from bookmarks] or: [Export as srt file] (every bookmark may be fixed on screen until the next bookmark appears, or duration of appearance may be adjustable for every bookmark, which will be taken from the user via a dialog box )

**Comment by steam3d** [comment]
Hi. I am not sure that you write in right place.  The MagicPods is software for Bluetooth headphones not text editor.
