### ISSUE TITLE
[Feature Request] Start magic pods at login instead of the system startup.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#317]
[Feature Request] Start magic pods at login instead of the system startup
Hey,
Sometimes, Magic Pods does not open after restarting windows after an update or some edge cases.
The fix for this problem is to add Start magic pods at login instead of system startup. When you log in → the system is a start-up when the system is a start-up -/> Does not mean you log in.

**Comment by steam3d** [comment]
Windows starts all apps in startup list after log-in. It is default behavior. This feature already made.

**Comment by bigplayer-ai** [comment]
Once you logout of a specific user and login to the other user. The application does not start. That’s why task scheduler have At-logon, and system startup as a different options. Sent from Mail for Windows From: Alexander MaslovSent: Thursday, 2 March 2023 23:25To: steam3d/MagicPods-WindowsCc: bigplayer-ai; AuthorSubject: Re: [steam3d/MagicPods-Windows] [Feature Request] Start magic pods at login instead of the system startup. (Issue #317) Windows starts all apps in startup list after log-in. It is default behavior. This feature already made.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by steam3d** [comment]
Here is the video. It work absoluty the same as you describe. (It's virtual machine so it has graphic bugs and very slow, but anyway)

https://user-images.githubusercontent.com/30986874/222650501-226cef44-386a-46ea-b806-bf3bd77ff1a4.mp4

**Comment by bigplayer-ai** [comment]
This is strange:O That's the first time I've heard that.
In task scheduler windows, I believed the distinction between run at any user log-on and run at start-up was t**hat run at any user log-on means the task will run whenever any user signs on to the computer**, whereas **run at start-up indicates the process will run just when the computer boots up.**

**Comment by steam3d** [comment]
Maybe it just a naming problem. The Microsoft doc says it is a startup task.

I am not as good as Windows administrator, but what you described sounds like " Windows service."

Services start at during Windows loading and work always while PC turned on. All users can access services.

The MagicPods is ordinary application. So it can't has such behavior.

**Comment by bigplayer-ai** [comment]
good to know.
Keep up the good work @steam3d.
Your application is mentioned in big articles/magazines.

**Comment by bigplayer-ai** [comment]
Hey,
I’m having hard time trying to make magicpods start at system startup properly (as this is microsoft store application).
Sometimes it launches and sometimes it does not.
Do you have any ideas how can I fix this issue?
Best regards,

**Comment by bigplayer-ai** [comment]
I tried repairing Abe reinstalling magic pods

**Comment by steam3d** [comment]
Maybe it crashes on startup. But I am not sure because I use the MagicPods pods each day more than 3 years and I got 2-3 crashes at startup.

**Comment by bigplayer-ai** [comment]
I think I fixed the issue. I just restarted my device 3 times, And MagicPods launched everytime.
It was regestiry fix:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize]
"StartupDelayInMSec"=dword:00000000
```

**Comment by steam3d** [comment]
Thanks I will add it to help.magicpods.app
