### ISSUE TITLE
Не могу подключить airpods 3

### ISSUE THREAD

**Issue by that-corych** [steam3d/MagicPods-Windows#318]
![image](https://user-images.githubusercontent.com/56929051/223225925-a8cbccb7-1a15-4b02-9f01-237aff0b3f32.png)
### 
**Пробовал все способы.**

**Comment by that-corych** [comment]
![image](https://user-images.githubusercontent.com/56929051/223226944-c0e08eb1-ed7f-41c0-913e-d0052932a731.png)

**Comment by steam3d** [comment]
Добрый день. Прикрепите лог файлы, их можно найти на странице поддержки

**Comment by steam3d** [comment]
Если судить по логам, то приложение работает штато и просто висит в бесконечно ожидании данных. Проблема где то между Windows и Bluetooth, возможно в каких то политиках системы.  Обычно причиной этого бывает Bluetooth драйвер или не совместимость Bluetooth адаптера. (Так же приложение не поддерживает Fake AirPods).

Вы используете какие нибудь твики системы или что-то такое? У меня около 10 разных систем, все установлены с официального образа и у меня никогда не получалось воспроизвести проблему

**Comment by that-corych** [comment]
Система стандартная, блютуз через адаптер TP-Link UB400.
![image](https://user-images.githubusercontent.com/56929051/223377207-b5620616-9706-4afc-9d53-ccb2d0acdc79.png)
Драйвер последний

**Comment by that-corych** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/10908547/log.txt)

**Comment by steam3d** [comment]
Скорее всего не поддерживается адаптер. Вот спецификация вашего адаптера:

| Name                                   | Value |
| -------------------------------------- | ----- |
| AreClassicSecureConnectionsSupported   | False |
| AreLowEnergySecureConnectionsSupported | True  |
| IsAdvertisementOffloadSupported        | False |
| IsCentralRoleSupported                 | True  |
| IsClassicSupported                     | True  |
| IsExtendedAdvertisingSupported         | False |
| IsLowEnergySupported                   | True  |
| IsPeripheralRoleSupported              | False |
| MaxAdvertisementDataLength             | 31    | 

А вот как выглядит мой адаптер:


| Name                                   | Value |
| -------------------------------------- | ----- |
| AreClassicSecureConnectionsSupported   | True  |
| AreLowEnergySecureConnectionsSupported | True  |
| IsAdvertisementOffloadSupported        | True  |
| IsCentralRoleSupported                 | True  |
| IsClassicSupported                     | True  |
| IsExtendedAdvertisingSupported         | True  |
| IsLowEnergySupported                   | True  |
| IsPeripheralRoleSupported              | True  |
| MaxAdvertisementDataLength             | 160 |
