### ISSUE TITLE
Keine Verbindung zu Airpods

### ISSUE THREAD

**Issue by Philip265** [steam3d/MagicPods-Windows#319]
Hallo,
ich bekomme keine Verbindung mehr zu meinen Airpods.
Das Icon verschwindet auch immer wieder aus der Startleiste

Ich kann keinen Zusammenhang zu etwas neuem bzw.  geändertem herstellen.

Gruß

**Comment by steam3d** [comment]
Hi. What language do use in MagicPods? Did you update the MagicPods recently?

**Comment by Philip265** [comment]
Hi,
i use the  MagicPods in german.
I don't find to update the magicpods

Freundliche Grüße
Philip Boer

+49 69 758077-87157
+49 172 7499502

**Comment by steam3d** [comment]
Could you manually upload log files? 

Press Win+R and past this
` %LOCALAPPDATA%\Packages\715AleksandrMaslov.MagicPods_vk1h99z2mpttm\TempState`
then press enter

Drag&drop log files in comment input.

**Comment by Philip265** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10977391/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10977393/MagicPodsUILog.txt)

**Comment by Philip265** [comment]
the problem ist solved

**Comment by steam3d** [comment]
The MagicPods says that you ProBeat does not have any sound outs. Does this ProBeat works?

**Comment by steam3d** [comment]
If you resolved issue can you describe solution? It will be helpful for users.

**Comment by Philip265** [comment]
The probeats are not mine. Maybe from a College


Freundliche Grüße
Philip Boer

+49 69 758077-87157
+49 172 7499502

**Comment by Philip265** [comment]
I switch bluetooth off and on (laptop) than its works

Freundliche Grüße
Philip Boer

+49 69 758077-87157
+49 172 7499502

**Comment by Philip265** [comment]
It doesn't work anymore all ready with microsoft
Magicpods is configurat in the startmenu
First I must always connect manuell with Bluetooth in the microsoft settings.




Freundliche Grüße
Philip Boer

+49 69 758077-87157
+49 172 7499502

**Comment by Philip265** [comment]
done

Freundliche Grüße
Philip Boer

+49 69 758077-87157
+49 172 7499502
