### ISSUE TITLE
feature request for potplayer

### ISSUE THREAD

**Issue by offlineface** [steam3d/MagicPods-Windows#32]
Please add playback pause for potplayer, the most famous video player

**Comment by steam3d** [comment]
This media player doesn't react on commands from other program. There is no way to add a player now.

**Comment by steam3d** [comment]
I made research, the potplayer does not react on any keys when it works on background. So there is no way to add it.

**Comment by RainEggplant** [comment]
> 
> 
> I made research, the potplayer does not react on any keys when it works on background. So there is no way to add it.

@steam3d There is a "Turn on global media control keys" option under "General > Keyboard > Support Multimedia Keyboard". After I turned this on, I was able to pause PotPlayer using my airpods' button or the media key on my keyboard when it's in the background. Not sure this would help.
