### ISSUE TITLE
Apple has restricted AirPods Pro 2 to work on non-Apple devices?

### ISSUE THREAD

**Issue by TheConfax** [steam3d/MagicPods-Windows#320]
In the documentation, I see that you wrote in a box: "Apple has restricted AirPods Pro 2 to work on non-Apple devices".
Can you provide more (even technical) information about that? I would like to understand the limitations further.

**Comment by steam3d** [comment]
Hi. You can read this [issue](https://github.com/steam3d/MagicPods-Windows/issues/246)

**Comment by steam3d** [comment]
You can ask additional info there. I closed because it is duplicate
