### ISSUE TITLE
audio delays/sleeps

### ISSUE THREAD

**Issue by clintcfavor** [steam3d/MagicPods-Windows#322]
Hi, after being idle for some time and you get back and play your video/music, it has a 5-10 second delay before you hear the audio back. 

Is this a bug?

**Comment by steam3d** [comment]
Hi. MagicPods is just searching your AirPods. If no one use AirPods around you enable "Fast search" it should reduce delay. You can also change "Search radius" to -75. 

Note. Apple does no allow to detect their AirPods so when some one around use AirPods the MagicPods may think that it's yours.
