### ISSUE TITLE
Airpod max not autopausing

### ISSUE THREAD

**Issue by twofacedfrog** [steam3d/MagicPods-Windows#323]
Great app and no complaints other than this;

Whenever I remove my airpods max from my head, they just don't pause. I have tried most troubleshooting techniques. From simple restarting all the way to uninstalling and reinstalling the app but nothing. 

Anybody else experiencing this problem or just me?

![image](https://user-images.githubusercontent.com/57505216/227044484-1475f069-cfc6-4131-a4a2-a4501fa87716.png)

**Comment by steam3d** [comment]
Hi. Upload the log files from Support page of MagicPods. Does auto switch audio endpoint work?

**Comment by twofacedfrog** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11068894/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/11068895/MagicPodsUILog.txt)

Hiya, thanks for the response. Here is the UILog and the Service log (My Airpods Max are named 'Generic Device #8'). Yes, auto switch audio endpoint does work. And I'd hope they are original, seen as the serial number is registered to Apple, as well as IOS 16 updating them and reporting them as genuine.

**Comment by steam3d** [comment]
Well, Ear Detection works as expected, because "auto switch audio endpoint" also works so maybe problem somewhere else.

Does music pause if you use app that support Windows Media Control Center?
![image](https://user-images.githubusercontent.com/30986874/227729363-f413fba7-f614-47b2-b10e-c2624422fa16.png)

**Comment by twofacedfrog** [comment]
On further inspection it seems auto switch audio endpoint does not work either, only working if I manually disconnect the headphones or if they sit motionless. I must've assumed otherwise, terribly sorry. As for an app using media control center, neither Spotify nor Google Chrome pause.

**Comment by steam3d** [comment]
Do you have enabled Ear Detection on iPhone?
 Which firmware version of AirPods Max?
 Did you rename AirPods Max to `Generic Device #8` name? (Name looks strange. If you specified the name by yourself that everything fine).

The log showed nothing usable.  Let's try to check what's data AirPods Max send to PC:

1. Go to support page.
2. Click five more time on MagicPods logo until page refresh.
3. Go to General settings page.
4. Scroll down and switch log level to trace.
5. Restart application.
6. Connect AirPods Max and try multiple times wear and unwear AirPods Max (Not too fast)
6. Uploaded again log files here again

**Comment by twofacedfrog** [comment]
I do have ear detection on iPhone.
Firmware 5B59.
I did indeed rename them myself.

All steps taken, log files attached.
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/11069539/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11069540/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
I found issue. Your AirPods Max send other data. The main problem for now if I fix ear detection for you then it will break ear detection for others. 

I will return when I find good solution

https://github.com/steam3d/MagicPods-Windows/issues/155

**Comment by steam3d** [comment]
Does popup animation work correct?

**Comment by twofacedfrog** [comment]
I see, thats interesting. I wonder why its sending other data to the device.

Yes the popups work correctly, every time the pop up appears.

**Comment by steam3d** [comment]
> I see, thats interesting. I wonder why its sending other data to the device.

Maybe some settings effect or something else. You could read #155 issue, it has similar issue

**Comment by twofacedfrog** [comment]
I will be sure to have a read. Thank you very much for your help, and keep me posted, I'll be interested to hear why it does it!

**Comment by steam3d** [comment]
Could I ask you to use AirPods Max during the day with MagicPods and send log? (Log level must be trace)
I do not rush you, you can collect the logs when it is convenient for you. I just want to get more info to be sure how to fix it and break nothing.

**Comment by twofacedfrog** [comment]
Yeah of course, I will collect it as soon as possible and reply to this close to or at the end of the day.

**Comment by steam3d** [comment]
![image](https://user-images.githubusercontent.com/30986874/227764772-180d338d-06d8-4a59-bc7b-c3887b525540.png)


Could you try this test app. It must show when you wear and not wear AirPods Max.
Does it work correct or reversed?

[AirPodsMaxEarDetectionTest.zip](https://github.com/steam3d/MagicPods-Windows/files/11071099/AirPodsMaxEarDetectionTest.zip)

**Comment by twofacedfrog** [comment]
The app works correctly, it is reporting wearing and not wearing correctly. I am in the process of creating the log during the duration of today.

When not wearing:
![image](https://user-images.githubusercontent.com/57505216/227773771-b11da9d7-ab0a-49d6-903b-fb93aebe9d58.png)
When wearing:
![image](https://user-images.githubusercontent.com/57505216/227773805-af4d1009-ee69-47ae-8034-e8d3da2f1582.png)

**Comment by steam3d** [comment]
Well. Looks like I must hard-code values. Okay I will think what to do and return with addition information.

**Comment by twofacedfrog** [comment]
Thank you very much, what you are doing is very kind of you.

**Comment by steam3d** [comment]
Request updates in Microsoft Store. I released MagicPods 2.0.49.0 it should fix issue

**Comment by steam3d** [comment]
No. I simple am closing issue. I am glad that everything works now.
