### ISSUE TITLE
App crashes after trying to connect airpods pro 2

### ISSUE THREAD

**Issue by Dennisgmt** [steam3d/MagicPods-Windows#324]
Hello, 

the app lost its function completely after installing my Windows 10 newly. 
When I am trying to pair them with the Magicpods app the app immediately crashes. 

It would be great if you could fix that issue :)
Attached you find my Service log. 
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11056173/MagicPodsServiceLog.txt)

Best regards
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11056179/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Hi. Can you record additional logs?

1. Go to support page.
3. Click five more time on MagicPods logo until page refresh.
4. Go to General settings page.
5. Scroll down and switch log level to debug.
6. Restart application and repeat action to crush the MagicPods.
7. Uploaded again log files here

Did you try reinstall MagicPods maybe after update something broken?

**Comment by Dennisgmt** [comment]
Thank you for your fast reply :), 

I hope the following log helps and that I did it right. 
I reinstalled the App multiple times, the Windows 10 Version is completely fresh installed so I dont know why it should crash out of nowhere.. 
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11056465/MagicPodsServiceLog.txt)

Thank you for your help, I really enjoyed using your App so far (until it did that) 

Best regards

**Comment by steam3d** [comment]
Well, the MagicPods does not throw an error or something. Did the app crash when animation is showing or when?

If you get a crash during animation, you can try disable animation windows and check. 

Also, we can check your Event Viewer.
Open the start menu and type **Event Viewer**. To simplify the process, I recommend you run MagicPods and connect AirPods. After MagicPods crashed, you need to remember the time. It will help you find an error message.

1. Choose Application item
2. Found error message by remembered time and error label
3. Inside description of error, you need to find any words like Magic, MagicPods, MagicPodsUI, and MagicPodsService. 
4. Take a screenshoot and copy the description of the error here.

![image](https://user-images.githubusercontent.com/30986874/227437753-3bb4fab9-5f44-49ec-8bf3-2f85a2cf29ce.png)


I see that the app worked on 21 March, so what happened after?

**Comment by Dennisgmt** [comment]
I just took a screen recording for you to see the error occurring. 
Also I checked the Event Viewer saying the following: 
![image](https://user-images.githubusercontent.com/93389177/227490469-2d7a91af-953a-40ed-a0bf-987f33b0a0c8.png)
Or as text: 

Protokollname: Application
Quelle:        Application Error
Datum:         24.03.2023 10:54:19
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:    
Beschreibung:
Name der fehlerhaften Anwendung: MagicPodsService.exe, Version: 0.0.0.3, Zeitstempel: 0x96b4c555
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2728, Zeitstempel: 0xe7e53a4e
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0xa5c
Startzeit der fehlerhaften Anwendung: 0x01d95e369867047e
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\715AleksandrMaslov.MagicPods_2.0.45.0_x64__vk1h99z2mpttm\MagicPodsService\MagicPodsService.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: cf9f0ad8-bedc-4ae3-9bfe-810bf2a940a9
Vollständiger Name des fehlerhaften Pakets: 715AleksandrMaslov.MagicPods_2.0.45.0_x64__vk1h99z2mpttm
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-24T09:54:19.0487068Z" />
    <EventRecordID>2701</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DennisM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>MagicPodsService.exe</Data>
    <Data>0.0.0.3</Data>
    <Data>96b4c555</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.2728</Data>
    <Data>e7e53a4e</Data>
    <Data>e0434352</Data>
    <Data>000000000002cd29</Data>
    <Data>a5c</Data>
    <Data>01d95e369867047e</Data>
    <Data>C:\Program Files\WindowsApps\715AleksandrMaslov.MagicPods_2.0.45.0_x64__vk1h99z2mpttm\MagicPodsService\MagicPodsService.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>cf9f0ad8-bedc-4ae3-9bfe-810bf2a940a9</Data>
    <Data>715AleksandrMaslov.MagicPods_2.0.45.0_x64__vk1h99z2mpttm</Data>
    <Data>App</Data>
  </EventData>
</Event>

Video is attached:


https://user-images.githubusercontent.com/93389177/227490691-b0e35501-da2c-4e29-9647-3522cdef52e6.mp4

Also I wouldnt know if it worked on 21.03.2023. I installed my windows new and since then it didnt work at all. 
So since the old windows has been deleted it couldn't show old times when it would work

**Comment by Dennisgmt** [comment]
Didnt want to close the issue sorry*

**Comment by steam3d** [comment]
### 1.
Do you have  Windows 10 22H2 (Build 19045)?

How to check Windows version:
1. Press Win+R
2. Type and press enter: `winver`

I could try to install your Windows version with you German language as default and try myself.

### 2

Your log files show that MagicPods worked on 21 March and successful got AirPods battery level. Your Event Viewer did not show error uninformantly.

### 3
Does MagicPods work when AirPods already connected? (When you do not click connect button)

### 4

Maybe check system files could help, You could try this:
https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca

**Comment by Dennisgmt** [comment]
1. 
Yes, I have Windows 10 Version 22H2 (Build 19045.2728)
3. 
Yes, MagicPods does work when I connect the airpods manually, atleast it shows the battery status correctly.
When I try to connect them with MagicPods it crashes as you already saw. 
4. 
The system file checker seemingly found some corrupted files and restored them. 
I will restart my system and try using the app again and will keep you updated if it works now.

**Comment by Dennisgmt** [comment]
Update: Still doesn't work

**Comment by steam3d** [comment]
Well. At least I can try to narrow down the problem. Open MagicPods on General Page (Developer mode must be enabled as we have done before). Scroll down and enable `Use legacy connection` and try to connect AirPods using MagicPods. Does MagicPods crash?

Note. I think disconnect will not work because in first version of MagicPods disconnection was no available.

**Comment by Dennisgmt** [comment]
I tried it with the legacy connection but it also crashes.. 
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11061420/MagicPodsServiceLog.txt)
Maybe the log shows something now?

**Comment by Dennisgmt** [comment]
*

**Comment by steam3d** [comment]
Unfortunately the log does not help. I installed Windows 10, because it is connect issue (when you click connect button) does not matter which headphones to connect.

Here is demo that everything works:

https://user-images.githubusercontent.com/30986874/227513279-7f5affe5-ea70-4acc-9434-0914a5301b71.mp4

But I have one idea, your Event Viewer error said than problem in module KERNELBASE.dll (C:\Windows\System32\KERNELBASE.dll)

What if you upload it here and I will replace my KERNELBASE.dll and try to connect headphones.

**Comment by Dennisgmt** [comment]
Yes maybe we can try that, thank you a lot for all your effort :) 
[KernelBase.zip](https://github.com/steam3d/MagicPods-Windows/files/11062542/KernelBase.zip)

**Comment by steam3d** [comment]
Everything works. I suppose something wrong with system.  Because similar issue found [here](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/issues/47)

You already have the latest version of MagicPods. So if MagicPods worked before it must work and now. No any changes were made.

For now I have no idea what to do. Looks like I tried everything. I also tested on my several PCs and could not reproduce it.

The main think that worries me it's that MagicPods worked on March 21, so what could changed in Windows to broke MagicPods

**Comment by steam3d** [comment]
I can add only that Windows collect a lot of information about paired headphones, so sometimes helps to remove and pair headphones again. I am not sure that it's your case, but who knows

**Comment by Dennisgmt** [comment]
I will try resetting the Airpods on my phone and name them differently, then pairing them again. 
Maybe that will help somehow

**Comment by Dennisgmt** [comment]
Oh Wow, it did work by just resetting the Airpods pro and pairing them with a different name. 
Sorry for taking your time, should have done that earlier

**Comment by steam3d** [comment]
I am glad that problem fixed. I will write down your experience and maybe for someone it also can help.
