### ISSUE TITLE
Бесконечная загрузка в разделе "Наушники"

### ISSUE THREAD

**Issue by asdsadh** [steam3d/MagicPods-Windows#326]
В какой-то момент просто перестало работать, искать нашники, удалились те которые уже были и на этом всё. Наушники просто через блютуз подключаться, а в приложении не появляються. Уже переустанавливал, перезагружал приложение - ничего не помогло. 

![Desktop Screenshot 2023 03 28 - 09 52 34 03](https://user-images.githubusercontent.com/123835846/228152838-628b3885-6cf5-4d9d-bbd5-f997d39ca176.png)

**Comment by asdsadh** [comment]
> Добрый день, прикрепите лог файлы, их можно найти на вкладке поддержка.
Когда нажимаю "Журнал ошибок" - нечего не рпоисходит. Может скажете путь к лог файлу?

![Desktop Screenshot 2023 03 28 - 10 41 51 94](https://user-images.githubusercontent.com/123835846/228164484-02340f30-9470-4db5-a6fe-89bf1c118c48.png)

**Comment by steam3d** [comment]
Путь до логов:
%LOCALAPPDATA%\Packages\715AleksandrMaslov.MagicPods_vk1h99z2mpttm\TempState

**Comment by steam3d** [comment]
У Вас даже не запускается приложение - в этом причина.
Попробуйте сначала [восстановить поврежденные файлы системы](https://support.microsoft.com/ru-ru/topic/%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2%D0%B0-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D1%85-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE%D1%82%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D1%85-%D0%B8%D0%BB%D0%B8-%D0%BF%D0%BE%D0%B2%D1%80%D0%B5%D0%B6%D0%B4%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D1%85-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-79aa86cb-ca52-166a-92a3-966e85d4094e)

Затем запустить, если опять тоже самое - нажмите пуск и напишите "Просмотр событий". И далее
![image](https://user-images.githubusercontent.com/30986874/228170731-5c8af9e0-9395-486d-80bd-53af56b0f756.png)

На строках с ошибками в подробностях (3) нужно найти слова типа MagicPods, MagicPodsUI, MagicPodsService. Прикрепить скриншот ошибки. 

Будет выглядеть типа такого:
![image](https://user-images.githubusercontent.com/30986874/228170900-77dc4fd4-0129-43c6-92f1-e0b184f1c89c.png)
