### ISSUE TITLE
AirPods Connection Status Displays Incorrectly

### ISSUE THREAD

**Issue by SupppRabit** [steam3d/MagicPods-Windows#328]
When I actually connect my computer to my AirPods, it shows 'disconnected'; but when I disconnect them, it shows 'connected'. These two situations are reversed
![1](https://user-images.githubusercontent.com/55012063/229265157-12b8daaf-6700-4a7f-bf4e-30e7aaf5ed73.png)
![2](https://user-images.githubusercontent.com/55012063/229265162-6d9d623f-6ade-4c0b-9089-a7a529a52103.png)

**Comment by steam3d** [comment]
Hi. The item described action that will be happen when you click on it.

**Comment by SupppRabit** [comment]
It does seem like a localization error. Simply removing the character "已"  (which means "already") would solve the problem. However, I did not see the character "已" in the webpage you provided, but it does appear in the app.

**Comment by SupppRabit** [comment]
Oh, I found that someone had made the modification three weeks ago, but the updated version may not have been released yet. 
![QQ截图20230401135815](https://user-images.githubusercontent.com/55012063/229268536-ecd1933f-b929-4bd8-aeec-f67f98f236dc.png)
