### ISSUE TITLE
My magic pods keep not launching on Windows startup/user login.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#329]
Hey,
My magic pods keep not launching on Windows startup/user login.
Is there a service/program that I can add to run/launch redundantly in the background, So magic pods will open if it did not open on Windows startup/user logon?
![Clip_20230404_160257](https://user-images.githubusercontent.com/119108387/229800215-a0b57939-8164-4a64-b560-bb4fc482cf8d.png)
![Clip_20230404_160333](https://user-images.githubusercontent.com/119108387/229800339-57f59e81-606b-40d8-ba98-2945ed4e4ff5.png)

This is a continuation of #317

**Comment by steam3d** [comment]
Hi. I do not know about the apps that can do this, but Windows does not allow you to launch MagicPods directly, because it Microsoft Store app.

**Comment by bigplayer-ai** [comment]
> You can run the MagicPods using cmd: `explorer.exe shell:appsFolder\715AleksandrMaslov.MagicPods_vk1h99z2mpttm!App`
> 
> It will run the app as if you click on app icon

Very fragile solution:
1) I don’t want to open the GUI interface every time 
2) The store application is sandboxed, they keep changing paths every while.

**Comment by steam3d** [comment]
> 2. The store application is sandboxed, they keep changing paths every while.

No. Only I can change path during update.
