### ISSUE TITLE
Pop-up window

### ISSUE THREAD

**Issue by davidloveradev** [steam3d/MagicPods-Windows#33]
Hi,

When I press the button of my case ("closed", if the case is open that doesn't happen) with the AirPods inside, the Pop up shows up, but when I close it, it starts to reopen endlessly. 

![Untitled](https://user-images.githubusercontent.com/62068732/95277641-4a161600-081c-11eb-8a95-34561c6bb218.png)

**Comment by steam3d** [comment]
Hi, can you upload log file? I tested on my pc and could't repeat this behavior.

**Comment by davidloveradev** [comment]
10/11/2020 7:51:39 PM ----------------- --- [Info]  |                | Start program
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | search_by_rssi: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | log_lvl: Info
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | auto_connect: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | volume_down_percent: 75
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | ear_detection: None
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | is_ble: True
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | search_min_rssi: -47
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | debug_mode: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | hide_tips: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | recommended_packet_count: 92
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | battery_tray_icon: True
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | recommended_rssi: -51
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | hide_tray_icon: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | hide_welcome_screen: True
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | recommended_rssi_count: -4733
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | animation_rssi: -55
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | battery_tray_icon_type: Digital
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | show_connect_btn: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | send_play: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | low_latency: False
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | search_max_rssi: 0
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | animation: True
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | animation_size: Large
10/11/2020 7:51:39 PM ----------------- --- [Info]  |    Settings    | additional_media_players: True
10/11/2020 7:51:39 PM ----------------- --- [Info]  |                | Run AirpodsState
10/11/2020 7:51:40 PM AC:90:85 --- [Info]  |GetPairedDevices| Find AirPods Pro Model airpodspro Disconnected
10/11/2020 7:51:40 PM ----------------- --- [Info]  |GetPairedDevices| IsAirPodsConnected False
10/11/2020 7:51:40 PM ----------------- --- [Info]  |                | AirPods found
10/11/2020 7:51:40 PM ----------------- --- [Info]  |                | Advertisement watcher started!
10/11/2020 7:52:32 PM AC:90:85 --- [Info]  |ConnectionStatus| Bluetooth ac:90:85:33:8d:75 Connected (IsAirPodsConnected True)
10/11/2020 7:52:33 PM 41:57:43 -55 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:52:34 PM 41:57:43 -43 [Info]  |  Print Action  | Open(RL)  | Case:open
10/11/2020 7:52:46 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:52:46 PM 41:57:43 -51 [Info]  |   MyAirPods    | Founded
10/11/2020 7:52:46 PM 41:57:43 -54 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:01 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:01 PM 41:57:43 -44 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:07 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:07 PM 41:57:43 -48 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:17 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:17 PM 41:57:43 -52 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:24 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:24 PM 41:57:43 -52 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:29 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:29 PM 41:57:43 -52 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:36 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:36 PM 41:57:43 -45 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:42 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:42 PM 41:57:43 -53 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:47 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:47 PM 41:57:43 -48 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:53:53 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:53:53 PM 41:57:43 -49 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:54:04 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:54:04 PM 41:57:43 -45 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:54:10 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:54:10 PM 41:57:43 -46 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:54:20 PM ----------------- --- [Info]  |                | force_hide clear
10/11/2020 7:54:20 PM 41:57:43 -47 [Info]  |   Animation    | Show, case_open False
10/11/2020 7:54:30 PM AC:90:85 --- [Info]  |ConnectionStatus| Bluetooth ac:90:85 Disconnected (IsAirPodsConnected False)

**Comment by steam3d** [comment]
Can you try repeat with extended log?

1. Go to "Support" page and click to "MagicPods" text until the page is refreshed. (usually 5 times)
2. Go to "General settings" -> scroll down -> change log level to **trace**
3. Restart the app

**Comment by davidloveradev** [comment]
I've tried but I don't know where those things are. The only support I've seen is on the app. I don't think I get it.

**Comment by davidloveradev** [comment]
This is a one-time press.

(IsAirPodsConnected True)
10/12/2020 8:16:28 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2054aab83800001c017a853f636fd50b0f8c3eaf6381da
10/12/2020 8:16:28 AM 45:BD:07:06:EB:31 -52 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:16:28 AM 45:BD:07:06:EB:31 -56 [Trace] |                | 0719010e2054aab83800001c017a853f636fd50b0f8c3eaf6381da
10/12/2020 8:16:28 AM 45:BD:07:06:EB:31 -56 [Info]  |  Print Action  | <unknown>54
10/12/2020 8:16:32 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:16:32 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2054aab83800001c017a853f636fd50b0f8c3eaf6381da
10/12/2020 8:16:32 AM 45:BD:07:06:EB:31 -53 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:16:32 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:32 AM 45:BD:07:06:EB:31 -49 [Info]  |  Print Action  | Open(RL)  | Case:open
10/12/2020 8:16:34 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:34 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:35 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:37 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:40 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:40 AM 45:BD:07:06:EB:31 -51 [Info]  |   MyAirPods    | Founded
10/12/2020 8:16:40 AM ----------------- --- [Debug] |                | Save cmd
10/12/2020 8:16:40 AM ----------------- --- [Debug] | UpdateBattery  | Updated
10/12/2020 8:16:41 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:42 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:42 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:42 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:43 AM 63:AB:2F:33:24:A2 -78 [Trace] |                | 0719010e2022f88f0100005b2166c5c1f2b2fb735e4466eb4cad86
10/12/2020 8:16:43 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:43 AM 63:AB:2F:33:24:A2 -82 [Trace] |                | 0719010e2022f88f0100005b2166c5c1f2b2fb735e4466eb4cad86
10/12/2020 8:16:43 AM 63:AB:2F:33:24:A2 -82 [Info]  |  Print Action  | Close(R)  | L: in
10/12/2020 8:16:45 AM 45:BD:07:06:EB:31 -58 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:45 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:49 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:16:49 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:49 AM 45:BD:07:06:EB:31 -52 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:16:51 AM 45:BD:07:06:EB:31 -58 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:53 AM ----------------- --- [Info]  |                | isAirpodsConnect: Hide 10/12/2020 8:16:49 AM < 10/12/2020 8:16:56 AM
10/12/2020 8:16:53 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:53 AM 45:BD:07:06:EB:31 -50 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:16:54 AM 45:BD:07:06:EB:31 -58 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:56 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:16:56 AM 45:BD:07:06:EB:31 -58 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:57 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:16:57 AM 45:BD:07:06:EB:31 -50 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:01 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:01 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:01 AM 45:BD:07:06:EB:31 -49 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:01 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:03 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:05 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:09 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:09 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:10 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:10 AM 45:BD:07:06:EB:31 -52 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:11 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:11 AM 45:BD:07:06:EB:31 -57 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:15 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:15 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:15 AM 45:BD:07:06:EB:31 -50 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:16 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:17 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:19 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:22 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:22 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:22 AM 45:BD:07:06:EB:31 -50 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:23 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:26 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:26 AM 45:BD:07:06:EB:31 -58 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:26 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:26 AM 45:BD:07:06:EB:31 -49 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:27 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:29 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:29 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:30 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:31 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:32 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:33 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:34 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:35 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:37 AM 45:BD:07:06:EB:31 -60 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:38 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:38 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:39 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:40 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:41 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:41 AM ----------------- --- [Debug] | UpdateBattery  | Updated
10/12/2020 8:17:43 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:44 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:45 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:45 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:49 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:17:49 AM 45:BD:07:06:EB:31 -53 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:49 AM 45:BD:07:06:EB:31 -53 [Info]  |   Animation    | Show, case_open False
10/12/2020 8:17:50 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:52 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:52 AM 45:BD:07:06:EB:31 -49 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:53 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:53 AM 45:BD:07:06:EB:31 -50 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:54 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:54 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:55 AM 45:BD:07:06:EB:31 -59 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:56 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:56 AM 45:BD:07:06:EB:31 -57 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:58 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:17:59 AM AC:90:85:33:8D:75 --- [Info]  |ConnectionStatus| Bluetooth ac:90:85:33:8d:75 Disconnected (IsAirPodsConnected False)
10/12/2020 8:19:23 AM ----------------- --- [Info]  |                | force_hide clear
10/12/2020 8:19:23 AM 45:BD:07:06:EB:31 -52 [Trace] |                | 0719010e2055aab8380004ffdab02d9c5112bd7d76b41234497ba2
10/12/2020 8:19:23 AM 45:BD:07:06:EB:31 -52 [Info]  |   Animation    | Show, case_open False

**Comment by steam3d** [comment]
Can you upload the full log file? I can't see what settings you are using

**Comment by davidloveradev** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/5388874/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Try to update the app to 1.0.58.0
