### ISSUE TITLE
magicpods keeps crashing/closing without any prompt.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#330]
Hey,
magicpods keeps crashing/closing without any prompt. 
So I open magicpods
after a while I want to use a hotkey set with my magicpods, magicpods is closed so I need to reopen it.

**Comment by steam3d** [comment]
Hi. It's not realated to MagicPods I think. It  is reelated to your Windows (based on your other issues).  You could try to restore damaged system files. Maybe it will help.

I have similar issue with my external GPU. When PC lock the screen all application (include MagicPods) that use global hotkeys crash.
