### ISSUE TITLE
Volume issues after connection

### ISSUE THREAD

**Issue by yige-yigeren** [steam3d/MagicPods-Windows#331]
Some earphones will be automatically turned to the maximum volume by MagicPods when they are connected. To be honest, it would be murder before I turn the volume back down (laughs).
If I turn off the MagicPods, it will use my last connection volume, I remember I set it in windows, but enabling the MagicPods somehow automatically adjusts to 100% after the bluetooth connection (and before the adjustment, it shows the last connection volume, but was turned up to 100% in a split second)
I hope this bug can be fixed, and if possible, the function of setting the volume after connection can be configured for each headset (IMHO Windows is too bad at this aspect)
Windows 11 professional 22H2 22621.1413 1000.22639.1000.0

**Comment by steam3d** [comment]
Hi. Turn down the voice volume. MagicPods first connect Headset then Headphones. By default all Bluetooth headphones have 100% headset volume.

**Comment by yige-yigeren** [comment]
> Hi. Turn down the voice volume. MagicPods first connect Headset then Headphones. By default all Bluetooth headphones have 100% headset volume.

I noticed that after updating to 22h2 it seems that the previously set registry keys are not working, so I'll try to change them.
:(
