### ISSUE TITLE
耳机放在电脑旁根本接收不到耳机

### ISSUE THREAD

**Issue by 2206871401** [steam3d/MagicPods-Windows#332]
airpods3耳机

**Comment by steam3d** [comment]
Hi. Do you have original AirPods 3? Can you upload the log files?

**Comment by 2206871401** [comment]
我不会上传日志，我目前只能把magicpods和蓝牙发给你，以及我的耳机信息发给您，如果您可以教我如何操作，也可以发送您的联系方式脸书、微信或者别的联系方式我都可以与您联系。





------------------ 原始邮件 ------------------
发件人: Alexander Maslov ***@***.***&gt;
发送时间: 2023年4月8日 01:30
收件人: steam3d/MagicPods-Windows ***@***.***&gt;
抄送: 2206871401 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [steam3d/MagicPods-Windows] 耳机放在电脑旁根本接收不到耳机 (Issue #332)





 
Hi. Do you have original AirPods 3? Can you upload the log files?

**Comment by steam3d** [comment]
I couldn't help without additional information. How to report wrote [here](https://help.magicpods.app/report-issue/)

You also should describe the issue and provide screenshots. 

Note. MagicPods does not support a fake AirPods.
