### ISSUE TITLE
Searching for airpods

### ISSUE THREAD

**Issue by luc4dev** [steam3d/MagicPods-Windows#333]
i installed the trial version of it, and when i try to connect my airpods pro to it, it just keeps saying searching for airpods then i get an error, on windows they connect, but on the app it doesnt work

**Comment by luc4dev** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11185405/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/11185406/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Hi. Which AirPods do you have?  Original or fake?

**Comment by luc4dev** [comment]
original

**Comment by steam3d** [comment]
According the log files everything is fine.

We could check copability of Bluetooth adapter. Run  [DebugError.zip](https://github.com/steam3d/MagicPods-Windows/files/10907873/DebugError.zip) application for 5-10 sec and close it. Near the exe file will appers `Log.txt` file. Upload it here.

**Comment by luc4dev** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/11185420/log.txt)

**Comment by steam3d** [comment]
Your Bluetooth adapter does not support AirPods data format. Because of it the MagicPods can't search your AirPods.
