### ISSUE TITLE
Infinite search, no battery status

### ISSUE THREAD

**Issue by idiotGG** [steam3d/MagicPods-Windows#334]
Hello. I've made all the recommended solutions in the troubleshooting guide (tick radio, devices in radio settings, install the latest vendor bluetooth driver and even try the default windows 10 one, and of course the reinstall of the program) but the problem still exists: it's searching for airpods pro 2 endlessly and cannot find them. 
My laptop is Lenovo s340 15api
The airpods work just fine with my system without the app (I got it just to see the battery status properly tbh)
Attached is also some bluetooth report thing I've launched that I saw in another thread
[reportzip.zip](https://github.com/steam3d/MagicPods-Windows/files/11185869/reportzip.zip)

**Comment by steam3d** [comment]
Hi. The MagicPods does not recive data from Windows Bluetooth API. Did you try to reinstall MagicPods after Bluetooth driver update?

**Comment by idiotGG** [comment]
I did. Right after.

**Comment by steam3d** [comment]
It's known issue and I think it depends from specific windows region or private settings or someone else. I could bot reproduce it on my side. (I tried more that 10 PC with different configuration). The main problem I do not get any error. From my side everything OK, so I have no idea which way to dig

**Comment by steam3d** [comment]
You debug the log show that you Bluetooth works fine and receive data. The MagicPods use the same way (100% the same) and do not get any data.

**Comment by idiotGG** [comment]
> I did. Right after. Btw I did purchase it from the windows store. Any way the store deployment might be crappy and I should try a direct installer somewhere?

btw I did try uninstalling the program, uninstalling the microsoft driver, restarting, installing the lenovo driver, restarting, installing the Magic Pods, restarting, trying the recommended solution again, but to no avail.
Any way to get from the infinite search and see the device battery status? Like, it seems to work just fine, even the functionality is alright (auto-play or auto-turn off when you put the headset in or out of your ears)? Is there a way to brute force the program to also show battery levels?

**Comment by idiotGG** [comment]
BTW I've installed the "Assistant Trigger" app on my samsung android smartphone and everything works fine: all the charge levels, the google assistant activation, it even identified the type of airpods itself.

**Comment by steam3d** [comment]
I do not know because I could not reproduce this. The problem is somewhere between MagicPods and Windows Bluetooth. The MagicPods is waiting for the data infinity and receives nothing from Windows. The Bluetooth is controlled by Windows.

**Comment by steam3d** [comment]
No feedback
