### ISSUE TITLE
MagicPods locking up when bluetooth disconnects

### ISSUE THREAD

**Issue by svalencia014** [steam3d/MagicPods-Windows#335]
Whenever my AirPods disconnect from Bluetooth without hitting the "disconnect" button in MagicPods, the app will lock up and force me to restart it through task manager. The same applies when I close and re-open my laptop, I am required to kill Magicpods through task manager because the tray icon stops responding and reopen it every time.

**Comment by steam3d** [comment]
Hi. Can you upload the log files? Did you try to wait maybe something work in background? Which architecture of processer do you have? (x86, x64, Arm)

**Comment by svalencia014** [comment]
Never mind I found it. I attached both log files available. I run an x86 processor I believe, an Intel I7-1165G7
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11234458/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/11234463/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
The log said that something wrong with Bluetooth device. 
` -2147020577 The device is not ready for use. (Exception from HRESULT: 0x800710DF)`

You can try to remove the AirPods and pair it again to setup AirPods again. Also you can update Bluetooth driver.

**Comment by svalencia014** [comment]
I'll test it out and follow up

**Comment by svalencia014** [comment]
It still does the same thing after unpairing and repairing them

**Comment by svalencia014** [comment]
Any other suggestions?

**Comment by steam3d** [comment]
You could  google error 'The device is not ready for use. (Exception from HRESULT: 0x800710DF)' to get some solutions.

I also recommend [check system files](https://support.microsoft.com/en-gb/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e)
