### ISSUE TITLE
some png icons shows as black background only on magicpods.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#339]
Hey,
some png icons shows as black background only on magicpods. Also when switching the same issue occurs. the background of the icon is black.
![Clip_20230424_151433](https://user-images.githubusercontent.com/119108387/233993043-447413a4-dc4d-4c50-b68d-51db9a2c9ac6.png)
![z533](https://user-images.githubusercontent.com/119108387/233993116-0b93e074-e85a-47a1-9986-82e44037162f.png)

**Comment by bigplayer-ai** [comment]
Also when switching the same issue occurs. the background of the icon is black.

**Comment by steam3d** [comment]
I don't know which png format UWP supports. I tested on  images exported from Figma and Photoshop. They display correct. You could try to change size on 1px and export again.

**Comment by bigplayer-ai** [comment]
nvm I will stick with soundswitch. I think this is too much work for magicpods. It's better to seperate these projects.
