### ISSUE TITLE
wake up Windows Bug

### ISSUE THREAD

**Issue by muxuuu** [steam3d/MagicPods-Windows#34]
After wake up Windows,taskbar icon turn red and say "this device doesn't support bluetooth 4.0"
restart program is useful,but everytime wake up PC need to restart MagicPods just too cumbersome,hope to repair.THANKS!
Device: Surface Pro 5
this device has a problem,sometimes after wake up device then can't connect AirpodsPro by bluetooth,but can connect other devices,i need to restart bluetooth device by Windows Device Manager then can connect successfully,hope that help~

从睡眠状态唤醒电脑后，任务栏状态会变红，进程序提示”需要支持蓝牙4.0及以上的设备“
重启软件后可以正常使用。
设备：Surface Pro 5
Surface的蓝牙连接AirpodsPro有一点别的问题，不知道是否与这有关。有时候睡眠状态唤醒后无法连接AirpodsPro，但其他蓝牙设备都可以连接，在设备管理器中重启蓝牙驱动后才能正常连接。

**Comment by steam3d** [comment]
Hi. I think that windows need some time to enable Bluetooth but MagicPods Immediately requests access to Bluetooth. As result the windows can't give Bluetooth control to app.

Did you try wake up your device and wait may be 10-60 second before connecting to your AirPods?

Also I think that it connected with battery saving. You can control this option on Bluetooth properties in device manager.

**Comment by muxuuu** [comment]
Log Info:
2020/10/12 12:13:07 ----------------- --- [Info]  |                | Advertisement watcher stopped
2020/10/12 12:13:07 ----------------- --- [Error] |                | BLE does not support on this PC
2020/10/12 12:13:38 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 12:14:30 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 12:14:33 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 12:14:36 ----------------- --- [Info]  |                | Start program

**Comment by muxuuu** [comment]
The error message says : "Your device doesn't support BLE(need Bluetooth 4.0)".
Waiting isn't work , The only useful way is to restart program.
I think it's Surface's Bluetooth device problem , because there's no turn off Bluetooth battery saving option in device manager.
(Maybe it's Windows Laptop battery saving mode cause this problem , I'll try it later)

**Comment by steam3d** [comment]
Okay. Let's try to understand if it possible to fix.
1. Go to "Support" page and click to "MagicPods" text until the page is refreshed. (usually 5 times)
2. Go to "General settings" -> scroll down -> change log level to debug
3. Restart the app
When you get this issue again then upload the log file here.

I can track when device is locked or unlocked. I want to check what going on when you wake up your device
Don't forget after upload the log file disable developer settings.

**Comment by muxuuu** [comment]
2020/10/12 18:18:29 ----------------- --- [Info]  |                | Advertisement watcher stopped
2020/10/12 18:18:29 ----------------- --- [Error] |                | BLE does not support on this PC
2020/10/12 18:18:39 ----------------- --- [Debug] |SendConnCommand| btconn.Disconnect code 1000
2020/10/12 18:18:40 ----------------- --- [Debug] |                | User unlock screen
2020/10/12 18:18:42 ----------------- --- [Debug] |SendConnCommand| btconn.Connect code 1000
2020/10/12 18:18:42 ----------------- --- [Debug] |SendConnCommand| Attempt to connect 1
2020/10/12 18:18:52 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 18:18:52 ----------------- --- [Debug] |                | Try to connect
2020/10/12 18:19:02 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 18:19:02 ----------------- --- [Debug] |                | Try to connect
2020/10/12 18:19:04 ----------------- --- [Info]  |                | Connection to UWP lost
2020/10/12 18:19:04 ----------------- --- [Debug] |                | Try to connect
2020/10/12 18:19:04 ----------------- --- [Error] | UWP Connection  | Status: AppUnavailable
2020/10/12 18:19:19 ----------------- --- [Debug] |SendConnCommand| btconn.Disconnect code 0
2020/10/12 18:19:21 80:5F:C5:EF:9B:E5 --- [Info]  |ConnectionStatus| AirPods Pro Connected (IsAirPodsConnected True)
2020/10/12 18:19:25 ----------------- --- [Debug] |SendConnCommand| btconn.Connect code 0
2020/10/12 18:19:25 ----------------- --- [Info]  |SendConnCommand| Connected

**Comment by muxuuu** [comment]
That might be a Surface Bluetooth Bug , Maybe Software Update can't fix it , just forget it.

**Comment by steam3d** [comment]
Try to update the app to 1.0.58.0. I added battery save mode. ( it is always on) The app pauses work when you lock the screen. Maybe it fixes your problem. My Surface Pro 7 works good with the MagicPods.

**Comment by steam3d** [comment]
Closed. No feedback.

**Comment by muxuuu** [comment]
Yeah, That works perfect now!!!
Thanks very much!!!
