### ISSUE TITLE
[Feature Request]  Add a universal mic mute hotkey that mutes all microphones on your PC computer

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#340]
“[Feature Request] Add a universal mic mute button that mutes all microphones on your PC computer. This way, we can ditch SoundSwitch for good. Thank you for this amazing software!”
nvm I will stick with soundswitch. I think this is too much work for magicpods. It's better to seperate these projects.

**Comment by steam3d** [comment]
It will be added when I find a way to remap headphones buttons
