### ISSUE TITLE
Can't enable Run on startup

### ISSUE THREAD

**Issue by Kentaki1607** [steam3d/MagicPods-Windows#341]
When updated to version 2.0.50.0 X64, I can't turn on the Run on startup feature in the app. I tried to open Task Manager and enable MagicPods to run on startup, but when I reopened Task Manager, it turned to Disable. How to fix it?

**Comment by steam3d** [comment]
Hi.
1. Open the MagicPods on Support page. Click 5-7 times on MagicPods logo until page refresh. 
2. Go to General settings scroll down and expand the Developer settings
3. Change log level to debug
4. Close MagicPods window
5. Open MagicPods window and go to Preferences

Upload the log files here. You can get them on Support page.

**Comment by steam3d** [comment]
`Activation kind DisabledByPolicy` - You or your administrator of PC disabled startup globally.

You need to enable startup again. I do not know how do you disabled it. You could try to google something like "Group Policy disable startup programs" and do the opposite. 

Windows has a lot of way to enable and disable globally startup applications:  https://www.thewindowsclub.com/manage-startup-items-windows-8
