### ISSUE TITLE
Square background behind popup

### ISSUE THREAD

**Issue by MrPropre** [steam3d/MagicPods-Windows#342]
![Capture d'écran 2023-04-29 150457](https://user-images.githubusercontent.com/36234981/235304290-638b2b9a-7fd4-4d04-a31f-c94d85dff2f5.png)
![Capture d'écran 2023-04-29 150606](https://user-images.githubusercontent.com/36234981/235304292-8b212dd5-a860-4eee-a45d-d52b4208d229.png)

**Comment by steam3d** [comment]
Hi. Looks like you use something like this https://github.com/MicaForEveryone/MicaForEveryone. Add MagicPodsService.exe to ingore list.

**Comment by MrPropre** [comment]
Thanks!
