### ISSUE TITLE
how can i connect fake airpods if i can connect can i see battery levels?

### ISSUE THREAD

**Issue by puryigithan** [steam3d/MagicPods-Windows#343]
it keeps getting like this can u help me?
![Ekran Görüntüsü (2)](https://user-images.githubusercontent.com/95376684/235320586-91efee11-85bd-4061-8db6-3642060f1022.png)

**Comment by steam3d** [comment]
Hi. MagicPods does not support Fake AirPods yet.

**Comment by puryigithan** [comment]
oh sorry for that man
