### ISSUE TITLE
Bigger modal upon connecting

### ISSUE THREAD

**Issue by Iliannnn** [steam3d/MagicPods-Windows#344]
How do you make the modal that pops up when opening the case of your AirPods bigger? It's quite small.

**Comment by steam3d** [comment]
Set size of the popup window

![image](https://user-images.githubusercontent.com/30986874/236277144-a3807cf9-617b-484c-a4b1-150cb39a7b02.png)

**Comment by Iliannnn** [comment]
Thanks, solved.
