### ISSUE TITLE
[feature request] Show window only when Audio Output changes to AirPods only.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#347]
Hello,

Could we have an option to display a window only when the audio output changes only to AirPods only? Currently, your application automatically connects to my AirPods without notifying me. It would be helpful to have a visual cue indicating that this has happened.

Thank you.

**Comment by steam3d** [comment]
MagicPods does no connect automaticly. It can connect only when Auto-connect enabled and the necessary conditions are met. 

You can enable Sound output window do be notificated when sound output switched

**Comment by steam3d** [comment]
> There is no auto connect option on my magicpods.

Then it's not MagicPods try to connect your AirPods.

> I want a sound output changed only when the airpods are connected.

Not planned. It's confusing behaviour when you have multiple headphones and auto switch sound out options turn on.
