### ISSUE TITLE
Auto Connect For Audio Streaming [Feature Request]

### ISSUE THREAD

**Issue by l0lGhostlxl** [steam3d/MagicPods-Windows#349]
When an audio device is connected, there could be a toggle to auto connect to the mobile device for the audio streaming feature to make the experience more seamless. This makes it easier as the user will not have to manually press connect inside the app.

**Comment by steam3d** [comment]
Hi. Read this https://github.com/steam3d/MagicPods-Windows/issues/288

**Comment by l0lGhostlxl** [comment]
Ah thank you, should've read the opened issues mb.
