### ISSUE TITLE
connect button issue

### ISSUE THREAD

**Issue by vural-bul** [steam3d/MagicPods-Windows#35]
connect button is very bad i press button and pc conneting airpods pro 
-reset airpods pro settings (my unactive airpods pro free ag audio going to active)
and connect button color is so bad :( 
please new color grey-white conbination (like a apple airpods connect button)

my english is bad sorry but ı love you and your app <3 <3

**Comment by steam3d** [comment]
As i described [here](https://github.com/steam3d/MagicPods-Windows/wiki/Connectivity-issues) For now there is only one way to connect AirPods.
I can't check when you enable or disable some services, for this reason, the only solution was to connect all services.
I understand that it is not too good decision, maybe i need to add some additional option to it.

I planned to add for users options to control color and etc. I don't know when, this is not a quick task

**Comment by steam3d** [comment]
It finally fixed.
