### ISSUE TITLE
Low audio latency not working on applications

### ISSUE THREAD

**Issue by nickp7** [steam3d/MagicPods-Windows#351]
I have enabled the low audio latency with my air pods pro 2nd gen, although it works flawlessly while browsing or listening to music, the issues comes whenever i open a program like a game or premiere, so far I've done some limited testing with some different results, like delay on the software but not while browsing, a few seconds after i open the software a white noise start buzzing and it effect every single audio source, or no audio at all only on the opened application. 

I do understand the driver issue and the delay caused by windows 11, if it's fixed while using magic pods, why it is not on other programs?
Also I'm on windows 11 22H2.

Thanks.

**Comment by steam3d** [comment]
Hi. The MagicPods prevents headphones go to IDLE mode so you get immediately playback after pause and etc. Side effect could be a quite white noise.

Some Bluetooth vendors fixed this issue. Sometimes it's better to turn off if you do not notice difference.

**Comment by nickp7** [comment]
Hi, thanks for the reply.

So if I understand correctly if it has the "delay" effect it's software dependent and not an magicpods or windows problem ?

and as for the white noise, it's not subtle, I can quite hear the difference when the program is open and the noise start and when it's not, but I guess it's the same issue as I stated above.

Thanks for the clarification 👍
