### ISSUE TITLE
Airpods Pro 2nd Generation ear detection not working

### ISSUE THREAD

**Issue by damivn** [steam3d/MagicPods-Windows#352]
Hello , I bought the app but it seems like the ear detection function doesn't work on the Airpods Pro 2nd gen, can this be fixed?
Would be nice to add a function to enable and disable this function.Thanks!

**Comment by steam3d** [comment]
Hi. You can read this https://github.com/steam3d/MagicPods-Windows/issues/246 and check [help](https://help.magicpods.app/fun-capability/). Apple restricted some AirPods features on none-Apple devices.

I am watching this situation if something changed I will make changes in MagicPods
