### ISSUE TITLE
Library of device icons

### ISSUE THREAD

**Issue by alejandro5042** [steam3d/MagicPods-Windows#354]
I'd love to change the icon of my device, however, I need to have a PNG... of my device... how/why?

Maybe we can find a dozen or so stock icons of various headset designs that I can choose from, that have similar styling to the app. That'd be awesome!

**Comment by steam3d** [comment]
Hi. You could simple google necessary icon and set it if you want.  It much flexible that have static icon pack.

it took 3 sec to find necessary icon and set it.
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/a226242f-ac87-48bb-b86c-6cff36bb741d)
