### ISSUE TITLE
Freshly installed, keeps loading, nothing happens

### ISSUE THREAD

**Issue by ksandersen** [steam3d/MagicPods-Windows#355]
Hi, 
Ive just installed the app from MS Store, and nothing happens. The loading bar just continues to load. I've tried turning of radios in windows settings, ive tried reinstall the app (many times). Ive tried updating everything. 
I the tried to download the app on my other Home PC, and it booted perfectly up. But it doesnt seem to be able to work on my laptop..
Dell XPS 15 9510
Windows 11
Hope you can help, idk if its just a
![Skærmbillede 2023-06-04 024609](https://github.com/steam3d/MagicPods-Windows/assets/73589532/cff39954-b0d1-455e-998d-e406c839e362)
 bug. 
BR Kris

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/11644544/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/11644545/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Hi. Did you use some tweaks to optimize Windows 11? 

You get unknown error:
Forkert parameter. Full text search is not supported.

I tried to google it and found nothing about it. Looks like something missing from the system or corrupted, if you say that MagicPods work on other PC.

You could try to restore system files:
https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca

**Comment by steam3d** [comment]
No feedback
