### ISSUE TITLE
AirPods Max

### ISSUE THREAD

**Issue by PhoenixYT124** [steam3d/MagicPods-Windows#356]
Everything works absolutely fine, apart from the Low Battery Windows Notification and Pausing my Content when i take the AirPods off. Really annoying, because my digital crown also can't pause my content. I mainly use the YouTube Webpage.

**Comment by steam3d** [comment]
The media keys of Bluetooth headphones controlled by Windows, some apps can take control of them globally. Do you try to use digital crown after reboot PC when there are no applications open except your browser?

**Comment by PhoenixYT124** [comment]
Yes, the Digital Crown now works, Wallpaper Engine was the problem. Still my low battery notification does not work, although i checked and notifications are turned on for the app. Also pause when i take them off doesn't work. With my Gen3 it does work, when i take 1 out. With the Maxes it just keeps playing the Video. Pause after disconnect does work though.

**Comment by steam3d** [comment]
Upload the log files from support page.

**Comment by steam3d** [comment]
According log files everything works as expected.

```
09.06.2023 02:52:28 ----------------- ---- [Info]  |LowBatteryNotifi| AirPods Max von Professor Zweistein sent low battery notification
09.06.2023 02:52:28 62:8D:35:17:E4:56  -41 [Info]  |EarDetectionFeat| AirPods Max von Professor Zweistein does Pause
```

Low battery notification sent to Windows notification center. (I can't get response was it shown or not from Windows)
Pause command also sent to Windows Media control center. (I can't control what Windows decide to do with it)

So MagicPods does everything right. 

PS
For my case Firefox sometimes does not react on play / pause from Windows Media control so I have to refresh the webpage with video. It's the Firefox bug, maybe you have something like this.
