### ISSUE TITLE
Couldn't find my airpods prod

### ISSUE THREAD

**Issue by babusbeih** [steam3d/MagicPods-Windows#357]
Dears,
I'm trying to open my AirPods Pro setting from the app but it keeps failing to find the Airpods even though I tried the 3 solutions provided by you on this page and still not working. but the AirPods are already connected and working fine on my device.

earphone: Apple AirPods pro
Laptop: Dell [Latitude 3520]
Windows: 11

**The screenshot and the logs are attached

![MagicPods](https://github.com/steam3d/MagicPods-Windows/assets/52489603/8561c681-30f8-420d-933d-2401fce39fcc)
[TempState.zip](https://github.com/steam3d/MagicPods-Windows/files/11743340/TempState.zip)

**Comment by steam3d** [comment]
Hi. Do you have original one or fake?

**Comment by babusbeih** [comment]
original, and it was working fine on win 10 but when I upgraded it to win 11 it keeps failing to find the AirPods

**Comment by steam3d** [comment]
> original, and it was working fine on win 10 but when I upgraded it to win 11 it keeps failing to find the AirPods

Well, looks like it's upgrade to Windows 11 issue.  Usually the problem is Bluetooth driver.

**Comment by steam3d** [comment]
> I installed another driver that recommended by Dell and reboot the device, but the issue still persists.

From my side everything fine. I request Bluetooth data from Windows, but Windows returns nothing, so I do not have tools to change it.

**Comment by babusbeih** [comment]
so what is the proper way to fix this issue. or I would request to refund my payment and remove the app.

**Comment by babusbeih** [comment]
the upgrade has not been done on the same device. I bought a new device with win 11 and installed magic pods. since that its not working

**Comment by steam3d** [comment]
Okay. Let's check you Bluetooth adapter run this[DebugError.zip](https://github.com/steam3d/MagicPods-Windows/files/10907873/DebugError.zip), wait 10 second and upload the log.txt file here (it will apper near .exe file)

**Comment by babusbeih** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/11743973/log.txt)
PFA

**Comment by steam3d** [comment]
The MagicPods and DebugError use the same code to request data. DebugError works, but MagicPods does not. My guess is that Windows is blocking Bluetooth access for MagicPods or some setting is affecting apps from the Microsoft Store

**Comment by steam3d** [comment]
> is there any solution for this issue ?

This issue does not contains any error massages, so the way trying to fix this issue is clear installation of Windows from official installer or trying to Google ways why Bluetooth does not works in some apps. (This behavior is very rare. You are the second user to have this error. The previous user reinstalled the system and everything worked).
Because from my side everything fine. We tested that code works as expected.

**Comment by babusbeih** [comment]
Thanks for your response, I'll try to google it and post the solution here if I found it to share the knowledge.

**Comment by wheelman944** [comment]
I'm having the same problem, but with Beats Studio Buds.

**Comment by steam3d** [comment]
@wheelman944 only one solution is known - update manually Bluetooth driver.

**Comment by wheelman944** [comment]
@steam3d I did that, it didn't help

**Comment by steam3d** [comment]
@wheelman944 sorry but I can't do anything, because the MagicPods get Bluetooth data from Windows, so I can't affect how Windows works

**Comment by steam3d** [comment]
@wheelman944 From my side - no. The MagicPods works as expected. I know only 2 cases that my uses said to me. 
1. Manually update or downgrade Bluetooth driver (not using Windows update)
2. Reinstall windows (I highly not recommend this method)


Usually Windows and apps break when user use some app to optimize their Windows.

**Comment by steam3d** [comment]
No feedback
