### ISSUE TITLE
When disconnecting the AirPods using MagicPods, the AirPods do not disconnect properly from the device's Bluetooth. I have to manually disconnect them from the Bluetooth settings in Windows.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#358]
When disconnecting the AirPods using MagicPods, the AirPods do not disconnect properly from the device's Bluetooth. I have to manually disconnect them from the Bluetooth settings in Windows.

When using MagicPods to disconnect the AirPods, they do not disconnect correctly from the device's Bluetooth. As a result, I have to manually disconnect them from the Bluetooth settings in Windows.

I use AirPods Pro-2
a Microsoft Windows 11
Version 22H2 OS Build 22621.1848

**Comment by steam3d** [comment]
Hi. I found solution. I will fix disconnect next update.

**Comment by steam3d** [comment]
Update to 2.0.53.0. I fixed
