### ISSUE TITLE
Request for auto close popup

### ISSUE THREAD

**Issue by JacksonWan** [steam3d/MagicPods-Windows#36]
I like how AirPods status can be viewed when it's connected, but it can be annoying sometimes when it doesn't auto close by itself and I have to do the "x" every time. The purpose of popup status is to show a quick glance at the battery status of AirPods. I feel like there should be an option for users to customize how long the popup should display after the popup.

**Comment by steam3d** [comment]
This is a known bug. I'll try to find a reason.

**Comment by steam3d** [comment]
Fixed update to 1.0.58.0
