### ISSUE TITLE
Soundcore Liberty 4NC

### ISSUE THREAD

**Issue by VladFromLat** [steam3d/MagicPods-Windows#360]
Hello

I'v got an issue. MagicPods doesn't determinate & show my new Soundcore Liberty 4 NC in a list of headphones.
It works well with my Soundcore Space Q45 (this model appeared in a list of headphones immedially after connection)
but the new model Liberty 4NC doesn't appear although it connects to PC without problem.

Any idea how to make it work so that I can see Soundcore Liberty 4NC & use it in MagicPods in proper way?

**Comment by steam3d** [comment]
Hi. Enable extended log and upload the log files here.

1. Open MagicPods go to Support page
2. Click the MagicPods logo until the page refresh (5 times and more).
3. Go to General Settings then scroll down
4. Expand Developer option and change Log level to Debug

Close the MagicPods and open it again and wait while headphones list is loaded.  Upload the log files here.

The MagicPods find Bluetooth devices that mapped by Windows as headphones if device is mapped to different type it will skipped.

**Comment by VladFromLat** [comment]
Here is the log file.
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/12077803/log.txt)

**Comment by steam3d** [comment]
This is wrong long.  It's from debug app to check Bluetooth issues. You need simple log from MagicPods. 
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/b31ac1f5-df56-4fe4-9aab-30f32fba85f8)

**Comment by VladFromLat** [comment]
sorry for wrong log file. uploading 2 correct log files.
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/12078072/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/12078074/MagicPodsUILog.txt)

**Comment by VladFromLat** [comment]
I'm using Soundcore Space Q45 also on 2 devices - PC & mobile phone & have no problem.
Soundcore Liberty 4 NC works with same mobile app and same pairing mode. all the same, connects to mobile & PC,
works perfect, but... is not appearing in Magic Pods.
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/12078587/log.txt)

**Comment by steam3d** [comment]
soundcore Liberty 4 NC does not appears because it has `ServiceCapabilities 290`.  Windows SDK does not provide info which device type is.

**Comment by VladFromLat** [comment]
Does it mean that Liberty 4NC will not work at all and there's no way to fix this issue?

**Comment by steam3d** [comment]
I can't enable devices with "290" code, because I do not know how Windows work with such device. If I enable devices with 290 code they can crush MagicPods for other users.

You can show this menu to check what headphones can do
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/7f718603-e779-42a7-9040-6fc4959cafd8)

<https://help.magicpods.app/issue-connectivity/>

**Comment by VladFromLat** [comment]
Re: [steam3d/MagicPods-Windows] Soundcore Liberty 4NC (Issue #360)



Many thanks.

Thursday, October 12, 2023, 12:12:26 AM, you wrote:





In update 2.0.56.0 headphones like your will be displayed in MagicPods headphones list.
