### ISSUE TITLE
Always disconnect

### ISSUE THREAD

**Issue by flutetian** [steam3d/MagicPods-Windows#361]
Hi.When I used the airpods pro2 on my Lenovo laptop, everything worked fine, but when I used it on the rog host, the connection was immediately disconnected and not working. The host's system was Win10, and the computer motherboard was ROG STRIX B760-G GAMING WIFI.I tried this many times, and re-downloaded the latest Bluetooth driver, but it was still unsuccessful.

**Comment by steam3d** [comment]
Hi. It's problem of AirPods Pro 2 itself. A lot of users have this problem on all operating systems except mac os and ios
