### ISSUE TITLE
Display charge of both AirPods in system tray

### ISSUE THREAD

**Issue by rakleed** [steam3d/MagicPods-Windows#365]
Could you please add an option to display the charge of both AirPods in the system tray besides the average charge of both? In the end, they discharge at different speeds, and sometimes it would be more convenient to know in advance when they need to be charged.

**Comment by steam3d** [comment]
Hi. Just hover mouse on icon
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/788c68c6-1d89-4a56-9604-64370ba581aa)

**Comment by rakleed** [comment]
I know, but I would like to be able to see this information without hover.

**Comment by steam3d** [comment]
The icons size is 16x16 for some systems, I can't fit two numbers here. As other apps shows info:
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/6b585cbc-a952-4c74-8a44-d9846308aa52)

**Comment by rakleed** [comment]
Is the icon always square anyway? It couldn't be more vertical anywhere?

And is it possible to fit two values ​​by making the font smaller and placing one value above and the other below?

**Comment by steam3d** [comment]
The icon is always square. I attached the screenshoot above your message. The font size will be as icon with 1467 digit.  I already tested it - it's not usable. I learn how to use Windows widgets, it's better for such task

**Comment by steam3d** [comment]
Added as icon with two batteries
