### ISSUE TITLE
The “Streaming device" function is not functioning properly.

### ISSUE THREAD

**Issue by AlenWill** [steam3d/MagicPods-Windows#368]
It sounds like the buffer is not set correctly.
When I linked my iPhone and attempted to stream the sound to the AirPods Pro (second-generation) connected to a Windows computer, the voice sounded intermittent. At this point, it was confirmed that the device was within normal connection range and there was no signal interference. After replacing the computer, iPhone, and headphones, this issue recurred.

**Comment by steam3d** [comment]
Hi. I can't acess to deep settings like codec or buffer. It controlled by Bluetooth driver.

**Comment by AlenWill** [comment]
Okay, but have you tried to reproduce this issue based on my feedback?

**Comment by steam3d** [comment]
As I said it depends from Bluetooth driver settings. I did no have such issue, but couple mounths ago my Bluetooth driver updated and I got the same issue.
