### ISSUE TITLE
Why there is no pop up window when I connect with airpods pro2?

### ISSUE THREAD

**Issue by DOGGOD11** [steam3d/MagicPods-Windows#369]
Also no battery information. How can I solve the problem?

**Comment by steam3d** [comment]
Hi.  Open the case with AirPods inside and bring it to the PC. The popup window will appear

**Comment by steam3d** [comment]
Which version of AirPods Pro 2 do you have?

**Comment by DOGGOD11** [comment]
the latest version with usb-c

**Comment by steam3d** [comment]
Update with support the last version AirPods Pro is processing by Microosft store. So we are waiting

**Comment by steam3d** [comment]
No feedback
