### ISSUE TITLE
Request for case battery indicator on taskbar icon

### ISSUE THREAD

**Issue by JacksonWan** [steam3d/MagicPods-Windows#37]
It's nice that there is an indicator on my taskbar that shows the battery status for left and right AirPods, but it'll be even nicer when it displays the battery status the case has left when I put one of my AirPods back to the case.

**Comment by steam3d** [comment]
It won't always work. If the action takes 1-2 seconds, the application may not even recognise that you opened the case. 
I will of course study this point, but I'm not sure if it will work well.

**Comment by steam3d** [comment]
You can turn on "Fast search", when you put one AirPod in the case you can wait 1-3 sec the battery of case will appear on MagicPods status page.
