### ISSUE TITLE
Double tap and triple tap support for AirPods Pro 2 USB-C

### ISSUE THREAD

**Issue by pharo3** [steam3d/MagicPods-Windows#370]
I have noticed that all Windows apps recognize the single tap (play/stop) gesture when using the newest version of the AirPods Pro 2, but only YouTube appears to be compatible with double tap (skip) and triple tap (skip back).

Please add support for this functionality.

**Comment by steam3d** [comment]
Hi. This is impossible. Bluetooth driver controls headphones buttons. I don't have access to it

**Comment by pharo3** [comment]
That's a bummer. Although I assume that the Bluetooth driver itself should be able to detect double/triple tap if YouTube can recognize them, right? Would there be a way to make this work for other apps on my own?

**Comment by steam3d** [comment]
Processing Bluetooth keys depends from application developers. For example some media player simple ignore the command "skip", because developer does not process this command. You need to write to each app a program helper that will convert actions
