### ISSUE TITLE
Request：Shortcut keys, animation, Popup size

### ISSUE THREAD

**Issue by Mino-shi** [steam3d/MagicPods-Windows#372]
1. Before learning about 'Magicpods', I used to use' SoundSwitch 'to switch the functions of Bluetooth devices. I used to use shortcut keys such as「win」 +「`/~」, but it is not supported in 'Magicpods'. Unfortunately, as a global shortcut, I need to try to avoid conflicts with other applications and make it easy for my fingers to operate on the keyboard. I think this feature can have.

2. I know that the animation of 'Magicpods' is very beautiful, but for me, who is accustomed to fast and efficient operations, it is not smooth to use. Therefore, I think it is possible to add a' no animation 'feature to improve usage speed. 

3. The 'Bluetooth Device Detection Popup' and 'Bluetooth Device Switching Popup' for 'Magicpods' on screens larger than 1920px are too small, especially the 'Switching Popup.' It appears as a tiny, barely visible rectangle at the bottom with a lengthy animation. 
If it's possible to customize the size and animation, it would be a great help for people like me with less than perfect eyesight.

I believe that a supplementary tool's greatest advantage is its lightweight nature and efficiency. While I appreciate making my computer look better, I value a clean backend even more. Thank you for taking the time to read this.

**Comment by steam3d** [comment]
1.Public Windows API does not allow to use some keys. I do not know why.  Even if  I get a success binded shortcut message from Windows some some keys do not work.

2. Maybe if some other users will want to see this feature

3. Open settings and choose different size

![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/d8f10173-8bd6-45f1-ad02-bd7bcbfe6292)
