### ISSUE TITLE
Startup refresh bug

### ISSUE THREAD

**Issue by gferreroferri** [steam3d/MagicPods-Windows#373]
I get his when I start the app in a small window. See screenshot 
![image](https://github.com/steam3d/MagicPods-Windows/assets/823394/8e52b37c-b640-47dd-ac4f-307a0b6d78c7)

**Comment by steam3d** [comment]
Hi. It is known Microsoft framework issue. I couldn't affect on it.

**Comment by gferreroferri** [comment]
OK. Understood. Thanks!
