### ISSUE TITLE
Disable connect on startup

### ISSUE THREAD

**Issue by Finedand** [steam3d/MagicPods-Windows#376]
Current Behavior:
Currently, when my Windows PC starts up, my AirPods automatically connect even if I am already using them with my iPhone or iPad. This forces me to manually reconnect them to my iOS device, disrupting my listening experience.

Expected Behavior:
I propose the addition of a new feature that allows users to disable automatic AirPods connection on Windows PC startup. Instead, the AirPods should only connect when a specific hotkey is triggered by the user.

**Comment by steam3d** [comment]
@Finedand Windows Bluetooth stack designed like you described. When you turn off then turn on Bluetooth or reboot pc, the Windows will try to connect to each device in devices Bluetooth list.

I did not find any good way to prevent it.

**Comment by Finedand** [comment]
Thanks for the response, it's not a huge deal i seldom turn off my pc. Amazing app btw thank you!
