### ISSUE TITLE
Always shows that my airpods pro is dead but actually has power.

### ISSUE THREAD

**Issue by Dirac0328** [steam3d/MagicPods-Windows#377]
Always shows that my airpods pro is dead but actually has power. It pauses the music when it shows no battery

**Comment by steam3d** [comment]
Hi. Do you have other people around who use AirPods Pro?

**Comment by Dirac0328** [comment]
Probably no.But im in a study room,im not sure for that.The problem appears randomly.
Pls tell me how to aviod that

**Comment by steam3d** [comment]
Seems that someone around you also using AirPods. The searching AirPods is not accurate process, because Apple does not allow to track or inedify their headphones.
So I did my best to create search as accurate as possible. You could turn off `Fast search` feature maybe it will help.
