### ISSUE TITLE
Cannot find Airpods

### ISSUE THREAD

**Issue by JoanneQN** [steam3d/MagicPods-Windows#378]
The hearphone is already connected to the computer, and the sound in computer can be normally heared of.
But in the magicpods, the airpods cannot be find. The debug files are attached as follows
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/13246121/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/13246120/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Hi. It's Bluetooth driver issue or Windows settings. The MagicPods works as expected.

**Comment by JoanneQN** [comment]
OK, it turns out to work well after i update my windows system and reinstall the magicpods, thanks for your response
