### ISSUE TITLE
Connecting Device Causes Crashing of Some Application

### ISSUE THREAD

**Issue by thoangg** [steam3d/MagicPods-Windows#379]
When reconnecting my wireless headphones its cycles through all possible output devices over and over causing some of my applications on my PC to crash.

**Comment by steam3d** [comment]
Hi. Issue is not related to MagicPods.  MagicPods only send request connect to Windows one time.  You could try to disable the HandsFree. HandsFree is often make troubles.

**Comment by thoangg** [comment]
Hi, I disabled handsfree and it seems to keep happening. Not sure what else to do.

**Comment by steam3d** [comment]
You could try re-pair headphones, maybe be Windows will update something under hood
