### ISSUE TITLE
Auto play/pause support for iTunes UWP plz

### ISSUE THREAD

**Issue by tnqzh123** [steam3d/MagicPods-Windows#38]
I use iTunes UWP as my music player because I'm using Apple Music. It didn't paused automatically when I take my AirPods Pro off. iTunes UWP seems not available for system media control?

**Comment by steam3d** [comment]
I tried to add this. For unknown reason iTunes not always react on play / pause commands. I will found another way

**Comment by steam3d** [comment]
Added. Update to 1.0.72.0.
