### ISSUE TITLE
Poor connection with AirPods Pro 2

### ISSUE THREAD

**Issue by SLoMp111** [steam3d/MagicPods-Windows#381]
Sometimes, during use, the sound is interrupted and restored after a while. Also, sometimes the headphones seem to switch to talk mode on the phone. How can this be fixed?

**Comment by steam3d** [comment]
It's common Bluetooth issue. Some Bluetooth dongles have such issue some not. The AirPods Pro 2 is working good only on Apple devices. 

To prevent switching to HandsFree mode - simple disable it. When you connect headphones the Windows first switch headphones to handsfree mode then to audiosink. When some app request microphone the headphones is also switch to handsfree.

**Comment by SLoMp111** [comment]
That is, just disable HandsFree?

**Comment by SLoMp111** [comment]
That is, just disable HandsFree?

**Comment by steam3d** [comment]
Yes. The microphone of AirPods Pro 2 will not be available, but as side effect it will improve connection speed.

**Comment by SLoMp111** [comment]
Thanks
