### ISSUE TITLE
Couldn't find AirPods Infinite Search

### ISSUE THREAD

**Issue by Neutrovertido** [steam3d/MagicPods-Windows#383]
Hi.
My AirPods fail to work with MagicPods, I tried the three solutions in https://help.magicpods.app but to no avail. I'm using Windows 11

Here's my log

![image](https://github.com/steam3d/MagicPods-Windows/assets/61665012/567d9ff3-5326-43df-9997-da7fcf5f04f7)

**Comment by steam3d** [comment]
Hi. Did you try to restore system files?
https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca

**Comment by Neutrovertido** [comment]
I ran the two commands, rebooted but the problem still persist

**Comment by steam3d** [comment]
When you run DeviceFinder (like shown on your screenshot) and open the AirPods case with AirPods inside does the application show running numbers?

**Comment by steam3d** [comment]
No feedback
