### ISSUE TITLE
AirPods Pro 2 Ear detection and Auto connect 

### ISSUE THREAD

**Issue by TechFlux1011** [steam3d/MagicPods-Windows#384]
Hello,
My name is Marshall and I'm a full stack  java developer. I recently bought this app because I was looking for all of this functionality in native windows to no avail.  I own the airpods pro 2 and i wanted to see if there is something i can do to help bring full functionality to the airpods pro 2. please lmk

**Comment by steam3d** [comment]
Hi. This is noted on https://help.magicpods.app/fun-capability/ 
The AirPods Pro 2 does not support these features

**Comment by steam3d** [comment]
Implemented on MagicPods 2.0.72.0. [MagicAAP driver required](https://help.magicpods.app/fun-magicaap/)
To discuss, join [MagicPods Discord](https://discord.com/invite/UyY4PY768V)

> Auto connect will not work unfortunately
