### ISSUE TITLE
托盘右键菜单总是跑到任务栏后面，无法操作。

### ISSUE THREAD

**Issue by SalicylicAcid** [steam3d/MagicPods-Windows#385]
![image](https://github.com/steam3d/MagicPods-Windows/assets/37034452/84e5a580-5c7a-4a31-805e-408e6f574c08)

**Comment by steam3d** [comment]
你好，这是一个已知的错误。没有解决方案。其他托盘应用程序也有同样的问题。
您使用的是 WH-1000XM3，MagicPods 支持 ANC 控制。 我建议您将 MagicPods 更新到最新版本。

Hi. It's a known bug. There is no solution. Other tray apps also have the same issue.
You use WH-1000XM3, the MagicPods supports ANC control for it.  I recommend updating the MagicPods to the latest version.
