### ISSUE TITLE
The app only shows info after closing and opening again

### ISSUE THREAD

**Issue by RenierC** [steam3d/MagicPods-Windows#387]
After booting up when I open the app my headphones never show, but after closing and opening it shows. 

<img width="897" alt="image" src="https://github.com/steam3d/MagicPods-Windows/assets/6173288/613c2bc0-468a-4d94-8c8b-b0348e349d2b">

Then if i close it and open it again I see it as normal

![image](https://github.com/steam3d/MagicPods-Windows/assets/6173288/6a0311de-e262-45fd-a146-e0b0561cbc93)

I'm on version 2.0.58.0 x64

**Comment by steam3d** [comment]
Hi. Upload the log files from the support page.

**Comment by RenierC** [comment]
> Hi. Upload the log files from the support page.

The button debug button doesn't seem to do anything. How do I get this logs?

**Comment by steam3d** [comment]
Okay, let's try manual way

1. Win+r
2. Paste and click enter `%LOCALAPPDATA%\Packages\715AleksandrMaslov.MagicPods_vk1h99z2mpttm\TempState`
3. Upload all txt files

**Comment by steam3d** [comment]
When did the problem start? Have you tried reinstalling the application?

**Comment by RenierC** [comment]
> When did the problem start? Have you tried reinstalling the application?

It has always been like that for me, yes I have tried reinstalling multiple times

**Comment by steam3d** [comment]
This is a strangle. The log shows that everything is fine, but sometimes you could have this issue, but it's very rare.

You can try to use the app with debug log on. It will give additional info, maybe we will find something here.

1. Open MagicPods on the Support page
2. Click on MagicPods logo (10 times) until the page refreshes
3. Go to general settings and scroll down in the developer option, switch log level to debug
4. Use the app as usual. When you get the issue, upload the new log files here

**Comment by RenierC** [comment]
These are the logs after doing the steps on the list

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/13654183/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/13654184/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Most likely a Windows problem. Check system files can help https://help.magicpods.app/report-issue/#check-system-files
