### ISSUE TITLE
Airpods doesn't disconnect after taking both airpods out of ear.

### ISSUE THREAD

**Issue by theashiqshow** [steam3d/MagicPods-Windows#389]
Airpods doesn't disconnect even after taking both airpods out of ear. And audio keeps playing when inside the airpods case.

**Comment by steam3d** [comment]
Airpods disconnects in two cases:

1. When idle some time
2. When connect to charge contacts inside the case

In your case clear the contact inside the case for left and right airpods and clear contscnt on the left and right AirPods legs
