### ISSUE TITLE
Close connect indicator by clicking anywhere in backdrop.

### ISSUE THREAD

**Issue by amitrajofficial** [steam3d/MagicPods-Windows#39]
*This is a feature request and not a bug.

When we open the airpods it gets connected and battery indicator is shown on the Screen in a pop-up. But to close that pop-up we need to click on cross button in the popup. Would be great if we can get a feature to close it if user clicks anywhere else on the screen other than the pop-up or maybe autohide the pop-up it after 2-5 seconds.

**Comment by steam3d** [comment]
Fixed. Now window must hide correctly. Update the app to 1.0.58.0
