### ISSUE TITLE
airpods的电量显示不精确

### ISSUE THREAD

**Issue by nuo-nuo-0** [steam3d/MagicPods-Windows#391]
耳机的电量只能精确到10%，如25%、35%等等，尤其在低于25%时，会出现直接从25%然后直接没电的情况
耳机为airpods pro generation 1st，软件为version2.0.59.0 X64

**Comment by nuo-nuo-0** [comment]
补充：耳机型号：airpods pro generation 1st ;Model A2084; 固件6A300

**Comment by steam3d** [comment]
你好。AirPods 发送的数据就是我显示的数据。充电步骤为 10%。可能是电池老化或其他原因。

**Comment by nuo-nuo-0** [comment]
谢谢，那应该是AirPods在非苹果设备上返回的电量值只有若干档，不是精确到1%？

**Comment by steam3d** [comment]
果苹公司没有透露有关 AirPods 工作原理的细节。目前，这是获得充电电量的唯一方法。

**Comment by nuo-nuo-0** [comment]
好的，谢谢
