### ISSUE TITLE
Airpod 2 Pro doesn't show Case precentage

### ISSUE THREAD

**Issue by NivMinkov** [steam3d/MagicPods-Windows#393]
![image](https://github.com/steam3d/MagicPods-Windows/assets/25706088/ad622ccc-1c24-4c07-95a7-0c9560aec52e)
on WIN10
trial version
case opened when photo taken
PC is Lenovo P14s gen 2i, windows updates done and Lenovo Vantage updates done.

**Comment by steam3d** [comment]
Hi. Place AirPods inside the case, to check case battery.

**Comment by NivMinkov** [comment]
> Hi. Place AirPods inside the case, to check case battery.

Hey thanks after restart it's working
