### ISSUE TITLE
airpods pro and airpods 2 not work

### ISSUE THREAD

**Issue by TyperEJ** [steam3d/MagicPods-Windows#4]
I tried my airpods pro and airpods 2 . it's not work.
I just purchase it QQ .

**Comment by steam3d** [comment]
Hello. Try unpair Airpods Pro from PC and try only with AirPods 2.
Describe what you did and send **debug log** file

**Comment by TyperEJ** [comment]
2020/3/26 上午 10:55:31 38:EC:0D:4F:D7:1A --- Find EJ’s Model airpodspro Connected
2020/3/26 上午 10:55:31 ----------------- --- AirPods found
2020/3/26 上午 10:55:31 ----------------- --- Advertisement watcher started!
2020/3/26 上午 10:57:17 ----------------- --- Settings: Animation           True
2020/3/26 上午 10:57:17 ----------------- --- Settings: Animation_rssi      -60
2020/3/26 上午 10:57:17 ----------------- --- Settings: Search_max_rssi     0
2020/3/26 上午 10:57:17 ----------------- --- Settings: Search_min_rssi     -60
2020/3/26 上午 10:57:17 ----------------- --- Settings: Volume_down_percent 0.25
2020/3/26 上午 10:57:17 ----------------- --- Settings: EarDetection        Volume
2020/3/26 上午 10:57:17 ----------------- --- Settings: DebugMode           True
2020/3/26 上午 10:57:17 ----------------- --- Connection to UWP lost
2020/3/26 上午 10:57:17 ----------------- --- Try to connect
2020/3/26 上午 11:01:01 ----------------- --- Settings: Animation           True
2020/3/26 上午 11:01:01 ----------------- --- Settings: Animation_rssi      -60
2020/3/26 上午 11:01:01 ----------------- --- Settings: Search_max_rssi     0
2020/3/26 上午 11:01:01 ----------------- --- Settings: Search_min_rssi     -60
2020/3/26 上午 11:01:01 ----------------- --- Settings: Volume_down_percent 0.25
2020/3/26 上午 11:01:01 ----------------- --- Settings: EarDetection        Volume
2020/3/26 上午 11:01:01 ----------------- --- Settings: DebugMode           True
2020/3/26 上午 11:01:01 ----------------- --- Connection to UWP lost
2020/3/26 上午 11:01:01 ----------------- --- Try to connect
2020/3/26 上午 11:15:12 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Disconnected(IsAirPodsConnected False)
2020/3/26 上午 11:27:52 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Connected(IsAirPodsConnected True)
2020/3/26 上午 11:44:51 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Disconnected(IsAirPodsConnected False)
2020/3/26 上午 11:47:32 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Connected(IsAirPodsConnected True)
2020/3/26 下午 12:31:56 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Disconnected(IsAirPodsConnected False)
2020/3/26 下午 12:31:57 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Connected(IsAirPodsConnected True)
2020/3/26 下午 12:32:00 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Disconnected(IsAirPodsConnected False)
2020/3/26 下午 12:32:02 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Connected(IsAirPodsConnected True)
2020/3/26 下午 12:33:17 38:EC:0D:4F:D7:1A --- ConnectionStatus Bluetooth 38:ec:0d:4f:d7:1a Disconnected(IsAirPodsConnected False)

log looks have record but not show any hint .

**Comment by steam3d** [comment]
I released an update, it must fix AirPodsPro issue. As soon as Microsoft confirms it, it will come to everyone

**Comment by TyperEJ** [comment]
![image](https://user-images.githubusercontent.com/42922266/77645543-d4440e80-6f9d-11ea-96d0-31874650101a.png)
repeat show this alert no matter what i click

**Comment by steam3d** [comment]
Oh. Sorry for this. I do't have AirpodsPro and it is little difficult to found issue.  I will try to deal with it as quickly as possible

**Comment by TyperEJ** [comment]
It's work !! thx for your help! 👯‍♂

**Comment by 1404794545** [comment]
But why it doesnt show airpods2 's animation ,when i connect to my airpods2.it only show the battery

**Comment by steam3d** [comment]
Try to bring the case as close as possible to the bluetooth adapter and open the case.  Wait 3-7 seconds
