### ISSUE TITLE
Move popup window from center screen to near icons tray position

### ISSUE THREAD

**Issue by spbmiac** [steam3d/MagicPods-Windows#40]
Please notice that dock can be not at the bottom, I use left position for example
Or just give us opportunity to move pop-up window and store that position.

That's not so important to show it on centre of screen, also often I use airpods with phone so just notice about charging is enough.

ps: 
if start menu on bottom side: popup needs to be shown right down 
if start menu on left side: popup needs to be shown left down

Thanks

**Comment by steam3d** [comment]
Added. Update the app to 1.0.58.0
