### ISSUE TITLE
查询调试日志

### ISSUE THREAD

**Issue by M1tsuha1127** [steam3d/MagicPods-Windows#400]
半个月前被别人偷走的耳机，刚才突然弹窗，查询调试日志过后发现确实有长达十秒的弹窗，请问如果没检测到耳机是不是不可能出现这种情况，或者说能一定说明耳机就在附近被打开了？

**Comment by steam3d** [comment]
Hi. Apple does not allow detect headphones directly, so MagicPods doesn't know which headphones yours. I use algorithm to guess which headphones possible yours.

苹果不允许直接检测耳机，因此 MagicPods 不知道您的耳机是哪一款。我使用算法来猜测可能是你的耳机

**Comment by M1tsuha1127** [comment]
16.04.2024 09:47:12 47:AF:7D:B7:D5:08  -85 [Info]  |  PopupWatcher  | Case close(  ) : L in  R in 
16.04.2024 09:48:21 4E:E8:48:26:BD:C4  -82 [Info]  |  PopupWatcher  | Case open (LR) : L out R out
16.04.2024 09:48:33 4E:E8:48:26:BD:C4  -60 [Info]  |WindowManagement| Show window
16.04.2024 09:48:42 4E:E8:48:26:BD:C4  -85 [Info]  |WindowManagement| Hide window
16.04.2024 09:48:42 4E:E8:48:26:BD:C4  -85 [Info]  |  PopupWatcher  | Case open ( R) : L out R out
16.04.2024 09:49:56 5D:3B:27:4A:46:48  -96 [Info]  |  PopupWatcher  | Case open (LR) : L out R out
16.04.2024 09:51:29 7D:25:C5:78:C6:4B  -81 [Info]  |  PopupWatcher  | Case close( R) : L in  R out


16.04.2024 14:14:24 5F:7F:93:58:30:38  -90 [Info]  |  PopupWatcher  | Case close(  ) : L in  R in 
16.04.2024 14:14:50 6F:16:2C:EB:A5:64  -76 [Info]  |  PopupWatcher  | Case open (LR) : L out R out
16.04.2024 14:14:53 6F:16:2C:EB:A5:64  -64 [Info]  |WindowManagement| Show window
16.04.2024 14:14:53 6F:16:2C:EB:A5:64  -69 [Info]  |WindowManagement| Hide window
16.04.2024 14:14:53 6F:16:2C:EB:A5:64  -69 [Info]  |  PopupWatcher  | Case open ( R) : L out R out
16.04.2024 14:14:53 7A:54:D2:64:CB:0E  -75 [Info]  |  PopupWatcher  | Case open ( R) : L out R out
16.04.2024 14:14:54 7A:54:D2:64:CB:0E  -75 [Info]  |  PopupWatcher  | Case open ( R) : L in  R out

I didn't quite get what you meant, my headphones are airpods II, but these are the only pods I've ever paired on my computer, and since the window popped up then these can only be my headphones, is that what you mean?

**Comment by steam3d** [comment]
I mean that no one except Apple could not know which headphones yours. Apple made it by privacy reason. Your log shows that someone has AirPods around you because the signal is low. it is possible it is your neighbors.

If you want to find your headphones, then use Find My service from apple.

**Comment by M1tsuha1127** [comment]
ty for your response
