### ISSUE TITLE
there is no pop-up window and the playback cannot be automatically paused.

### ISSUE THREAD

**Issue by culiuo4** [steam3d/MagicPods-Windows#402]
The sound can be heard normally in the headphones and the battery level of the headphones is displayed, but there is no pop-up window and the playback cannot be automatically paused.

**Comment by steam3d** [comment]
Hi. Do you have original or fake AirPods?

**Comment by culiuo4** [comment]
Original iPods pro 2

**Comment by steam3d** [comment]
You can read about all the features here:
https://help.magicpods.app/headphones/apple-airpodspro2/

The pop-up animation will display when both AirPods are in the case and the case is opened.

**Comment by culiuo4** [comment]
I have read about this page and installed driver. And yes both airpods are in the case and the case is opened.
I also tried adjusting the search scope.

**Comment by steam3d** [comment]
Upload the log files from preferences page. Did the battery of AirPods Pro 2 display without driver?

**Comment by culiuo4** [comment]
[MagicPodsServiceLog.txt](https://github.com/user-attachments/files/16390036/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/user-attachments/files/16390037/MagicPodsUILog.txt)
Yes.Battery displayed before I installed the driver.

**Comment by steam3d** [comment]
You have extremely low radio signal strength. You need to set AirPods search radius to 100-110, after it, you will see the pop-up. I recommend do not use pop-up windows at all due to signal strength

**Comment by culiuo4** [comment]
Wait...So if I replace my Bluetooth signal device, will it work normally? Is it because the signal is poor that the auto-pause function cannot be used normally?
😢😢😢😢

**Comment by steam3d** [comment]
No, it's only for pop-up window. 
Auto-pause will try to pause playback when your headphones disconnects from pc.
Ear detection - will try to play / pause when you put on and put out AirPod into / from the ear

**Comment by culiuo4** [comment]
Okay.Thank you for your time and patience.💕
