### ISSUE TITLE
Airpods 4 is not supported

### ISSUE THREAD

**Issue by FeRhodium** [steam3d/MagicPods-Windows#406]
Need a enhancement

**Comment by steam3d** [comment]
Which AirPods 4 or AirPods 4 ANC?

**Comment by FeRhodium** [comment]
ANC Version

**Comment by steam3d** [comment]
MagicPods has basic support for AirPods 4 ANC. The ability to toggle between noise-cancelling modes will be available later and requires the installation of the MagicAAP driver.
