### ISSUE TITLE
Always reconnect when start up OS

### ISSUE THREAD

**Issue by AdemJensen** [steam3d/MagicPods-Windows#41]
This software automatically connects to the Airpods Pro after OS start up even if the target device is already in use, and it wasn't connected to the Device before OS shutdown.
This brings an issue that when using Airpods on an iPhone, the start up of my computer will disconnect the previous connection by accident and make something awkward...

**Comment by steam3d** [comment]
Yes. This is standard behaviour of windows 10. Usually when you turn on PC the WIndows check all bt device around and try to connect them. I am not taking full control of the AirPods. It can make some trouble for inexperienced users.
You can try enable only connect button. (Not enable auto-connect option).

In addition, I will check on my PC if everything works exactly as expected.

**Comment by AdemJensen** [comment]
I have looked up more info on the internet, it seem that there is no solution right now...

**Comment by steam3d** [comment]
I can make AirPods not available to connect, but you must use the MagicPods to connect AirPods or manually enable services.
I will think about advanced settings for experienced users

**Comment by Billybobertjoe** [comment]
still happens even with auto connect turned off and show connect button option turned on.

**Comment by 7HE-W0R1D** [comment]
same, can confirm that it reconnects even if auto connect is turned off

**Comment by steam3d** [comment]
Unfortunately, the Windows does not allow control this.
