### ISSUE TITLE
`Run on startup` stops working

### ISSUE THREAD

**Issue by rakleed** [steam3d/MagicPods-Windows#410]
`Run on startup` has not been working for some time, but it worked without problems before. The advice in https://help.magicpods.app/report-issue/ didn't help.

[MagicPodsLogs.zip](https://github.com/user-attachments/files/17791692/MagicPodsLogs.zip)

**Comment by steam3d** [comment]
Hi. I did not make any changes to the 'run on startup' feature. This issue is on your Windows side.

**Comment by steam3d** [comment]
The logs displayed that startup is enabled. I do not see any crash or something.
