### ISSUE TITLE
Button "Connect" do not translated on Russian

### ISSUE THREAD

**Issue by valdemar1977** [steam3d/MagicPods-Windows#42]
Not a bug, but a perfectionist nightmare ;). Please localize it if it is not so hard to realize.
Many thanx

**Comment by steam3d** [comment]
This is known issue, it will be fixed next update

**Comment by steam3d** [comment]
Done. Update to 1.0.55.0

**Comment by valdemar1977** [comment]
Yahoo!!! Done right
