### ISSUE TITLE
Headphone icon in the taskbar

### ISSUE THREAD

**Issue by asul1** [steam3d/MagicPods-Windows#43]
I would like to see a clearer image of the airpods in the taskbar. Also the ability to choose a white or dark icon. Because the app icon is lost among the white icons.

**Comment by steam3d** [comment]
Hi. Did you update the app to 1.0.54.0? It brings fix when tray icon was blurry. 
I am not sure that i understood second part. The app switch between white and dark icon automatically it depended what windows theme used now.
