### ISSUE TITLE
This is one the worst app for AirPods support on Windows 10

### ISSUE THREAD

**Issue by michaeljackson99** [steam3d/MagicPods-Windows#44]
The music doesn't pause when I pull an AirPod out of my ear, the connection is the worst part tho. The audio is constantly cutting and distorted, the funny thing is when I close out of this app the audio is normal. The app doesn't work properly plus worsens the sound quality.

**Comment by steam3d** [comment]
Hi. It depends on Bluetooth module and strength radio signal from your pc. Some Bluetooth modules better some not. Because of that you have 1 free day to test the app and make sure that app works with your hardware.

**Comment by michaeljackson99** [comment]
My bluetooth module cannot be the issue as;
I have an iMac which drives the AirPods perfectly in macOS
and the AirPods have 0 sound issues when MagicPods is fully closed, the issues start to arise once I open the app.

**Comment by steam3d** [comment]
I do not write the drivers. I use capabilities of your Bluetooth driver. It means that problem with your specific driver or bluetooth module. I cannot affect the driver manufacturer.

**Comment by michaeljackson99** [comment]
The drivers are not the issue because my AirPods don't have any issues when I close the app. The sound is fine (there aren^t any crackles) until I open the app and then it gets messed up. The play/pause function is hit or miss too, couldn't get it to work all the time.

**Comment by steam3d** [comment]
As i told above i use ` capabilities of your Bluetooth driver`. When you use AirPods without app, you use only audio playback. To get battery info or ear detection those required addition information. This means that when app is running it get at the same time audio and addition information. And it means your BT dongle or drivers can't works with audio and addition information at the same time.
