### ISSUE TITLE
Click tray icon to connect AirPods

### ISSUE THREAD

**Issue by LewisSpring** [steam3d/MagicPods-Windows#45]
Hello there,
My idea is that by clicking the tray battery icon (or in it's right click menu), MagicPods will connect and switch audio devices to the AirPods.
This means that if the audio source is wrong or the airpods happen to be disconnected, both issues would be fixed just by clicking (a/the) button. 

Thanks!

**Comment by windingwind** [comment]
Agree! This feature will be very helpful.
I think adding a button  in the rightclick menu would be a good choice.
like this:
![59651725E89A684BA147ACB4B11BAF77](https://user-images.githubusercontent.com/33902321/104600224-b1f9b980-56b3-11eb-9b70-39f962e3932e.png)

**Comment by thelewiss1** [comment]
Half of this feature is already implemented now - it'll switch the audio source.

**Comment by steam3d** [comment]
I understand that this is a great function. But as it turned out, it has many problems, for example, when bluetooth is disabled and etc.  I concentrate to fix existing bugs and finish up small things like icons and text. This feature will be implemented in the future

**Comment by NikopolL** [comment]
+1

**Comment by steam3d** [comment]
Not good news, I can connect Bluetooth device but can't disconnect it. I will try to look for other ways
![image](https://user-images.githubusercontent.com/30986874/121582305-81863380-ca37-11eb-8102-48912eead8ef.png)

**Comment by steam3d** [comment]
Added partially. Update to 1.0.72.0.
_Disconnect not available now, i will add it when find necessary api._
