### ISSUE TITLE
Add more than Airpods, please.

### ISSUE THREAD

**Issue by Shua131** [steam3d/MagicPods-Windows#46]
I understand how strange (and difficult to implement) this is as this app is geared toward Airpods, but could you please add Sony WF-1000XM's and Galaxy Buds (Classic, Plus, and Live) to the app as that would be very helpful to someone who owns those, such as myself. I know that this is ALOT to ask, and that it would require integration of other APIs, but please consider it, I would love to be able to control my noise cancelling from my tablet as well as see the battery of my earbuds. Again, sorry for the rather large request.

**Comment by steam3d** [comment]
I know that Sony WF-1000XM is possible to set-up (battery and etc.) But i don't have those headphones. I can do nothing without it.

**Comment by Shua131** [comment]
I have them, is there any way I could help?

**Comment by Shua131** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/5599029/log.txt)

**Comment by Void48** [comment]
bump. please support for Sony XM4s!

**Comment by steam3d** [comment]
attach to https://github.com/steam3d/MagicPods-Windows/issues/21
