### ISSUE TITLE
Does not work Windows 10 / AirPods Pro

### ISSUE THREAD

**Issue by denniske** [steam3d/MagicPods-Windows#5]
Hi, I have just downloaded the trial version of your app.

I started the app and opened the case of my airpods pro. But it does not work. Here is a screenshot:

![image](https://user-images.githubusercontent.com/1076211/78108426-a6c0f000-73f7-11ea-99f9-f8d122c4ffd5.png)

It says Connected (1) in the bluetooth area. But I cannot see airpods in the bluetooth device list and I they also do not show up as audio device.

Before using your app I used the airpods with my computer so it should not be a problem with my computer / airpods. I also unpaired the airpods before installing the app.

One additional question. When I start the app I alsways get to the settings dialog. How can I choose to to the initial setup again from there?

**Comment by denniske** [comment]
![image](https://user-images.githubusercontent.com/1076211/78108791-5d24d500-73f8-11ea-930a-7c8de5054c84.png)

**Comment by steam3d** [comment]
Hi. Application does not connect or pair AirPods. If there are no AirPods in the system, it will not work. Make sure the AirPods work before starting the program.

1. Pair your AirPods to PC. 
2. Open the app and turn on startup.
3. Bring your Airpods case(with headphones inside) as close as possible to pc then open case and wait 3-5 sec.

**Comment by denniske** [comment]
I have now paired the airpods pro and restarted the app. I enabled startup. But it still does not do anything when opening the case.

![image](https://user-images.githubusercontent.com/1076211/78110954-2f418f80-73fc-11ea-9b62-9718e55d2413.png)

Also the tile does not display anything:

![image](https://user-images.githubusercontent.com/1076211/78110997-41233280-73fc-11ea-8434-34393b23f74f.png)

**Comment by steam3d** [comment]
Can you send full log file?

**Comment by denniske** [comment]
Yes, here is the full log file:

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/4413711/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Did you try reinstall app? I think it will not help, but maybe system restore some settings and something change.
It is looks app has infinity loop. I am not sure where the problem is. I will try to fix it next update.

**Comment by denniske** [comment]
I reinstalled it 1 hour ago when you told me that I need to pair the airpods first.
Okay I will wait for the update. Maybe you can add more logging.
My trial is expiring in 22 hours though.

**Comment by steam3d** [comment]
An update has been released. I'm not sure it will help or not. If it is still relevant write to me

**Comment by juanchohq** [comment]
everything is working in this side... thanks for the update. Is in the roadmap full support for AirPods Pro?

**Comment by steam3d** [comment]
@juanchohq Apple does not provide information about how their devices work.  As soon as there’s some way to get more features, I’ll immediately add them.

**Comment by juanchohq** [comment]
Thanks a lot for all your work!... the app is great! I hope also that in the near future apple change the way that share information of their products...

**Comment by denniske** [comment]
[MagicPodsServiceLog-New.txt](https://github.com/steam3d/MagicPods-Windows/files/4588463/MagicPodsServiceLog-New.txt)

@steam3d It still does not work. I have paired air pods with pc and they work well. I put them in case and run startup and then open the case and nothing happens.

**Comment by steam3d** [comment]
@denniske Okay. It looks like your bluetooth works a little differently. Let's try check this. Run DebugError.exe wait 5-10 sec -> Close DebugError.exe -> Send me a file **log.txt** that appear near DebugError.exe
[DebugError.zip](https://github.com/steam3d/MagicPods-Windows/files/4588976/DebugError.zip)

**Comment by denniske** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/4589065/log.txt)

**Comment by steam3d** [comment]
@denniske Okay. Try this. I can't understand why your version windows response on my request another way. 
[DebugError_v2.zip](https://github.com/steam3d/MagicPods-Windows/files/4589107/DebugError_v2.zip)

**Comment by denniske** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/4591369/log.txt)

I had the air pods in the case all time during this test. Should I open the case or anything else?

**Comment by steam3d** [comment]
No. Everything fine. Do you have two airpods pro paired on your pc?
The log said that you have 2 device AirpodsPro. One works right, second with issue.

**Comment by denniske** [comment]
I have only one pair. But I have removed and paired them again multiple times in the last weeks.

![image](https://user-images.githubusercontent.com/1076211/81268781-aea02f80-9048-11ea-9a31-5f4bc75a2cde.png)

**Comment by denniske** [comment]
![image](https://user-images.githubusercontent.com/1076211/81269029-09d22200-9049-11ea-911f-32cdd36432b3.png)

**Comment by denniske** [comment]
Maybe it is this:

![image](https://user-images.githubusercontent.com/1076211/81269081-1fdfe280-9049-11ea-8a45-e08b4fbef818.png)

**Comment by denniske** [comment]
I have removed the unknown bluetooth device and ran debug error again:
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/4591526/log.txt)

**Comment by steam3d** [comment]
I do not know why your system show 2 times AirPodsPro. I fixed your problem, but I do not know if this will affect other users. Try this version. If everything is okay, I will add a fix in the next update
[DebugError_v4.zip](https://github.com/steam3d/MagicPods-Windows/files/4591643/DebugError_v4.zip)

**Comment by denniske** [comment]
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/4591945/log.txt)

**Comment by steam3d** [comment]
@denniske I released the update. Try the app.

**Comment by denniske** [comment]
@steam3d Thank you, it is working now :)

![image](https://user-images.githubusercontent.com/1076211/81342380-6d913500-90b3-11ea-9aca-0eca8695f6b0.png)

**Comment by steam3d** [comment]
Hi. Can you help? I need log from you, because a lot of people got error after fix your problem.
[DebugError_v6.zip](https://github.com/steam3d/MagicPods-Windows/files/4640075/DebugError_v6.zip)

**Comment by denniske** [comment]
Okay here is the log:

[log.txt](https://github.com/steam3d/MagicPods-Windows/files/4640152/log.txt)

**Comment by saad642** [comment]
dear app maker of Magicpods,
I just downloaded the trial version of your app and it is not working with airpods pro.I have done every thing that is required but still it is not working
<img width="960" alt="Screenshot 2021-06-22 131536" src="https://user-images.githubusercontent.com/86288967/122889112-f15fbc80-d35b-11eb-9f6a-b89673cbf1ea.png">

**Comment by saad642** [comment]
plz help me in fixing this issue

**Comment by saad642** [comment]
if it works I might buy it

**Comment by steam3d** [comment]
@saad642 
This issue mostly depend from your Bluetooth adapter, drivers or Windows update.
There are 3 ways can helps.
1. Remove the MagicPods.  Reboot your PC. Install MagicPods again. Try to use the app.
2. Update bluetooth drivers from manufactory site (not through windows update usually it does not have the latest drivers). Update windows and reboot you PC. Try to use the app
3. If steps above did not help, then you Bluetooth module not supports.

Also you need to upload the log file to check your problem. The MagicPods can't access to bluetooth directly, this way the bluetooth is controlled by the system and I cannot change it.

**Comment by saad642** [comment]
Thanks for the quick reply.Ihave tried all the above mentioned steps But still it is not working for me.I have also Updated the drivers from the manafactureres website.This my bluetooth adapter's frimvare let me know if this is supported or not and the second image is my airpods pro bluetooth services.The log file is also included
<img width="443" alt="Screenshot 2021-06-22 191040" src="https://user-images.githubusercontent.com/86288967/122949745-57b50100-d395-11eb-80fb-5ede181b51cc.png">
<img width="256" alt="Screenshot 2021-06-22 200418" src="https://user-images.githubusercontent.com/86288967/122949797-613e6900-d395-11eb-90d0-116113d2755c.png">
<img width="283" alt="Screenshot 2021-06-22 200433" src="https://user-images.githubusercontent.com/86288967/122949802-61d6ff80-d395-11eb-98ae-08e809683ab7.png">
<img width="278" alt="Screenshot 2021-06-22 200446" src="https://user-images.githubusercontent.com/86288967/122949809-63082c80-d395-11eb-8f16-4afc7cfdd781.png">
<img width="263" alt="Screenshot 2021-06-22 200502" src="https://user-images.githubusercontent.com/86288967/122949811-63a0c300-d395-11eb-80c0-f44dc433cec0.png">
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6695462/MagicPodsServiceLog.txt)

**Comment by saad642** [comment]
I am really looking foward to buying it if this works

**Comment by juanchohq** [comment]
Here works perfect! worth every penny! buy with confident!

**Comment by steam3d** [comment]
@saad642 Unfortunately it looks like your bluetooth not compatible with the AirPods.  Your Bluetooth module just not receive data from AirPods, based on this is not possible to do something. (Note: Music can play any Bluetooth dongle, but for additional functions need "support equipment")

**Comment by saad642** [comment]
But it is not working for me.I will buy only if it works and displays the battery.I am currently using the trial version of it.If anyone does know how to fix this issue.Here is the log file

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6695723/MagicPodsServiceLog.txt)
 help plz

**Comment by steam3d** [comment]
@steam3d It is hardware problem. There is no way no fix this. Most people are helped by the instructions described above, if it did not help, then for my part I can not do anything.

**Comment by saad642** [comment]
😟

**Comment by saad642** [comment]
can you recommend a bluetooth dongle that works
