### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Actualygayaf** [steam3d/MagicPods-Windows#51]
I got the app and i have no idea why is it in russian... How can i translate it to English ASAP... Pls help

**Comment by steam3d** [comment]
Hi. Check your language settings. Windows set the language for all apps.
Also make first keyboard EN (bottom of the screesnshot)
![image](https://user-images.githubusercontent.com/30986874/102582699-2cb2d180-4114-11eb-9baa-6405332fedb9.png)

**Comment by steam3d** [comment]
No feedback.
