### ISSUE TITLE
AirPods Max

### ISSUE THREAD

**Issue by spn91** [steam3d/MagicPods-Windows#54]
Hi, could you please add the new AirPods Max? Please let me know how i can help with it.

**Comment by steam3d** [comment]
Hi. You can try this:
https://github.com/steam3d/MagicPods-Windows/issues/21
*Step 6. Listen music 5-10 sec

But i am not sure how AirPods Max works. It is always on, maybe it behave different from regular AirPods.

**Comment by Void48** [comment]
Hey can you please add support for AirPods Max (animations and other things) ?

**Comment by steam3d** [comment]
I am not sure that possible to add AirPods max without having it. I am studying their work on the provided log file, they work differently and it is not yet clear how exactly to get the battery charge. At the same time, I think I found the definition of an ear.

**Comment by steam3d** [comment]
@spn91 @Void48 Which color AirPods max Do you have?

**Comment by steam3d** [comment]
Hi. New update The MagicPods 1.0.71.0 is available. You can use your AirPods Max now :)
