### ISSUE TITLE
Airpods pro Mic

### ISSUE THREAD

**Issue by JustYannicc** [steam3d/MagicPods-Windows#58]
are you gonna add support for the AirPods mic because it isn't supported in windows otherwise?

**Comment by steam3d** [comment]
Hi. AirPods Pro's microphone works with any operating system. Windows by default add two services headset and headphones. If you don't have those services maybe your bluetooth driver not updated or Bluetooth stick doesn't support some of audio services.
https://github.com/steam3d/MagicPods-Windows/wiki/Connectivity-issues

**Comment by JustYannicc** [comment]
Yeah, but what I am talking about is that you can use it at the same time as using the headphones. Because currently there are two different audio devices you can select when connecting AirPods and I think one of them is the headphones but Idk. But when wanting to use the mic the headphones turn off and I cant hear anything anymore
![image](https://user-images.githubusercontent.com/52761674/103940600-e3134080-512d-11eb-93b3-5eca7fdf65ae.png)
![image](https://user-images.githubusercontent.com/52761674/103940631-f0302f80-512d-11eb-950e-6ed1bdbc9a7f.png)

**Comment by steam3d** [comment]
You need to switch Audio output of your voice app. Some apps use Headset as microphone and external speaker as headphones. 

You must have the headset on playback tab and the headset on recording tab. Like this:

![image](https://user-images.githubusercontent.com/30986874/103988812-c31c6500-519f-11eb-8dfd-75fd65e6f609.png)
![image](https://user-images.githubusercontent.com/30986874/103988831-c9aadc80-519f-11eb-9fdb-4cea4202b411.png)

**Comment by steam3d** [comment]
Closed. No feedback.
