### ISSUE TITLE
The pop-up window has garbled characters

### ISSUE THREAD

**Issue by wp231** [steam3d/MagicPods-Windows#63]
![Snipaste_2021-01-11_17-33-00](https://user-images.githubusercontent.com/56443833/104164646-2d006d00-5433-11eb-9c62-43bb142b7fe0.png)

**Comment by steam3d** [comment]
Hi. Do you use emoji in your AirPods name?

**Comment by wp231** [comment]
No I just use "Airpod Pro"

**Comment by wp231** [comment]
But now it is suddenly gone

**Comment by steam3d** [comment]
The problem was solved.

**Comment by wp231** [comment]
Yes
