### ISSUE TITLE
Never Recognize my Airpods

### ISSUE THREAD

**Issue by Naif1992** [steam3d/MagicPods-Windows#64]
During the app trial period, it was working fine. When I purchased it, however, it stopped recognizing my Airpods. I tried reinstalling  MagicPods and removing the Airpods and adding it again with no luck. 

Please support.

**Comment by steam3d** [comment]
Can you attach the log file?

**Comment by Naif1992** [comment]
> Can you attach the log file?

HYG[
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/5795758/MagicPodsServiceLog.txt)
](url)

**Comment by steam3d** [comment]
Did you have windows update? Did you try to reboot pc? The MagicPods works right. It does all the necessary things. For unknown reason bluetooth module does not receive information.

1. Open MagicPods app
2. Go to Support page
3. Click on logo until it blink (5 times and more)
4. Go to general settings
5. Switch log level to trace
6. Restart the MagicPods

After steps above try to use AirPods with app. Note than MagicPods can search your AirPods about 10 second after you connect them

**Comment by steam3d** [comment]
Closed. No feedback.
