### ISSUE TITLE
Cannot automatically switch the default player

### ISSUE THREAD

**Issue by wp231** [steam3d/MagicPods-Windows#66]
![image](https://user-images.githubusercontent.com/56443833/104817013-8dd7dd00-5859-11eb-94b6-a7b94d35998e.png)
![image](https://user-images.githubusercontent.com/56443833/104817059-d2fc0f00-5859-11eb-963a-b9608c34ee59.png)
I have reinstalled countless times but it still doesn't work

**Comment by wp231** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/5824734/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Looks like you did not have Microsoft Visual C++ 2015 Redistributable. Try to install it
 https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by wp231** [comment]
Thanks it's working now

**Comment by steam3d** [comment]
Thx for feedback. I will add instruction to MagicPods app how to fix this issue.
