### ISSUE TITLE
Can not connect to airpods

### ISSUE THREAD

**Issue by BraveSail** [steam3d/MagicPods-Windows#67]
When take out airpods from box Magicpods connect and disconnect quickly cycle. But airpods is working fine and not disconnnect.

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/5877846/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Hi. This is known issue and it does not have solution.
There are three theoretical reasons:
1. Bluetooth module can't work with Classic bluetooth and Bluetooth low energy at the same time
2. Bluetooth driver installed with error
3. Windows has broken system file(s)

You can go to `support` page. Click 5 times or more on logo until it refresh. Go to `general settings` scroll down to `developer mode` and switch `log level` to `trace`. Restart app and try again use MagicPods. After it attach your log file.

Unfortunately i can't reproduce this issue on my PC. (I use 3 different bluetooth modules).

**Comment by BraveSail** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/5899280/MagicPodsServiceLog.txt)

**Comment by BraveSail** [comment]
![GIF](https://user-images.githubusercontent.com/49320262/106376698-a08cfe80-638f-11eb-8068-c32f839fccb2.gif)

**Comment by BraveSail** [comment]
大概1.0.58之前的版本是正常的，之后的版本就连不上了，耳机并没有掉线，就是软件连不上一直搜索重连

**Comment by steam3d** [comment]
I released the new 1.0.61.0 version it includes extra log information about this problem. You can try it.
I checked you last log, it does not include additional information. This means that everything works fine, except reason why windows stop Bluetooth service

**Comment by steam3d** [comment]
I got the same error after 10 or 15 times turn off and turn on bluetooth. For unknown reason just restart app does not help.
i found the only solution delete MagicPods (check that process MagicPodsService.exe terminated). Restart PC and try to install MagicPods again.

I can't fix program this issue because windows does not respond on my requests.

**Comment by BraveSail** [comment]
Now it works again.
