### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ohanedan** [steam3d/MagicPods-Windows#7]
Hello, You said that you want Airpods Pro test on reddit. I am testing it now and it works very well. I have 2 feature requests.
- An option to the settings to make the tray icon appear only when the airpods are connected.
- When we double-click tray icon, instead of showing settings, can we preview charge percentage like the box opening? I know that the charging of the box cannot be shown when the two pods are not in the box. But only the charge of the pods can be shown. 

Thank you.

**Comment by steam3d** [comment]
Hi.
1) I can make it, but it depends on Microsoft Store. It may look like an application running without the knowledge of the user.
2) I work on it.

**Comment by ohanedan** [comment]
I don't know much about Microsoft Store rules but I think it will not be a problem because it's just an option in the settings. You are the developer, the final choice is yours 👍 
I will follow the developments,
Thanks.

**Comment by steam3d** [comment]
Done. Update to MagicPods_1.0.21.0
