### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by AC202** [steam3d/MagicPods-Windows#73]
Hi, sorry for the question...
But I'm a little bit just interesting in that thing of animation and I wondered if you can please sent me the animation of the AirPods? and if you have than also Airpods Max? 
Thank you so much!!!

**Comment by AC202** [comment]
?

**Comment by AC202** [comment]
can you please answer?

**Comment by steam3d** [comment]
Hi. You can easily find animation in google or youtube. The MagicPods not support AirPods Max according of this i don't try to find this animation.
https://www.youtube.com/watch?v=I1HdBAQeGoI

**Comment by AC202** [comment]
Hello! Thanks for the respond, I got how to do it , by the way I’ve made a really good animation with the airpods max ,if you want to add them I’ll be happy to sent it for you. Sent from Mail for Windows 10 From: Alexander MaslovSent: יום שני 15 פברואר 2021 20:00To: steam3d/MagicPods-WindowsCc: AC 1; AuthorSubject: Re: [steam3d/MagicPods-Windows] Animation (#73) Hi. You can easily find animation in google or youtube. The MagicPods not support AirPods Max according of this i don't try to find this animation.https://www.youtube.com/watch?v=I1HdBAQeGoI—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		בלי וירוסים. www.avast.com
