### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by ujvszabi** [steam3d/MagicPods-Windows#78]
Hello there!

On march 1st the app updated on microsoft app store and since then the app doesn't work. The app opened but the taskbar icon didn't show and after i connected my airpods pro in bluetooth settings the app didn't realize anything. Idk what the problem is☹️ 

I reinstalled it and checked the settings but I found nothing. 
(PS.: i use the full version of the app not the trial) 

Please let me know if you had some information.

Thanks

**Comment by steam3d** [comment]
Hi. I saw your email. Let’s check your log file.

Open MagicPods app -> Go to support page -> Debug log
or
Path to log file %UserProfile%\AppData\Local\Temp\MagicPodsLogs

What windows 10 build do you use? 
win+r -> type: winver -> click ok

**Comment by ujvszabi** [comment]
Okey i sent you the logs file and a screenshoot of the win10 build version to your email. Thanks for the help.

**Comment by steam3d** [comment]
@ujvszabi Open MagicPods app -> support page -> Click 5-8 times to logo until it refreshes -> general settings page -> scroll down -> Change "Log level" to Trace -> restart app.

After it try to open MaigcPods as usual and send again the log file.

**Comment by ujvszabi** [comment]
The problem is still there. I sent you again the log file and the task manager screens.

**Comment by steam3d** [comment]
@ujvszabi Last log message was 2021. 03. 02. 11:22:45. When you click debug log does the explorer open? 
I just install the MagicPods from Store. I have the same windows build and it is works well.  
Did you try uninstalling app, the reboot pc and install it again? (Delete log file because app must create it when its start, maybe it helps to understand reason)

**Comment by ujvszabi** [comment]
When i click on debug log nothing happens. Okey i try to reinstall again and delete log file.

**Comment by ujvszabi** [comment]
Here is the airpods version if you need for it.![image](https://user-images.githubusercontent.com/75737126/110111985-6d37f800-7db1-11eb-8d0f-9df6733dab33.png)

**Comment by steam3d** [comment]
Does MagicPods works after reinstalling?

**Comment by ujvszabi** [comment]
Im doing now.

**Comment by ujvszabi** [comment]
Now its working fine. Thank you very much man!
![ScreenShot_20210305130631](https://user-images.githubusercontent.com/75737126/110114083-59da5c00-7db4-11eb-8a50-bf45f29d4fff.png)
