### ISSUE TITLE
Not working with AirPods Pro

### ISSUE THREAD

**Issue by uAdmAgH** [steam3d/MagicPods-Windows#8]
It seems like everything is okay but , in spotify when i try to listen something it constantly skips the song to a next one and goes like that , anywhere else like youtube etc. there is no sound. 

Error log : From MainWindow MediaFailed System.Runtime.InteropServices.COMException (0xC00D109B)

**Comment by steam3d** [comment]
Hi.
1) MagicPods can't control media playback or disable sound (only control volume). There are not this functions. Do youtube or spotify work correctly without MagicPods?

2) It looks like you have trouble with video when animation shown. It can randomly happen. Usually restart app will fix this. I know this problem, but I can not find a solution to the problem now

**Comment by steam3d** [comment]
Closed. Did not receive a response.
