### ISSUE TITLE
System Tray icon not appearing

### ISSUE THREAD

**Issue by hchavan-cmd** [steam3d/MagicPods-Windows#81]
I'm on a free trial right now, almost about to make the jump to buy the app. But I noticed that after a restart, the system tray icon doesn't appear, neither does the battery pop up on connection. Is there something I'm missing, some setting I need to tweak?
Do note, I have enabled MagicPods as a startup app, and some of the features I enabled are functioning. The visual cues are just missing. 
The device in mention is PowerBeats Pro.

**Comment by hchavan-cmd** [comment]
I did manage to fix it up with an uninstall of MagicPods. But then I faced the pitfall of being hosted on the Store. It wouldn't allow me to download it again. I did manage to reboot it and make it function once again, this time around the reboot test not messing up the app function.

**Comment by hchavan-cmd** [comment]
On a different note (not an issue), what's the principle behind the Low Latency mode? I'm not completely sure if my observation is right, but the connection seems a bit more stable with it on. So, I am curious.

**Comment by steam3d** [comment]
Sometimes after the free trial. you will need delete the app, reboot pc and then install it again. There are extra small count users who has this issue.

I do not have the PowerBeats Pro but on AirPods gen 2 and Pro this feature disable "standby mode to save energy" when you do not use AirPods for a while.  Exit from standby mode take about 0.2 -0.4 second
