### ISSUE TITLE
Pop-up window keeps pop up when other airpods opened.

### ISSUE THREAD

**Issue by mukata69** [steam3d/MagicPods-Windows#85]
Pop-up window keeps pop up when other airpods opened.
It never paired with my pc.
please see video for more info https://imgur.com/a/bbVlMug

**Comment by steam3d** [comment]
This is normal behaviour.  Apple does not allow Identify AirPods. This limitation cannot be circumvented without Apple's permission.

**Comment by penz6** [comment]
It happens on MACOS and IOS devices as well, its just the way they are designed.
