### ISSUE TITLE
popup window slide animation shaking when there are 2 displays.

### ISSUE THREAD

**Issue by Sheey11** [steam3d/MagicPods-Windows#88]
<video src="https://user-images.githubusercontent.com/13375959/114664823-d86cd680-9d2e-11eb-9543-8d26efa1b2e3.mov"/>

**Comment by steam3d** [comment]
Hi. Unfortunately, i can't fix it now, because i do not have a second display.
I added you case to task tracker.  I will return when will have access to second monitor.

**Comment by steam3d** [comment]
Fixed. Update to 1.0.80.0.
