### ISSUE TITLE
Can't tick Startup (Run on startup box)

### ISSUE THREAD

**Issue by trongtinh1212** [steam3d/MagicPods-Windows#9]
I have tried many ways but no luck
![image](https://user-images.githubusercontent.com/32267081/81256899-072cf800-905c-11ea-89bb-19081bc7b1d4.png)

**Comment by steam3d** [comment]
Hi. 
> App is disabled by the administrator or company group policy. Note: It can be enabled only by the administrator.

You can try open task manager -> startup -> try to find MagicPods
Or right click on tile MagicPods -> settings -> startup

**Comment by trongtinh1212** [comment]
> Hi.
> 
> > App is disabled by the administrator or company group policy. Note: It can be enabled only by the administrator.
> 
> You can try open task manager -> startup -> try to find MagicPods
> Or right click on tile MagicPods -> settings -> startup

tried , it's still disable in Task manager
and i have pop up too much, and wrong battery percent

**Comment by trongtinh1212** [comment]
my account is adminstrator too

**Comment by steam3d** [comment]
Can you reinstall app? Try to enable startup and send screenshot of task manager startup.

![image](https://user-images.githubusercontent.com/30986874/81265381-adbccd00-904b-11ea-85f9-deeba2efecdc.png)

Note that app does not works with Windows S mode.

**Comment by trongtinh1212** [comment]
i have tried reinstall,and  pop up came up too much (wrong battery percent)
![image](https://user-images.githubusercontent.com/32267081/81265863-f84f4100-906d-11ea-8a80-49529363c793.png)
tried change to enable but it's auto changed to disable

**Comment by steam3d** [comment]
I don’t know how to help you now. I tried on virtual machines of different configurations and I can’t prevent auto-start by Windows policy. I will find solution.
![image](https://user-images.githubusercontent.com/30986874/81272497-3b9db580-9056-11ea-88e8-5ddab370c21e.png)
Change settings to this. 

It will disable popup. You can check battery level by app tile or click arrow back on settings page.
Also send log file.

**Comment by steam3d** [comment]
1) Win+r -> type **regedit** -> click enter
2) Go to *HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System**
3) Do you have **SupportFullTrustStartupTasks** key?
![image](https://user-images.githubusercontent.com/30986874/81337270-71bd5280-90b3-11ea-8d57-9767fb2eac59.png)

**Comment by trongtinh1212** [comment]
clean install windows fixed for me, but I still have splash pop up to much ( it's show battery but showed to many times) maybe this is a bug

**Comment by steam3d** [comment]
Can you send a log file? I can't help without it

**Comment by trongtinh1212** [comment]
full log : https://drive.google.com/file/d/1R1w1vNwv5FjYwPLc6y83CVbzHbzC0tVt/view?usp=sharing

**Comment by steam3d** [comment]
I don't have access to the file. Check share settings

**Comment by trongtinh1212** [comment]
check it again, sorry

**Comment by steam3d** [comment]
You need sitting at the computer as usual and look at live signal setting. (airpods must be connected) What is the average value?
For your log i recommend set the **signal** to -50 <-> -55
![image](https://user-images.githubusercontent.com/30986874/81393355-e5e60d80-9128-11ea-883b-9aa75ce36289.png)

**Comment by trongtinh1212** [comment]
i'm working at office and many people have airpod too, i think this app showed wrong battery percent maybe not mine

**Comment by steam3d** [comment]
You are right. Because windows has low refresh rate of bluetooth information. Based on your testimony. Your headphones have a signal from -38 to -55
If you change **Search AirPods** min value to -50 or -55 and AirPods splash screen signal value to -50 or -55 Maybe it helps.  
But considering that you have an incredibly good signal. I would even try -45

**Comment by trongtinh1212** [comment]
in my laptop the Spash screen seem too small, maybe u should add option to customize the size of splash screen ?

**Comment by steam3d** [comment]
Thx for feedback. I already planned to add this.

**Comment by trongtinh1212** [comment]
i'm home now but the splash seem so anoying too much
https://pastebin.com/TkQWiSJX

**Comment by steam3d** [comment]
Can you enable debug mode?  When you will get multiple splash send me the log file.  
Also check task manager. App should looks like 
![image](https://user-images.githubusercontent.com/30986874/81407761-9f061100-9144-11ea-9ad3-b61b3cbace68.png)

**Comment by trongtinh1212** [comment]
> i'm home now but the splash seem so anoying too much
> https://pastebin.com/TkQWiSJX

already enable, check at 7.00 PM
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/4599055/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Update to the latest version. I fixed the bug.
