### ISSUE TITLE
add support for auto switching

### ISSUE THREAD

**Issue by CJNiiva** [steam3d/MagicPods-Windows#90]
I know you have support for autoswitching back to the default audio device, but what about switching from default to the airpods when they connect? I have a program installed (displayfusion) that automatically detects my displays and switches to the gaming headset when I have only my 2 monitors active, but what about the times that windows screws up, or I have multiple bluetooth devices connected that have audio, this would be great for not just me, but maybe more people, I'm assuming this is a simple thing to implement though, I have no experience with programming though, so I'm uncertain, love the program anyways

**Comment by steam3d** [comment]
The MagicPods automatically switch to AirPods when they are connected. The MagicPods take a 10 second to find your AirPods after it connected, after successful find AirPods and check that one of AirPods inside the ear, the app switches the audio output to AirPods.

To avoid 10 seconds pause you can enable Fast search, but i highly recommend not use this option if someone except you use AirPods.  

I am not sure that i understand last part of your message, but if you mean automatically detect your default device (not set it on settings page). It is tricky thing.  When AirPods is connecting sometimes windows says that default device is already AirPods for this reason i can't get your real default device.

**Comment by steam3d** [comment]
No feedback.
