### ISSUE TITLE
Небольшая ошибка в подписи наушников

### ISSUE THREAD

**Issue by artemvodorez** [steam3d/MagicPods-Windows#93]
При наведении на иконку в трее отображается заряд наушников. Подписи наушников Л и Р. На русском должно быть Л и П или Лв и Пр (если в выбранном шрифте эти буквы выглядят слишком похожими).

**Comment by steam3d** [comment]
Привет. Пока поменяю на Л,П. Сейчас место только под 2 символа заложено.  Если интересно, можно и самому править перевод и предлагать более удачные формулировки, тут https://weblate.magicpods.app/

**Comment by steam3d** [comment]
Исправлено в апдейте 1.0.71.0
