### ISSUE TITLE
Malware Shown in App 

### ISSUE THREAD

**Issue by StxrzLA** [steam3d/MagicPods-Windows#94]
![image](https://user-images.githubusercontent.com/83698851/117119737-61a18700-ad8a-11eb-97b4-14f2422e0985.png)

This shows that there is a virus in your application, please resolve this issue

**Comment by steam3d** [comment]
Hi. The app does not have any Malware. Your Scanner catch MagicPodsUI.exe - this exe provide user interface and manage notification. Windows defender did not show any issues and Microsoft Store team.

Just add the folder to ignore list.

**Comment by steam3d** [comment]
@StxrzLA What antivirus do you use? I want to contact to developer company
