### ISSUE TITLE
Infinite search

### ISSUE THREAD

**Issue by BradCOnGitHub** [steam3d/MagicPods-Windows#95]
I keep getting the infinite search bug. 

I'm a dev and can help you debug it. Just tell me what to do.

**Comment by steam3d** [comment]
There are no way to fix this.  I make request to WIndows API to start bluetooth scan. Windows answer "success"  and after about 1 second windows stop scanning. This happens endlessly.  

I found only one way to fix this, uninstall app -> reboot pc -> install again.

**Comment by BradCOnGitHub** [comment]
Some combination of shutting off bluetooth, putting the airpods into their case, and restarting both of your processes does fix it without a reinstall or reboot.

What's the API call?

**Comment by steam3d** [comment]
BLE watcher

https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher?view=winrt-19041
________________________________

**Comment by steam3d** [comment]
No feedback.
