### ISSUE TITLE
Hope the pop-up function improves

### ISSUE THREAD

**Issue by wp231** [steam3d/MagicPods-Windows#99]
I hope to be able to pop out the pop-up window when the charging box is opened or there is a headset in the charging box, but it is not necessary to have both earphones in the charging box to have the pop-up window-AirPods Pro

**Comment by steam3d** [comment]
Most users do not expect this behavior, it can be confusing to them.
But you can check case battery as you describe (only without popup) after turning on "Fast search"
The charge of the case appears if you put one earphone in an open case on  (Open MagicPods and go to the status page).
